import { z } from 'zod';
export const id=z.string().uuid();
const text=z.string().trim().min(1).max(200);
const note=z.string().trim().max(5000).default('');
const email=z.email().max(200).transform(s=>s.toLowerCase());
export const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().startsWith(v),'Invalid calendar date').transform(v=>new Date(v+'T00:00:00.000Z'));
const optionalId=id.nullable().optional();
const money=z.number().int().min(0).max(1_000_000_000);
export const password=z.string().min(8).max(128).refine(v=>/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v)&&/[^A-Za-z0-9]/.test(v),'Use at least 8 characters with uppercase, lowercase, number and symbol.');
export const loginSchema=z.object({email:z.string().trim().min(1).max(200).transform(v=>v.includes('@')?v.toLowerCase():v.toUpperCase()),password:z.string().min(1).max(128),companyCode:z.string().trim().max(80).optional(),remember:z.boolean().default(false)}).strict();
export const tenantSchema=z.object({name:text,plan:z.enum(['STARTER','GROWTH','ENTERPRISE']).default('STARTER'),employeeLimit:z.number().int().min(1).max(100000).default(25),ownerName:text,ownerEmail:email,ownerPhone:z.string().trim().max(30).default('')}).strict();
export const employeeSchema=z.object({employeeCode:text,firstName:text,lastName:text,email,phone:z.string().max(30).default(''),photo:z.string().max(8_000_000).default(''),departmentId:optionalId,branchId:optionalId,shiftId:optionalId,managerId:optionalId,designation:z.string().max(100).default(''),employmentType:z.enum(['FULL_TIME','PART_TIME','CONTRACT','INTERN']).default('FULL_TIME'),joiningDate:date,status:z.enum(['ACTIVE','PROBATION','NOTICE','INACTIVE']).default('ACTIVE'),monthlySalary:money.default(0),personal:z.object({gender:z.string().max(40).optional(),dob:z.string().max(10).optional(),bloodGroup:z.string().max(10).optional(),maritalStatus:z.string().max(30).optional(),nationality:z.string().max(80).optional(),address:z.string().max(1000).optional(),city:z.string().max(100).optional(),state:z.string().max(100).optional(),pincode:z.string().max(20).optional(),emergencyContact:z.string().max(200).optional(),emergencyPhone:z.string().max(30).optional(),aadhaar:z.string().max(20).optional(),pan:z.string().max(20).optional(),uan:z.string().max(30).optional(),pfNumber:z.string().max(50).optional(),esicNumber:z.string().max(50).optional(),bankName:z.string().max(120).optional(),accountHolder:z.string().max(150).optional(),accountNumber:z.string().max(50).optional(),ifsc:z.string().max(30).optional(),bankBranch:z.string().max(120).optional(),workLocation:z.string().max(150).optional(),shiftName:z.string().max(100).optional(),probationEnd:z.string().max(10).optional(),confirmationDate:z.string().max(10).optional(),qualification:z.string().max(300).optional(),experience:z.string().max(300).optional(),skills:z.string().max(1000).optional(),notes:z.string().max(2000).optional()}).default({})}).strict();
export const orgSchema=z.object({name:text,code:text,description:note}).strict();
export const branchSchema=z.object({name:text,code:text,location:text,addressLine:z.string().trim().max(300).default(''),city:z.string().trim().max(100).default(''),state:z.string().trim().max(100).default(''),pincode:z.string().trim().max(20).default('')}).strict();
export const shiftSchema=z.object({name:text,startMinute:z.number().int().min(0).max(1439),endMinute:z.number().int().min(0).max(1439),graceMinutes:z.number().int().min(0).max(120).default(10),earlyOutGraceMinutes:z.number().int().min(0).max(120).default(10),workingDays:z.string().regex(/^(?:[0-6](?:,[0-6])*)$/,'Use comma-separated weekday numbers: 0=Sun ... 6=Sat').default('1,2,3,4,5'),breakMinutes:z.number().int().min(0).max(180).default(60),fullDayMinutes:z.number().int().min(60).max(960).default(480),halfDayMinutes:z.number().int().min(30).max(600).default(240),overtimeAfterMinutes:z.number().int().min(60).max(960).default(480),timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true}catch{return false}}).default('Asia/Kolkata')}).strict();
export const deviceSchema=z.object({name:text,vendor:z.enum(['TCW_MOBILE','BIOMAX','ZKTECO','ESSL','MATRIX','REALTIME','MANTRA','HIKVISION','CPPLUS','DAHUA','SUPREMA','ANVIZ','SPECTRA','VIRDI','GENERIC']),model:z.string().max(100).default(''),serialNumber:text,branchId:optionalId,connectionMode:z.enum(['EMPLOYEE_APP','NATIVE_PUSH','CLOUD_PUSH','LAN_PULL','WIFI_LAN','MIDDLEWARE']).default('NATIVE_PUSH'),host:z.string().regex(/^[a-zA-Z0-9.:-]*$/).max(255).default(''),port:z.number().int().min(1).max(65535).default(5005),timezone:z.string().max(80).default('Asia/Kolkata')}).strict();
export const leaveTypeSchema=z.object({name:text,annualDays:z.number().min(0).max(366),paid:z.boolean().default(true)}).strict();
export const leaveSchema=z.object({employeeId:id,leaveTypeId:id,startDate:date,endDate:date,halfDay:z.boolean().default(false),reason:text,requestKey:z.string().trim().min(8).max(80).optional()}).strict().refine(v=>v.endDate>=v.startDate,'End date must follow start date').refine(v=>!v.halfDay||+v.startDate===+v.endDate,'Half days must use one date').refine(v=>v.startDate.getUTCFullYear()===v.endDate.getUTCFullYear(),'Split requests across calendar years');
export const eventSchema=z.object({title:text,date,endDate:date.nullable().optional(),kind:z.enum(['HOLIDAY','HR_EVENT','TRAINING','INTERVIEW','PAYROLL','APPRAISAL']).default('HR_EVENT'),description:note}).strict().refine(v=>!v.endDate||v.endDate>=v.date,'End date must be on or after start date');
export const jobSchema=z.object({title:text,departmentId:optionalId,location:text,openings:z.number().int().min(1).max(10000).default(1),employmentType:z.enum(['FULL_TIME','PART_TIME','CONTRACT','INTERN']).default('FULL_TIME'),description:note,status:z.enum(['OPEN','PAUSED','CLOSED']).default('OPEN')}).strict();
export const candidateSchema=z.object({name:text,email,phone:z.string().max(30).default(''),jobId:id,stage:z.enum(['APPLIED','SCREENING','SHORTLISTED','INTERVIEW','TECHNICAL','HR','OFFER','HIRED','REJECTED']).default('APPLIED'),notes:note,interviewAt:z.iso.datetime().transform(v=>new Date(v)).nullable().optional()}).strict();
export const goalSchema=z.object({employeeId:id,title:text,target:z.number().int().min(1).max(1e6),progress:z.number().int().min(0).max(1e6).default(0),dueDate:date,status:z.enum(['ACTIVE','COMPLETED','CANCELLED']).default('ACTIVE')}).strict();
export const courseSchema=z.object({title:text,description:note,trainer:text,date,capacity:z.number().int().min(1).max(10000).default(20),status:z.enum(['SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED']).default('SCHEDULED')}).strict();
export const assetSchema=z.object({name:text,assetTag:text,category:text,employeeId:optionalId,status:z.enum(['AVAILABLE','ASSIGNED','REPAIR','RETIRED']).default('AVAILABLE'),purchaseDate:date.nullable().optional(),value:money.default(0)}).strict().refine(v=>(v.status==='ASSIGNED')===!!v.employeeId,'Assigned assets require an employee; clear assignment before changing status');
export const expenseSchema=z.object({employeeId:id,title:text,category:text,amount:money.min(1),date,notes:note}).strict();
export const travelSchema=z.object({employeeId:id,destination:text,purpose:text,startDate:date,endDate:date,budget:money}).strict().refine(v=>v.endDate>=v.startDate,'End date must follow start date');
export const exitSchema=z.object({employeeId:id,lastWorkingDate:date,reason:text}).strict();
export const productivitySchema=z.object({pattern:text,category:z.enum(['PRODUCTIVE','NEUTRAL','NON_PRODUCTIVE'])}).strict();
export const leadSchema=z.object({company:text,contactName:text,email,phone:z.string().max(30).default(''),stage:z.enum(['LEAD','CONTACTED','DEMO','QUOTATION','NEGOTIATION','WON','LOST']).default('LEAD'),value:money.default(0),nextFollowup:z.iso.datetime().transform(v=>new Date(v)).nullable().optional(),notes:note}).strict();
export const planSchema=z.object({name:z.enum(['STARTER','GROWTH','ENTERPRISE']),monthlyPrice:money,employeeLimit:z.number().int().min(1),deviceLimit:z.number().int().min(0),features:z.array(text).max(50)}).strict();
export const salaryRuleSchema=z.object({name:text,kind:z.enum(['DEDUCTION']),percent:z.number().min(0).max(100),cap:money.nullable().optional(),active:z.boolean().default(true)}).strict();
export const supportSchema=z.object({subject:text,message:note,category:z.enum(['TECHNICAL','LOGIN','BILLING','ATTENDANCE','PAYROLL','LEAVE','GENERAL']).default('GENERAL'),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL')}).strict();
export const configs:Record<string,{model:string;resource:string;schema:z.ZodType;employeeScoped?:boolean;references?:Record<string,string>;readOnly?:boolean}>={
  branches:{model:'branch',resource:'organization',schema:branchSchema},departments:{model:'department',resource:'organization',schema:orgSchema},designations:{model:'designation',resource:'organization',schema:orgSchema},teams:{model:'team',resource:'organization',schema:orgSchema},locations:{model:'location',resource:'organization',schema:orgSchema},'cost-centers':{model:'costCenter',resource:'organization',schema:orgSchema},
  shifts:{model:'shift',resource:'shifts',schema:shiftSchema},devices:{model:'attendanceDevice',resource:'devices',schema:deviceSchema,references:{branchId:'branch'}},'leave-types':{model:'leaveType',resource:'leave',schema:leaveTypeSchema},calendar:{model:'calendarEvent',resource:'calendar',schema:eventSchema},jobs:{model:'job',resource:'recruitment',schema:jobSchema,references:{departmentId:'department'}},candidates:{model:'candidate',resource:'recruitment',schema:candidateSchema,references:{jobId:'job'}},goals:{model:'goal',resource:'performance',schema:goalSchema,employeeScoped:true},courses:{model:'course',resource:'training',schema:courseSchema},assets:{model:'asset',resource:'assets',schema:assetSchema,employeeScoped:true},expenses:{model:'expenseClaim',resource:'expenses',schema:expenseSchema,employeeScoped:true},travel:{model:'travelRequest',resource:'travel',schema:travelSchema,employeeScoped:true},exit:{model:'employeeExit',resource:'exit',schema:exitSchema,employeeScoped:true},'productivity-rules':{model:'productivityRule',resource:'workforce',schema:productivitySchema},'salary-rules':{model:'salaryRule',resource:'payroll',schema:salaryRuleSchema},support:{model:'supportTicket',resource:'support',schema:supportSchema}
};
