import {test,expect} from '@playwright/test';

test('employee face setup fits narrow phones and opens camera only on tap with permission recovery',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.addInitScript(()=>{
  localStorage.setItem('tcw_cookie_consent_v1','essential');
  const w=window as any;w.cameraCalls=0;w.cameraDenied=true;
  Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>{w.cameraCalls++;if(w.cameraDenied)throw new DOMException('Permission denied','NotAllowedError');const canvas=document.createElement('canvas');canvas.width=640;canvas.height=640;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#c8dae5';ctx.fillRect(0,0,640,640);const stream=canvas.captureStream(5);w.cameraTrack=stream.getVideoTracks()[0];w.cameraCanvas=canvas;const timer=setInterval(()=>ctx.fillRect(0,0,640,640),50),stop=w.cameraTrack.stop.bind(w.cameraTrack);w.cameraTrack.stop=()=>{clearInterval(timer);stop()};return stream;}}});
 });
 let faceWrites=0;page.on('request',r=>{if(r.method()==='POST'&&/\/attendance\/face-(profile|scan|challenge)$/.test(new URL(r.url()).pathname))faceWrites++;});
 await page.route('**/api/attendance/face-profile',r=>r.fulfill({json:{enrolled:false,status:'LEGACY',attendanceReady:false}}));
 await page.goto('/login');await page.locator('input[name=companyCode]').fill(process.env.DEMO_COMPANY_CODE!);await page.locator('input[name=username]').fill('phone-employee@example.test');await page.locator('input[name=password]').fill(process.env.E2E_EMPLOYEE_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();
 const gate=page.locator('.employee-face-onboarding');await expect(gate.getByRole('heading',{name:'Add your face',exact:true})).toBeVisible();await expect(gate.getByText('Your camera is off',{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).cameraCalls)).toBe(0);await expect(page.locator('.tcw-ios-notice')).not.toBeVisible();
 for(const width of [390,320]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const card=await gate.locator('.face-enrollment-card').boundingBox();expect(card!.x).toBeGreaterThanOrEqual(0);expect(card!.x+card!.width).toBeLessThanOrEqual(width);await gate.getByRole('button',{name:'Open camera',exact:true}).scrollIntoViewIfNeeded();const button=await gate.getByRole('button',{name:'Open camera',exact:true}).boundingBox();expect(button!.x+button!.width).toBeLessThanOrEqual(width);await page.screenshot({path:`test-results/people-face-idle-${width}.png`,fullPage:true,animations:'disabled'});}
 await gate.getByRole('button',{name:'Open camera',exact:true}).click();await expect(gate.getByRole('alert')).toContainText('Camera access is blocked');expect(await page.evaluate(()=>(window as any).cameraCalls)).toBe(1);await expect(gate.getByRole('heading',{name:'Allow camera access'})).toBeVisible();await expect(gate).not.toContainText('The request is not allowed by the user agent');expect(faceWrites).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/people-face-permission-mobile.png',fullPage:true,animations:'disabled'});
 await page.evaluate(()=>{(window as any).cameraDenied=false});await gate.getByRole('button',{name:'Open camera',exact:true}).click();expect(await page.evaluate(()=>(window as any).cameraCalls)).toBe(2);await expect(gate.locator('.face-camera')).toHaveClass(/ (ready|preview)$/);if(await gate.getByRole('button',{name:'Start preview',exact:true}).count())await gate.getByRole('button',{name:'Start preview',exact:true}).click();await expect(gate.getByRole('button',{name:'Capture straight',exact:true})).toBeEnabled();await expect(gate.getByRole('alert')).toHaveCount(0);await expect(gate.locator('video')).toHaveAttribute('playsinline','');await expect.poll(()=>page.evaluate(()=>document.querySelector('video')!.videoWidth)).toBeGreaterThan(0);expect(faceWrites).toBe(0);await page.screenshot({path:'test-results/people-face-ready-mobile.png',fullPage:true,animations:'disabled'});
 await gate.getByRole('button',{name:'Sign out',exact:true}).click();await expect(gate).toHaveCount(0);expect(await page.evaluate(()=>(window as any).cameraTrack.readyState)).toBe('ended');
});
