CREATE TABLE field_work_policies (tenant_id uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE, enabled boolean NOT NULL DEFAULT false, interval_seconds integer NOT NULL DEFAULT 30 CHECK(interval_seconds BETWEEN 15 AND 300), max_accuracy_meters integer NOT NULL DEFAULT 100 CHECK(max_accuracy_meters BETWEEN 20 AND 500), max_session_hours integer NOT NULL DEFAULT 10 CHECK(max_session_hours BETWEEN 1 AND 12), employee_ids text[] NOT NULL DEFAULT '{}', updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE field_work_sessions (id uuid PRIMARY KEY, attendance_in_id uuid NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, employee_id uuid NOT NULL, started_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at timestamp(3) NOT NULL, ended_at timestamp(3), end_reason text, consent_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(tenant_id,id), FOREIGN KEY(tenant_id,employee_id) REFERENCES employees(tenant_id,id) ON DELETE CASCADE);
CREATE INDEX field_session_employee_idx ON field_work_sessions(tenant_id,employee_id,started_at);
CREATE UNIQUE INDEX field_one_open_session ON field_work_sessions(tenant_id,employee_id) WHERE ended_at IS NULL;
CREATE TABLE field_location_points (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, session_id uuid NOT NULL, employee_id uuid NOT NULL, latitude double precision NOT NULL CHECK(latitude BETWEEN -90 AND 90), longitude double precision NOT NULL CHECK(longitude BETWEEN -180 AND 180), accuracy double precision NOT NULL CHECK(accuracy > 0), captured_at timestamp(3) NOT NULL, received_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(session_id,captured_at), FOREIGN KEY(tenant_id,session_id) REFERENCES field_work_sessions(tenant_id,id) ON DELETE CASCADE, FOREIGN KEY(tenant_id,employee_id) REFERENCES employees(tenant_id,id) ON DELETE CASCADE);
CREATE INDEX field_location_employee_idx ON field_location_points(tenant_id,employee_id,received_at);
CREATE TABLE field_visits (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, employee_id uuid NOT NULL, title text NOT NULL, customer text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', outcome text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'PLANNED', scheduled_at timestamp(3), latitude double precision, longitude double precision, radius_meters integer NOT NULL DEFAULT 200, session_id uuid, started_at timestamp(3), completed_at timestamp(3), check_in jsonb, check_out jsonb, created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(tenant_id,employee_id) REFERENCES employees(tenant_id,id) ON DELETE CASCADE, FOREIGN KEY(tenant_id,session_id) REFERENCES field_work_sessions(tenant_id,id) ON DELETE CASCADE);
CREATE INDEX field_visit_employee_idx ON field_visits(tenant_id,employee_id,created_at);
CREATE UNIQUE INDEX field_one_active_visit ON field_visits(tenant_id,employee_id) WHERE status='ACTIVE';
