import {BadRequestException,ServiceUnavailableException} from '@nestjs/common';
import sharp from 'sharp';
import path from 'node:path';
// Use the Node WASM build: bundled browser descriptors are never identity evidence.
let engine:Promise<any>|undefined,pending=0;let tail=Promise.resolve();
async function getEngine(){if(!engine)engine=(async()=>{const api=require('@vladmandic/face-api/dist/face-api.node-wasm.js');await api.tf.setBackend('wasm');await api.tf.ready();const models=path.join(path.dirname(require.resolve('@vladmandic/face-api/package.json')),'model');await Promise.all([api.nets.tinyFaceDetector.loadFromDisk(models),api.nets.faceLandmark68TinyNet.loadFromDisk(models),api.nets.faceRecognitionNet.loadFromDisk(models)]);return api;})().catch(()=>{engine=undefined;throw new ServiceUnavailableException('Server face verification is unavailable. No attendance was recorded.');});return engine;}
export function cameraBytes(frame:string){const match=frame.match(/^data:image\/(jpeg|png);base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new BadRequestException('Capture a valid camera image.');const bytes=Buffer.from(match[2],'base64');if(bytes.length<5000||bytes.length>500000)throw new BadRequestException('Camera image must be between 5 KB and 500 KB.');return bytes;}
export async function analyzeFace(frame:string){
 if(pending>=4)throw new ServiceUnavailableException('Face verification is busy. Retry in a few seconds.');pending++;const previous=tail;let release!:()=>void;tail=new Promise<void>(r=>{release=r});await previous;
 try{
  const api=await getEngine(),bytes=cameraBytes(frame);let raw:any;try{raw=await sharp(bytes,{limitInputPixels:4000000}).rotate().resize(640,640,{fit:'inside',withoutEnlargement:true}).removeAlpha().toColourspace('srgb').raw().toBuffer({resolveWithObject:true});}catch{throw new BadRequestException('Camera image could not be decoded.');}
  const tensor=api.tf.tensor3d(new Uint8Array(raw.data),[raw.info.height,raw.info.width,3]);
  try{const faces=await api.detectAllFaces(tensor,new api.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.55})).withFaceLandmarks(true).withFaceDescriptors();if(faces.length!==1)throw new BadRequestException(faces.length?'More than one face detected. Only the employee should be in the camera.':'No face detected. Use normal lighting and keep your face visible.');const f=faces[0],box=f.detection.box;if(f.detection.score<.65||box.width*box.height/(raw.info.width*raw.info.height)<.06)throw new BadRequestException('Face is not clear enough. Move closer and use normal light.');const pts=f.landmarks.positions,left=pts.slice(36,42).reduce((n:number,p:any)=>n+p.x,0)/6,right=pts.slice(42,48).reduce((n:number,p:any)=>n+p.x,0)/6,width=right-left;if(width<12)throw new BadRequestException('Face landmarks are unclear.');const yaw=(pts[30].x-(left+right)/2)/width;return {descriptor:Array.from(f.descriptor as Float32Array),yaw,hash:require('node:crypto').createHash('sha256').update(bytes).digest('hex') as string};}finally{tensor.dispose();}
 }finally{pending--;release();}
}
export function validateHeadMovement(faces:{yaw:number;hash:string}[],turn:string){if(faces.length!==3)throw new BadRequestException('Capture all three challenge frames.');const [front,turned,returned]=faces;if(new Set(faces.map(f=>f.hash)).size!==3||Math.abs(front.yaw-returned.yaw)>.16||Math.abs(front.yaw)>.32||Math.abs(returned.yaw)>.32||(turn==='LEFT'?turned.yaw-front.yaw:front.yaw-turned.yaw)<.14)throw new BadRequestException('Head movement was not verified. Look straight, turn as instructed, then look straight again. No attendance was recorded.');}
