import {BadRequestException,ConflictException,ForbiddenException,NotFoundException} from '@nestjs/common';
import {createHash,createPublicKey,randomBytes,randomUUID,verify} from 'node:crypto';
import {z} from 'zod';
import type {Database} from '../../../packages/database';
import {assertEmployee,audit,Context,requirePermission,tenant} from './context';
const keySchema=z.string().min(80).max(400).regex(/^[A-Za-z0-9+/]+={0,2}$/);
export const biometricProofSchema=z.object({challengeId:z.string().uuid(),signature:z.string().min(80).max(200).regex(/^[A-Za-z0-9+/]+={0,2}$/)}).strict();
function own(ctx:Context){if(ctx.user.role.code!=='EMPLOYEE'||!ctx.user.employeeId)throw new ForbiddenException('Use your linked Employee account for phone biometrics.');return ctx.user.employeeId;}
export function biometricPublicKey(value:string){const der=Buffer.from(keySchema.parse(value),'base64');let key;try{key=createPublicKey({key:der,type:'spki',format:'der'});}catch{throw new BadRequestException('Invalid phone public key.');}if(key.asymmetricKeyType!=='ec'||key.asymmetricKeyDetails?.namedCurve!=='prime256v1')throw new BadRequestException('Phone key must use P-256.');return {key,publicKey:key.export({type:'spki',format:'der'}).toString('base64'),keyHash:createHash('sha256').update(key.export({type:'spki',format:'der'})).digest('hex')};}
async function liveAccount(db:Database,ctx:Context){const employeeId=own(ctx);await assertEmployee(db,ctx,employeeId);if(!await db.session.findFirst({where:{id:ctx.session.id,userId:ctx.user.id,expiresAt:{gt:new Date()}}}))throw new ForbiddenException('Sign in again before phone verification.');return employeeId;}
export async function phoneBiometricStatus(db:Database,ctx:Context){const employeeId=await liveAccount(db,ctx),tid=tenant(ctx);return {accountKey:`${tid}:${employeeId}`,items:await db.employeeBiometricDevice.findMany({where:{tenantId:tid,employeeId,status:{in:['PENDING','APPROVED']}},select:{id:true,keyHash:true,label:true,status:true,createdAt:true},orderBy:{createdAt:'desc'}})};}
export async function createBiometricChallenge(db:Database,ctx:Context,body:unknown){const employeeId=await liveAccount(db,ctx),tid=tenant(ctx),input=z.object({purpose:z.enum(['REGISTER','PUNCH']),intent:z.enum(['IN','OUT']),deviceId:z.string().uuid().optional()}).strict().parse(body);
 if(input.purpose==='PUNCH'&&(!input.deviceId||!await db.employeeBiometricDevice.findFirst({where:{id:input.deviceId,tenantId:tid,employeeId,status:'APPROVED'}})))throw new ForbiddenException('This phone needs HR approval before biometric attendance.');
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM employees WHERE tenant_id=${tid}::uuid AND id=${employeeId}::uuid FOR UPDATE`;
 if(await tx.biometricChallenge.count({where:{tenantId:tid,employeeId,createdAt:{gt:new Date(Date.now()-60000)}}})>=5)throw new ConflictException('Too many phone verification attempts. Wait one minute.');
 await tx.biometricChallenge.deleteMany({where:{tenantId:tid,employeeId,createdAt:{lt:new Date(Date.now()-86400000)}}});
 const id=randomUUID(),payload=['TCW_PHONE_V1',tid,employeeId,ctx.user.id,ctx.session.id,id,input.purpose,input.intent,input.deviceId??'',randomBytes(32).toString('base64url')].join('|'),expiresAt=new Date(Date.now()+120000);
 await tx.biometricChallenge.create({data:{id,tenantId:tid,employeeId,userId:ctx.user.id,sessionId:ctx.session.id,deviceId:input.purpose==='PUNCH'?input.deviceId:null,purpose:input.purpose,intent:input.intent,payload,expiresAt}});
 return {challengeId:id,payload,expiresAt,accountKey:`${tid}:${employeeId}`};});
}
async function takeChallenge(db:Database,ctx:Context,id:string,purpose:string,intent:string){const employeeId=await liveAccount(db,ctx),tid=tenant(ctx),where={id,tenantId:tid,employeeId,userId:ctx.user.id,sessionId:ctx.session.id,purpose,intent,usedAt:null,expiresAt:{gt:new Date()}};
 const challenge=await db.biometricChallenge.findFirst({where});if(!challenge)throw new ForbiddenException('Phone verification expired or already used. Retry.');
 if((await db.biometricChallenge.updateMany({where,data:{usedAt:new Date()}})).count!==1)throw new ForbiddenException('Phone verification already used.');return challenge;
}
function proof(payload:string,signature:string,key:string){try{if(verify('sha256',Buffer.from(payload,'utf8'),biometricPublicKey(key).key,Buffer.from(signature,'base64')))return;}catch{}throw new ForbiddenException('Phone signature did not verify. No attendance was recorded.');}
export async function registerBiometricDevice(db:Database,ctx:Context,body:unknown){const input=biometricProofSchema.extend({publicKey:keySchema,label:z.string().trim().min(1).max(80),intent:z.enum(['IN','OUT'])}).parse(body),challenge=await takeChallenge(db,ctx,input.challengeId,'REGISTER',input.intent),key=biometricPublicKey(input.publicKey);proof(challenge.payload,input.signature,key.publicKey);
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM employees WHERE tenant_id=${challenge.tenantId}::uuid AND id=${challenge.employeeId}::uuid FOR UPDATE`;
 await liveAccount(tx as any,ctx);
 const where={tenantId:challenge.tenantId,employeeId:challenge.employeeId};const prior=await tx.employeeBiometricDevice.findFirst({where:{...where,keyHash:key.keyHash}});if(prior?.status==='APPROVED'||prior?.status==='PENDING')return {id:prior.id,status:prior.status};
 if(await tx.employeeBiometricDevice.count({where:{...where,status:{in:['PENDING','APPROVED']}}})>=3)throw new ConflictException('Ask HR to remove an old phone before adding another.');
 const device=await tx.employeeBiometricDevice.upsert({where:{tenantId_employeeId_keyHash:{...where,keyHash:key.keyHash}},create:{...where,publicKey:key.publicKey,keyHash:key.keyHash,label:input.label},update:{status:'PENDING',label:input.label,approvedBy:null,approvedAt:null}});
 await audit(tx,ctx,'PHONE_BIOMETRIC_PENDING','employees',challenge.employeeId,undefined,{deviceId:device.id,keyHash:key.keyHash});return {id:device.id,status:device.status};});
}
export async function verifyBiometricPunch(db:Database,ctx:Context,body:unknown,intent:'IN'|'OUT') {const input=biometricProofSchema.parse(body),challenge=await takeChallenge(db,ctx,input.challengeId,'PUNCH',intent),device=await db.employeeBiometricDevice.findFirst({where:{id:challenge.deviceId??'',tenantId:challenge.tenantId,employeeId:challenge.employeeId,status:'APPROVED'}});if(!device)throw new ForbiddenException('Phone approval was removed.');proof(challenge.payload,input.signature,device.publicKey);
 return {enrolled:true,matched:true,profileId:null,profileUpdatedAt:null,deviceId:device.id,deviceUpdatedAt:device.updatedAt,captureHash:createHash('sha256').update(challenge.payload).digest('hex'),distance:0,threshold:0};
}
export async function reviewBiometricDevices(db:Database,ctx:Context,method:string,body:unknown){const tid=tenant(ctx);requirePermission(ctx,'employees','MANAGE');if(!['COMPANY_OWNER','HR_ADMIN'].includes(ctx.user.role.code))throw new ForbiddenException('Company HR administrators approve phones.');
 if(method==='GET'){const rows=await db.employeeBiometricDevice.findMany({where:{tenantId:tid,status:{in:['PENDING','APPROVED']}},orderBy:{createdAt:'desc'},take:100,select:{id:true,employeeId:true,label:true,keyHash:true,status:true,createdAt:true,updatedAt:true}});const items=[];for(const row of rows){const employee=await db.employee.findFirst({where:{tenantId:tid,id:row.employeeId,deletedAt:null},select:{employeeCode:true,firstName:true,lastName:true}});if(employee)items.push({...row,employee});}return {items};}
 if(method!=='POST')throw new BadRequestException('Unsupported phone review operation.');
 const input=z.object({deviceId:z.string().uuid(),decision:z.enum(['APPROVE','REVOKE']),expectedUpdatedAt:z.string().datetime(),identityConfirmed:z.literal(true)}).strict().parse(body);
 return db.$transaction(async tx=>{const row=await tx.employeeBiometricDevice.findFirst({where:{id:input.deviceId,tenantId:tid}});if(!row)throw new NotFoundException('Phone not found.');await tx.$queryRaw`SELECT id FROM employees WHERE tenant_id=${tid}::uuid AND id=${row.employeeId}::uuid FOR UPDATE`;
 if(input.decision==='APPROVE')await assertEmployee(tx as any,ctx,row.employeeId);
 const updated=await tx.employeeBiometricDevice.updateMany({where:{id:row.id,tenantId:tid,updatedAt:new Date(input.expectedUpdatedAt),status:input.decision==='APPROVE'?'PENDING':{in:['PENDING','APPROVED']}},data:{status:input.decision==='APPROVE'?'APPROVED':'REVOKED',approvedBy:ctx.user.id,approvedAt:new Date()}});if(updated.count!==1)throw new ConflictException('Phone approval changed. Refresh.');await audit(tx,ctx,'PHONE_BIOMETRIC_'+input.decision,'employees',row.employeeId,undefined,{deviceId:row.id,keyHash:row.keyHash,identityConfirmed:true});return {ok:true};});
}
