'use client';
import React,{useEffect,useMemo,useState} from 'react';
import {Activity,ChevronRight,Cloud,Filter,KeyRound,MapPin,Monitor,MoreVertical,Plus,RefreshCw,Search,Server,Settings2,Signal,Smartphone,Trash2,Users,Wifi,WifiOff} from 'lucide-react';
import {Confirm,Empty,Failure,Loading,Modal,displayDate,useApp,useData} from './core';
import {Row,readable} from './config';
import {AttendanceMachineCatalogModal,DeviceLogModal,DeviceMappingModal,DeviceNativeSetupModal,DevicePunchModal} from './device-tools';
import './device-design.css';

type DeviceDraft={name:string;vendor:string;model:string;serialNumber:string;connectionMode:string;host:string;port:number;branchId:string;timezone:string};
const vendors=['TCW_MOBILE','BIOMAX','ZKTECO','ESSL','MATRIX','REALTIME','MANTRA','HIKVISION','CPPLUS','DAHUA','SUPREMA','ANVIZ','SPECTRA','VIRDI','GENERIC'];
const modes=['EMPLOYEE_APP','NATIVE_PUSH','CLOUD_PUSH','LAN_PULL','WIFI_LAN','MIDDLEWARE'];
const timezones=['Asia/Kolkata','UTC','Asia/Dubai','Asia/Singapore','Europe/London','America/New_York'];
const emptyDraft=():DeviceDraft=>({name:'',vendor:'BIOMAX',model:'SpeedFace 5SE Lite',serialNumber:'',connectionMode:'NATIVE_PUSH',host:'',port:4370,branchId:'',timezone:'Asia/Kolkata'});
const toDraft=(row:Row):DeviceDraft=>({name:String(row.name??''),vendor:String(row.vendor??'GENERIC'),model:String(row.model??''),serialNumber:String(row.serialNumber??''),connectionMode:String(row.connectionMode??'NATIVE_PUSH'),host:String(row.host??''),port:Number(row.port??5005),branchId:String(row.branchId??''),timezone:String(row.timezone??'Asia/Kolkata')});
const payload=(draft:DeviceDraft)=>{const mobile=draft.vendor==='TCW_MOBILE'||draft.connectionMode==='EMPLOYEE_APP';return {name:draft.name.trim(),vendor:mobile?'TCW_MOBILE':draft.vendor,model:mobile?'TCW Employee Face Scan':draft.model.trim(),serialNumber:mobile?'TCW-EMPLOYEE-APP':draft.serialNumber.trim(),connectionMode:mobile?'EMPLOYEE_APP':draft.connectionMode,host:mobile?'':draft.host.trim(),port:mobile?443:Number(draft.port||5005),branchId:draft.branchId||null,timezone:draft.timezone}};
const isOnline=(row:Row)=>['ONLINE','ACTIVE','READY'].includes(String(row.status??'').toUpperCase());
const isInactive=(row:Row)=>['INACTIVE','DISABLED'].includes(String(row.status??'').toUpperCase());
const deviceKind=(row:Row|DeviceDraft)=>String(row.connectionMode)==='EMPLOYEE_APP'||String(row.vendor)==='TCW_MOBILE'?'Mobile App':'Biometric Device';
const modeLabel=(value:any)=>readable(String(value??'').toLowerCase());
const vendorLabel=(value:any)=>String(value)==='TCW_MOBILE'?'TCW Mobile':readable(String(value??'').toLowerCase());

function DeviceIcon({row,large=false}:{row:Row|DeviceDraft;large?:boolean}){const mobile=String(row.connectionMode)==='EMPLOYEE_APP'||String(row.vendor)==='TCW_MOBILE';return <span className={'device-v3-icon '+(large?'large ':'')+(mobile?'mobile':'')}>{mobile?<Smartphone/>:<Monitor/>}</span>}
function StatusChip({row}:{row:Row}){if(isOnline(row))return <span className="device-v3-status online"><i/>Online</span>;if(isInactive(row))return <span className="device-v3-status inactive"><i/>Inactive</span>;return <span className="device-v3-status offline"><i/>{String(row.status??'OFFLINE')==='AWAITING_CONNECTION'?'Awaiting':'Offline'}</span>}
function DeviceField({label,children,required=false,className=''}:{label:string;children:React.ReactNode;required?:boolean;className?:string}){return <label className={'device-v3-field '+className}><span>{label}{required&&<b aria-hidden="true">*</b>}</span>{React.isValidElement(children)?React.cloneElement(children as React.ReactElement<any>,{'aria-label':label,'aria-required':required||undefined}):children}</label>}

export function DeviceManagement(){
 const {can,mutate,notify}=useApp();
 const query=useData('devices?pageSize=500',true,10000);
 const branches=useData('branches?pageSize=500',can('organization'));
 const rows:Row[]=query.data?.items??[],branchRows:Row[]=branches.data?.items??[];
 const canCreate=can('devices','CREATE'),canEdit=can('devices','EDIT'),canDelete=can('devices','DELETE'),canManage=can('devices','MANAGE');
 const [selectedId,setSelectedId]=useState(''),[creating,setCreating]=useState(false),[draft,setDraft]=useState<DeviceDraft>(emptyDraft()),[search,setSearch]=useState(''),[filter,setFilter]=useState<'ALL'|'ONLINE'|'OFFLINE'|'INACTIVE'>('ALL'),[saving,setSaving]=useState(false);
 const [baseDraft,setBaseDraft]=useState<DeviceDraft>(emptyDraft()),[actionBusy,setActionBusy]=useState(''),[typeFilter,setTypeFilter]=useState(''),[branchFilter,setBranchFilter]=useState(''),[page,setPage]=useState(1),[switchTo,setSwitchTo]=useState<Row|'ADD'|null>(null),[rotateTarget,setRotateTarget]=useState<Row|null>(null);
 const dirty=JSON.stringify(draft)!==JSON.stringify(baseDraft);
 const [remove,setRemove]=useState<Row|null>(null),[catalog,setCatalog]=useState(false),[catalogSearch,setCatalogSearch]=useState('');
 const [nativeSetup,setNativeSetup]=useState<Row|null>(null),[punches,setPunches]=useState<Row|null>(null),[mapping,setMapping]=useState<Row|null>(null),[logs,setLogs]=useState<Row|null>(null),[gateway,setGateway]=useState<Row|null>(null);
 useEffect(()=>{if(creating)return;if(selectedId&&rows.some(row=>String(row.id)===selectedId))return;if(rows.length){setSelectedId(String(rows[0].id));setDraft(toDraft(rows[0]));setBaseDraft(toDraft(rows[0]))}},[rows,selectedId,creating]);
 const selected=creating?null:rows.find(row=>String(row.id)===selectedId)??null;
 useEffect(()=>{if(selected&&!creating&&!dirty){setDraft(toDraft(selected));setBaseDraft(toDraft(selected))}},[selectedId,selected?.updatedAt,creating]);
 const branchName=(id:any)=>branchRows.find(row=>String(row.id)===String(id))?.name??'Unassigned';
 const online=rows.filter(isOnline).length,inactive=rows.filter(isInactive).length,offline=rows.length-online-inactive;
 const filtered=useMemo(()=>rows.filter(row=>{const needle=search.trim().toLowerCase();if(needle&&!String([row.name,row.vendor,row.model,row.serialNumber,row.host,branchName(row.branchId)].join(' ')).toLowerCase().includes(needle))return false;if(typeFilter&&deviceKind(row)!==typeFilter)return false;if(branchFilter&&String(row.branchId??'')!==branchFilter)return false;if(filter==='ONLINE')return isOnline(row);if(filter==='INACTIVE')return isInactive(row);if(filter==='OFFLINE')return !isOnline(row)&&!isInactive(row);return true}),[rows,search,filter,branchRows,typeFilter,branchFilter]);
 const update=(patch:Partial<DeviceDraft>)=>setDraft(current=>({...current,...patch}));
 const mobile=draft.vendor==='TCW_MOBILE'||draft.connectionMode==='EMPLOYEE_APP';
 function applyOpen(row:Row){setCreating(false);setSelectedId(String(row.id));setDraft(toDraft(row));setBaseDraft(toDraft(row))}
 function open(row:Row){if(dirty)setSwitchTo(row);else applyOpen(row)}
 function applyAdd(){setCreating(true);setSelectedId('');setDraft(emptyDraft());setBaseDraft(emptyDraft())}
 function add(){if(dirty)setSwitchTo('ADD');else applyAdd()}
 async function save(){if(!draft.name.trim()||(!draft.serialNumber.trim()&&!mobile)||!(selected?canEdit:canCreate))return;if(!mobile&&['LAN_PULL','WIFI_LAN'].includes(draft.connectionMode)&&!draft.host.trim()){notify('Enter a device host for LAN / Wi-Fi mode.',true);return;}setSaving(true);try{const result=await mutate('devices'+(selected?'/'+selected.id:''),selected?'PATCH':'POST',{...payload(draft),...(selected?{expectedSettings:payload(baseDraft)}:{})});setBaseDraft(toDraft(result));setDraft(toDraft(result));if(!selected&&result?.id){setCreating(false);setSelectedId(String(result.id));setDraft(toDraft(result));if(result.connectionMode==='NATIVE_PUSH')setNativeSetup({...result,fallbackKey:result.pushSecret});else if(result?.pushSecret)setGateway(result)}}catch{}finally{setSaving(false)}}
 async function test(row:Row){setActionBusy('test');try{const result=await mutate('devices/'+row.id+'/test','POST',{});notify(result?.message??'Connection test completed.')}catch(e:any){notify(e?.message??'Connection test failed.',true)}finally{setActionBusy('')}}
 async function rotate(row:Row){setActionBusy('rotate');try{const result=await mutate('devices/'+row.id+'/rotate-secret','POST',{});setGateway({...result.device,...result});setRotateTarget(null)}catch{}finally{setActionBusy('')}}
 const choosePreset=(preset:Row)=>{setCatalog(false);setCreating(true);setSelectedId('');const next={...emptyDraft(),name:String(preset.name??''),vendor:String(preset.vendor??'GENERIC'),model:String(preset.model??''),serialNumber:String(preset.serialNumber??''),connectionMode:String(preset.connectionMode??'NATIVE_PUSH'),host:String(preset.host??''),port:Number(preset.port??5005),timezone:String(preset.timezone??'Asia/Kolkata'),branchId:''};setDraft(next);setBaseDraft(next)};

 if(query.isLoading)return <Loading/>;
 if(query.error)return <Failure error={query.error} retry={()=>query.refetch()}/>;

 return <div className="device-v3 device-workspace">
  <header className="device-v3-head"><div><span className="device-v3-eyebrow"><Signal size={15}/> CONNECTED WORKFORCE</span><h1>Every punch. Connected.</h1><p>Manage your attendance devices, employee face app and connection activity.</p></div><div className="device-v3-head-actions">{canCreate&&<button className="btn secondary" onClick={()=>setCatalog(true)}><Monitor size={17}/>Attendance Sources</button>}{canCreate&&<button className="btn primary" onClick={add}><Plus size={17}/>Add Device</button>}</div></header>
  <div className="dw-stats">{[[Monitor,'Attendance sources',rows.length,'Registered devices and apps'],[Wifi,'Online / ready',online,'Sources currently marked available'],[WifiOff,'Needs attention',offline,'Offline or awaiting connection'],[Smartphone,'Employee face app',rows.filter(r=>deviceKind(r)==='Mobile App').length,'Mobile attendance sources']].map(([Icon,label,value,note]:any)=><article key={label}><span><Icon size={21}/></span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>)}</div>
  <div className="device-v3-layout">
   <aside className="device-v3-list-panel">
    <div className="device-v3-list-head"><div><h2>All Devices</h2><span>{rows.length}</span></div><button className="icon-button" aria-label="Refresh devices" title="Refresh devices" onClick={()=>query.refetch()}><RefreshCw size={17}/></button></div>
    <div className="device-v3-tabs"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>All <span>{rows.length}</span></button><button className={filter==='ONLINE'?'active':''} onClick={()=>setFilter('ONLINE')}><i className="online"/>Online <span>{online}</span></button><button className={filter==='OFFLINE'?'active':''} onClick={()=>setFilter('OFFLINE')}><i className="offline"/>Offline <span>{offline}</span></button><button className={filter==='INACTIVE'?'active':''} onClick={()=>setFilter('INACTIVE')}><i className="inactive"/>Inactive <span>{inactive}</span></button></div>
    <label className="device-v3-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search devices" placeholder="Search name, serial or host"/><Filter size={16}/></label>
    <div className="dw-filters"><select aria-label="Device source type" value={typeFilter} onChange={e=>{setTypeFilter(e.target.value);setPage(1)}}><option value="">All source types</option><option>Biometric Device</option><option>Mobile App</option></select><select aria-label="Device branch" value={branchFilter} onChange={e=>{setBranchFilter(e.target.value);setPage(1)}}><option value="">All branches</option>{branchRows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>
    <div className="device-v3-list">{!filtered.length?<Empty title="No matching devices" description={rows.length?'Change the search or device status filter.':'Add your first attendance source.'}/>:filtered.slice((Math.min(page,Math.max(1,Math.ceil(filtered.length/15)))-1)*15,Math.min(page,Math.max(1,Math.ceil(filtered.length/15)))*15).map(row=><button key={row.id} type="button" className={'device-v3-list-item '+(selected?.id===row.id?'active':'')} onClick={()=>open(row)}><DeviceIcon row={row}/><span className="device-v3-list-copy"><span><strong>{row.name}</strong><StatusChip row={row}/></span><small>{vendorLabel(row.vendor)} {row.model?'· '+row.model:''}</small><em><MapPin size={13}/>{branchName(row.branchId)}{row.host?' · '+row.host:''}</em></span><ChevronRight size={18}/></button>)}</div>
    <div className="dt-pager"><span>{filtered.length} matching · latest {rows.length} loaded</span><div><button className="icon-button" aria-label="Previous devices" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><button className="icon-button" aria-label="Next devices" disabled={page>=Math.ceil(filtered.length/15)} onClick={()=>setPage(p=>p+1)}>›</button></div></div>
   </aside>
   <main className="device-v3-editor">
    <div className="device-v3-editor-head"><div><h2>{creating?'Add Device':selected?'Device details':'Register your first source'}</h2><p>{creating?'Register a new attendance source.':'Update device information and connection settings.'}</p></div>{selected?<StatusChip row={selected}/>:<span className="device-v3-status inactive"><i/>New</span>}</div>
    <div className="device-v3-editor-body">{dirty&&<div className="dt-note">Unsaved changes · live status refresh keeps your edits.</div>}{selected?.lastError&&<div className="dt-note warning"><strong>Connection needs attention</strong><p>{selected.lastError}</p></div>}
     <section className="device-v3-identity"><DeviceIcon row={draft} large/><div><strong>{draft.name||'New Attendance Device'}</strong><span>{deviceKind(draft)}</span><small>{vendorLabel(draft.vendor)} {draft.model?'· '+draft.model:''}</small></div>{selected&&<div className="device-v3-live-meta"><span><Signal size={15}/>Last seen <strong>{selected.lastSeenAt?displayDate(selected.lastSeenAt):'Never'}</strong></span><span><RefreshCw size={15}/>Last sync <strong>{selected.lastSync?displayDate(selected.lastSync):'Never'}</strong></span></div>}</section>
     <section className="device-v3-section">
      <div className="device-v3-section-title"><div><h3>Device Information</h3><p>Core identity and attendance source details.</p></div><Monitor size={19}/></div>
      <div className="device-v3-grid two">
       <DeviceField label="Device Name" required><input disabled={!creating&&!canEdit} value={draft.name} onChange={e=>update({name:e.target.value})} placeholder="Main Office Device"/></DeviceField>
       <DeviceField label="Source / Brand" required><select disabled={!creating&&!canEdit} value={draft.vendor} onChange={e=>{const vendor=e.target.value;update({vendor,connectionMode:vendor==='TCW_MOBILE'?'EMPLOYEE_APP':draft.connectionMode==='EMPLOYEE_APP'?'NATIVE_PUSH':draft.connectionMode,port:vendor==='TCW_MOBILE'?443:draft.port===443?4370:draft.port})}}>{vendors.map(v=><option key={v} value={v}>{vendorLabel(v)}</option>)}</select></DeviceField>
       <DeviceField label="Model / App"><input value={mobile?'TCW Employee Face Scan':draft.model} disabled={mobile||(!creating&&!canEdit)} onChange={e=>update({model:e.target.value})} placeholder="SpeedFace 5SE Lite"/></DeviceField>
       <DeviceField label="Serial / Source ID" required><input value={mobile?'TCW-EMPLOYEE-APP':draft.serialNumber} disabled={mobile||(!creating&&!canEdit)} onChange={e=>update({serialNumber:e.target.value})} placeholder="Device serial number"/></DeviceField>
       <DeviceField label="Branch / Location"><select disabled={!creating&&!canEdit} value={draft.branchId} onChange={e=>update({branchId:e.target.value})}><option value="">Unassigned</option>{branchRows.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></DeviceField>
       <DeviceField label="Timezone" required><select disabled={!creating&&!canEdit} value={draft.timezone} onChange={e=>update({timezone:e.target.value})}>{!timezones.includes(draft.timezone)&&<option value={draft.timezone}>{draft.timezone}</option>}{timezones.map(v=><option key={v} value={v}>{v}</option>)}</select></DeviceField>
      </div>
     </section>
     <section className="device-v3-section">
      <div className="device-v3-section-title"><div><h3>Connection Settings</h3><p>Configure how TCW HR receives attendance punches.</p></div><Server size={19}/></div>
      <div className="device-v3-grid three"><DeviceField label="Communication Mode" required className="span-3"><select value={mobile?'EMPLOYEE_APP':draft.connectionMode} disabled={mobile||(!creating&&!canEdit)} onChange={e=>update({connectionMode:e.target.value,...(e.target.value==='EMPLOYEE_APP'?{vendor:'TCW_MOBILE',port:443}:{})})}>{modes.map(v=><option key={v} value={v}>{modeLabel(v)}</option>)}</select></DeviceField>{!mobile&&<><DeviceField label="LAN IP / Host" className="span-2"><input disabled={!creating&&!canEdit} value={draft.host} onChange={e=>update({host:e.target.value})} placeholder="192.168.1.201"/></DeviceField><DeviceField label="Port" required><input disabled={!creating&&!canEdit} type="number" min={1} max={65535} value={draft.port} onChange={e=>update({port:Number(e.target.value)})}/></DeviceField></>}</div>
      {selected&&canManage&&<div className="device-v3-connection-actions"><button className="btn secondary" disabled={!!actionBusy} onClick={()=>test(selected)}>{mobile?<Smartphone size={17}/>:<Wifi size={17}/>} {mobile?'Check App Status':'Test Connection'}</button>{!mobile&&<button className="btn secondary" onClick={()=>setNativeSetup(selected)}><Settings2 size={17}/>Device Setup</button>}</div>}
     </section>
     <section className="device-v3-section">
      <div className="device-v3-section-title"><div><h3>Attendance & Sync</h3><p>Live operational information from this attendance source.</p></div><Activity size={19}/></div>
      <div className="device-v3-info-grid"><article><span className="blue"><Activity/></span><div><small>Punch Capture</small><strong>IN & OUT attendance</strong><em>Processed by TCW attendance engine</em></div></article><article><span className={selected&&isOnline(selected)?'green':'slate'}>{selected&&isOnline(selected)?<Wifi/>:<WifiOff/>}</span><div><small>Connection State</small><strong>{selected?readable(String(selected.status??'unknown').toLowerCase()):'Not connected yet'}</strong><em>{selected?.lastSeenAt?'Last seen '+displayDate(selected.lastSeenAt):'No live heartbeat yet'}</em></div></article><article><span className="violet"><Cloud/></span><div><small>Integration</small><strong>{modeLabel(draft.connectionMode)}</strong><em>{mobile?'Signed-in Employee Face Scan':'Device to server attendance sync'}</em></div></article></div>
      {selected&&<div className="device-v3-tools"><button onClick={()=>setPunches(selected)}><Activity size={17}/><span><strong>{mobile?'Face Scan Punches':'Live Punches'}</strong><small>View recent attendance events</small></span><ChevronRight size={17}/></button>{!mobile&&<button onClick={()=>setMapping(selected)}><Users size={17}/><span><strong>Map Employees</strong><small>Link device users to employees</small></span><ChevronRight size={17}/></button>}<button onClick={()=>setLogs(selected)}><Server size={17}/><span><strong>{mobile?'Activity Log':'Sync Log'}</strong><small>Review device integration events</small></span><ChevronRight size={17}/></button>{!mobile&&canManage&&<button disabled={!!actionBusy} onClick={()=>setRotateTarget(selected)}><KeyRound size={17}/><span><strong>Gateway Key</strong><small>Rotate middleware secret safely</small></span><ChevronRight size={17}/></button>}</div>}
     </section>
    </div>
    <footer className="device-v3-footer"><div>{selected&&canDelete&&<button className="btn danger" onClick={()=>setRemove(selected)}><Trash2 size={17}/>Delete Device</button>}</div><div>{(creating||dirty)&&<button className="btn secondary" onClick={()=>{if(selected){setDraft(baseDraft)}else{setCreating(false);if(rows[0])applyOpen(rows[0])}}}>Cancel</button>}{(selected?canEdit:canCreate)&&<button className="btn primary" disabled={saving||(!mobile&&(!Number.isInteger(draft.port)||draft.port<1||draft.port>65535))||!draft.name.trim()||(!mobile&&!draft.serialNumber.trim())} onClick={save}>{saving?'Saving…':!selected?'Create Device':'Update Device'}</button>}</div></footer>
   </main>
  </div>
  {catalog&&<AttendanceMachineCatalogModal search={catalogSearch} setSearch={setCatalogSearch} onClose={()=>setCatalog(false)} onSelect={choosePreset}/>}
  {nativeSetup&&<DeviceNativeSetupModal device={nativeSetup} onClose={()=>setNativeSetup(null)}/>}
  {punches&&<DevicePunchModal device={punches} onClose={()=>setPunches(null)}/>}
  {mapping&&<DeviceMappingModal device={mapping} onClose={()=>setMapping(null)}/>}
  {logs&&<DeviceLogModal device={logs} onClose={()=>setLogs(null)}/>}
  {gateway&&<Modal title="Gateway key" onClose={()=>setGateway(null)} wide><div className="modal-body credential-sheet"><p>This secret is used only for middleware / REST gateway integrations. Save it securely when it is shown.</p><div className="profile-grid"><div><span>Device</span><strong>{gateway.name??gateway.device?.name??selected?.name}</strong></div><div><span>Serial</span><strong>{gateway.serialNumber??gateway.device?.serialNumber??selected?.serialNumber}</strong></div><div className="span-two"><span>Gateway key</span><strong className="mono-secret">{gateway.pushSecret??'Generated key is not available in this response.'}</strong></div></div>{gateway.pushSecret&&<button className="btn primary" onClick={()=>navigator.clipboard.writeText(String(gateway.pushSecret)).then(()=>notify('Gateway key copied.')).catch(()=>notify('Clipboard is unavailable. Select and copy the key.',true))}>Copy gateway key</button>}</div></Modal>}
  {switchTo&&<Confirm title="Discard unsaved changes?" description="Your device edits have not been saved." onClose={()=>setSwitchTo(null)} onConfirm={async()=>{if(switchTo==='ADD')applyAdd();else applyOpen(switchTo);setSwitchTo(null)}}/>}
  {rotateTarget&&<Confirm title="Rotate gateway key?" description="The old key will stop working. Update your middleware integration with the new key after rotation." onClose={()=>setRotateTarget(null)} onConfirm={async()=>rotate(rotateTarget)}/>}
  {remove&&<Confirm title="Delete device?" description="This removes an unused attendance source and its configuration. Devices with recorded punches cannot be deleted because attendance history must be retained." onClose={()=>setRemove(null)} onConfirm={async()=>{await mutate('devices/'+remove.id,'DELETE');setRemove(null);setCreating(false);setSelectedId('')}}/>}
 </div>
}
