'use client';
import React,{useEffect,useRef,useState} from 'react';
import './face.css';
import {Camera,Check,LogOut,RotateCcw,ShieldCheck,UserCheck} from 'lucide-react';
import {api,Modal,TCW_PRODUCT_LOGO,useApp,useData,Loading,Failure,Empty} from './core';

export function preloadFaceEngine(){}
async function startCamera(video:HTMLVideoElement){
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is not supported on this device/browser.');
  video.muted=true;video.defaultMuted=true;video.playsInline=true;
  video.setAttribute('playsinline','');video.setAttribute('webkit-playsinline','');
  const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:640},height:{ideal:640}}});
  try{video.srcObject=stream;await video.play();return stream;}catch(error){stream.getTracks().forEach(track=>track.stop());throw error;}
}
function stopStream(stream:MediaStream|null){stream?.getTracks().forEach(track=>track.stop());}
function captureFrame(video:HTMLVideoElement){
  const canvas=document.createElement('canvas'),size=420;canvas.width=size;canvas.height=size;
  const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Camera frame could not be prepared.');
  const sw=video.videoWidth,sh=video.videoHeight;if(!sw||!sh)throw new Error('Camera is not ready yet.');
  const side=Math.min(sw,sh),sx=(sw-side)/2,sy=(sh-side)/2;
  ctx.drawImage(video,sx,sy,side,side,0,0,size,size);
  const pixels=ctx.getImageData(0,0,size,size).data;let mean=0,samples=0;
  for(let i=0;i<pixels.length;i+=32){mean+=(pixels[i]+pixels[i+1]+pixels[i+2])/3;samples++;}
  mean/=Math.max(1,samples);
  if(mean<30)throw new Error('Image is too dark. Move to better light and try again.');
  return canvas.toDataURL('image/jpeg',0.68);
}
function CompanyMark({src,name}:{src?:string|null;name?:string}){
  return <img src={src||TCW_PRODUCT_LOGO} alt={(name||'Company')+' logo'} className="face-company-logo" onError={e=>{(e.currentTarget as HTMLImageElement).src=TCW_PRODUCT_LOGO}}/>;
}
function CameraStage({videoRef,state,message}:{videoRef:React.RefObject<HTMLVideoElement|null>;state:string;message:string}){
  return <div className={'face-camera '+state}><video ref={videoRef} autoPlay muted playsInline aria-label="Live front camera preview"/>{['idle','error'].includes(state)?<div className="face-camera-placeholder"><Camera size={32}/><strong>{state==='idle'?'Your camera is off':'Camera preview unavailable'}</strong><span>{state==='idle'?'Tap Open camera and allow camera access.':'Follow the instructions below, then try again.'}</span></div>:<><div className="face-scan-shade"/><div className="face-scan-guide"><span/><i/><i/><i/><i/></div></>}{['starting','capturing','saving','success'].includes(state)&&<div className={'face-scan-overlay '+(state==='success'?'success':'')}>{state==='success'?<span><Check size={30}/></span>:<span className="auth-spinner"/>}<strong>{message}</strong></div>}</div>;
}
function cameraFailure(error:any){
 const name=error?.name;
 if(name==='NotAllowedError'||name==='PermissionDeniedError'||name==='SecurityError')return {title:'Camera access is blocked',message:'Your browser or phone did not allow camera access. No face was captured. Allow Camera for this website, then tap Open camera.',help:true};
 if(name==='NotFoundError'||name==='DevicesNotFoundError')return {title:'No camera is available',message:'Open this website on a phone or computer with a camera, then tap Open camera.',help:true};
 if(name==='NotReadableError'||name==='TrackStartError')return {title:'Camera is busy or unavailable',message:'Close other apps using the camera and check this browser’s camera permission, then try again.',help:true};
 return {title:'Camera could not start',message:'Open this website directly in Safari or Chrome, check camera permission and try again.',help:true};
}
function CaptureFlow({purpose,onComplete,onClose,logo,companyName,intent}:{purpose:'ENROLL'|'PUNCH';onComplete:(result?:any)=>void|Promise<any>;onClose:()=>void;logo?:string|null;companyName?:string;intent?:'IN'|'OUT'}){
 const{session}=useApp();const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),busyRef=useRef(false),generation=useRef(0),mounted=useRef(true);
 const[state,setState]=useState('idle'),[message,setMessage]=useState('Open your front camera to begin.'),[frames,setFrames]=useState<string[]>([]),[challenge,setChallenge]=useState<any>(null),[error,setError]=useState(''),[cameraError,setCameraError]=useState<ReturnType<typeof cameraFailure>|null>(null);
 const start=async()=>{if(busyRef.current)return;busyRef.current=true;const epoch=++generation.current;stopStream(streamRef.current);streamRef.current=null;setError('');setCameraError(null);setFrames([]);setChallenge(null);setState('starting');setMessage('Opening camera…');try{if(!videoRef.current)throw new Error('Camera view is unavailable.');const stream=await startCamera(videoRef.current);if(!mounted.current||epoch!==generation.current){stopStream(stream);return;}streamRef.current=stream;setState('ready');setMessage('Look straight at the camera.');}catch(e:any){if(mounted.current&&epoch===generation.current){const failure=cameraFailure(e);setState('error');setCameraError(failure);setError(failure.message);}}finally{busyRef.current=false}};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;stopStream(streamRef.current)}},[]);
 const capture=async()=>{if(state!=='ready'||busyRef.current||!videoRef.current)return;busyRef.current=true;setError('');try{let token=challenge;if(!token){token=await api('attendance/face-challenge','POST',{purpose},session.csrf);setChallenge(token);}const frame=captureFrame(videoRef.current),next=[...frames,frame];setFrames(next);if(next.length<3){setMessage(next.length===1?`Turn your face slightly to your ${token.turn==='LEFT'?'left':'right'}.`:'Look straight at the camera again.');return;}setState('saving');setMessage('Server is verifying your face…');const result=await api(purpose==='ENROLL'?'attendance/face-profile':'attendance/face-scan','POST',{challengeId:token.challengeId,frames:next,...(purpose==='PUNCH'?{clientNonce:crypto.randomUUID(),...(intent?{intent}:{})}:{})},session.csrf);if(!mounted.current)return;stopStream(streamRef.current);streamRef.current=null;setState('success');setMessage(purpose==='ENROLL'?'Face setup sent to HR for approval':result.punchType==='IN'?'Checked in — working timer started':'Checked out — work session closed');await onComplete(result);if(purpose==='PUNCH')window.setTimeout(()=>{if(mounted.current)onClose()},650);}catch(e:any){stopStream(streamRef.current);streamRef.current=null;setCameraError(null);setState('error');setFrames([]);setChallenge(null);setError(e.message??'Face verification failed. No attendance was recorded.');}finally{busyRef.current=false}};
 return <div className="face-scan-modal">{purpose==='ENROLL'&&<><div className="face-enrollment-brand"><CompanyMark src={logo} name={companyName}/><div><strong>{companyName??'TCW Employee'}</strong><small>Employee identity setup</small></div></div><h2>Add your face</h2><p>Capture straight, turn as instructed, then look straight again. HR must confirm that the captured face belongs to you before attendance is enabled.</p></>}<CameraStage videoRef={videoRef} state={state} message={message}/><div className="face-enrollment-progress">{[0,1,2].map(i=><span key={i} className={frames.length>i?'done':''}/>)}</div><div className="face-scan-status" role={error?'alert':'status'}><UserCheck size={20}/><div><strong>{cameraError?cameraError.title:error?'Face verification needs attention':state==='idle'?'Ready to set up your camera':state==='success'?message:`Capture ${Math.min(frames.length+1,3)} of 3`}</strong><p>{error||message}</p></div></div>{cameraError?.help&&<aside className="face-camera-help"><h3>Allow camera access</h3><ol><li>Allow Camera for this website in your browser’s site settings.</li><li>On iPhone, open this website directly in Safari if you are using an in-app browser. Check Camera permission in Safari’s website settings.</li><li>If access is still blocked, check your phone’s camera privacy restrictions or ask your device administrator. Return here and tap Open camera.</li></ol></aside>}<div className="face-scan-privacy"><ShieldCheck size={16}/><p>{purpose==='ENROLL'?'Your encrypted face template is linked to your employee account. One encrypted review image is kept until HR approves or rejects setup, then deleted.':'Camera images are checked on the server against your HR-approved template. A mismatch, multiple faces or failed movement challenge cannot create a punch.'}</p></div><div className="face-scan-actions"><button className="btn secondary" onClick={onClose}>{purpose==='ENROLL'?<><LogOut size={16}/>Sign out</>:'Cancel'}</button>{state==='idle'||state==='error'?<button className="btn primary" onClick={start}>{state==='idle'||cameraError?<Camera size={16}/>:<RotateCcw size={16}/>}Open camera</button>:state==='success'?<button className="btn primary" onClick={onClose}>Done</button>:<button className="btn primary" disabled={state!=='ready'} onClick={capture}><Camera size={16}/>{state==='saving'?'Verifying…':frames.length===0?'Capture straight':frames.length===1?'Capture turn':'Capture straight again'}</button>}</div></div>;
}
export function EmployeeFaceEnrollmentGate({onComplete,onSignOut,logo,companyName}:{onComplete:()=>void|Promise<any>;onSignOut:()=>void|Promise<any>;logo?:string|null;companyName?:string}){return <div className="mandatory-overlay employee-face-onboarding"><div className="mandatory-card face-enrollment-card"><CaptureFlow purpose="ENROLL" onComplete={onComplete} onClose={()=>void onSignOut()} logo={logo} companyName={companyName}/></div></div>;}
export function FaceScanAttendanceModal({onClose,onComplete,intent}:{onClose:()=>void;onComplete?:(result?:any)=>void|Promise<any>;intent?:'IN'|'OUT'}){return <Modal title="Verify your face" onClose={onClose}><CaptureFlow purpose="PUNCH" intent={intent} onClose={onClose} onComplete={async result=>{await onComplete?.(result)}}/></Modal>;}
export function FaceApprovalPanel(){
 const{session}=useApp(),q=useData('attendance/face-review'),[confirmed,setConfirmed]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function review(row:any,decision:string){setBusy(true);setError('');try{await api('attendance/face-review','POST',{profileId:row.id,decision,expectedUpdatedAt:row.updatedAt,identityConfirmed:true},session.csrf);await q.refetch();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="field-face-panel"><div className="panel"><h2>Approve employee face identities</h2><p>Check the employee’s identity in person or through your company’s identity process. Employee self-setup cannot approve itself. Existing face setups need a fresh server capture and approval.</p>{error&&<p className="form-error">{error}</p>}</div>{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<div className="field-face-reviews">{q.data.items.map((r:any)=><article className="panel" key={r.id}><strong>{r.employee.firstName} {r.employee.lastName} · {r.employee.employeeCode}</strong>{r.preview&&<img src={r.preview} alt="Captured face awaiting HR identity review"/>}{r.employee.photo&&<><small>Employee directory photo</small><img src={r.employee.photo} alt="Employee directory reference"/></>}<label className="field-consent"><input type="checkbox" checked={!!confirmed[r.id]} onChange={e=>setConfirmed({...confirmed,[r.id]:e.target.checked})}/>I checked whether this face belongs to this employee.</label><div className="field-actions"><button className="btn primary" disabled={busy||!confirmed[r.id]} onClick={()=>review(r,'APPROVE')}>Approve identity</button><button className="btn secondary" disabled={busy||!confirmed[r.id]} onClick={()=>review(r,'REJECT')}>Reject setup</button></div></article>)}</div>:<Empty title="No face setups awaiting approval" description="Employees capture their face from the Employee app. Approved face reset is available in People → Employee app access."/>}</section>;
}
