'use client';
import React,{useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {MapPin,Navigation,ShieldCheck,Square,Play,CheckCircle2,RefreshCw,Settings2,Route,Plus} from 'lucide-react';
import {api,useApp,useData,Loading,Failure,Empty,Avatar,Badge} from './core';
import {Row} from './config';
import './field-work.css';
import {FaceApprovalPanel} from './face';
export function freshLocation():Promise<any>{return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('GPS is not available on this device.'));return;}navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:new Date(p.timestamp).toISOString()}),e=>reject(new Error(e.code===1?'Location permission is denied. Enable it in your browser or app settings.':e.code===3?'GPS timed out. Move outside and retry.':'GPS is unavailable. Move outside and retry.')),{enableHighAccuracy:true,maximumAge:0,timeout:15000});});}
function pointLabel(p:Row){return `${Number(p.latitude).toFixed(5)}, ${Number(p.longitude).toFixed(5)}`;}
function MapLink({point}:{point:Row}){return <a className="btn secondary small" href={`https://www.openstreetmap.org/?mlat=${point.latitude}&mlon=${point.longitude}#map=17/${point.latitude}/${point.longitude}`} target="_blank" rel="noopener noreferrer"><MapPin size={14}/>Open map</a>;}
// Mounted in the shell, so changing employee pages does not lose the GPS watcher.
export function EmployeeFieldTracker(){
 const{session}=useApp(),q=useData('field-work/session',session.user.role==='EMPLOYEE'),[error,setError]=useState(''),[visible,setVisible]=useState(true),[lastSent,setLastSent]=useState('');const busy=useRef(false),last=useRef(0);const s=q.data?.session,interval=Number(q.data?.policy?.intervalSeconds??30);
 useEffect(()=>{if(session.user.role!=='EMPLOYEE')return;const timer=window.setInterval(()=>q.refetch().catch(()=>{}),15000);const changed=()=>{q.refetch().catch(()=>{});last.current=0};window.addEventListener('tcw-field-session',changed);return()=>{clearInterval(timer);window.removeEventListener('tcw-field-session',changed)}},[q.refetch,session.user.role]);
 useEffect(()=>{const changed=()=>setVisible(document.visibilityState==='visible');changed();document.addEventListener('visibilitychange',changed);return()=>document.removeEventListener('visibilitychange',changed)},[]);
 useEffect(()=>{
  if(!s?.id||!visible||!navigator.geolocation)return;let active=true,pending:GeolocationPosition|null=null;
  const send=async()=>{if(!active||busy.current||!pending||Date.now()-last.current<interval*1000)return;busy.current=true;const p=pending;pending=null;try{await api('field-work/point','POST',{sessionId:s.id,point:{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:new Date(p.timestamp).toISOString()}},session.csrf);if(active){setError('');setLastSent(new Date().toLocaleTimeString());last.current=Date.now();}}catch(e:any){if(active)setError(e.message);}finally{busy.current=false;}};
  const watch=navigator.geolocation.watchPosition(p=>{pending=p;void send()},e=>{setError(e.code===1?'Location permission denied. Tracking paused.':'GPS unavailable. Last location may be delayed.');},{enableHighAccuracy:true,maximumAge:0,timeout:15000});const timer=window.setInterval(()=>{if(!pending)navigator.geolocation.getCurrentPosition(p=>{pending=p;void send()},()=>{}, {enableHighAccuracy:true,maximumAge:0,timeout:15000});else void send()},interval*1000);
  return()=>{active=false;navigator.geolocation.clearWatch(watch);clearInterval(timer)};
 },[s?.id,visible,interval,session.csrf]);
 if(!s)return null;
 return <div className={'field-sharing-banner '+(error?'warning':'')} role="status"><Navigation size={17}/><span><strong>{error?'Location needs attention':visible?'Field location sharing is on':'Location updates paused while app is hidden'}</strong><small>{error||`HR can see your work location. ${lastSent?'Last sent '+lastSent+'. ':''}Stops on checkout or when you stop sharing.`}</small></span><Link href="/field-work">Manage</Link><button aria-label="Stop sharing location" onClick={async()=>{await api('field-work/session','DELETE',{},session.csrf);window.dispatchEvent(new Event('tcw-field-session'));await q.refetch();}}>Stop</button></div>;
}
function RoutePreview({points,timezone}:{points:Row[];timezone:string}){
 if(!points.length)return <Empty title="No location points" description="Choose an employee and a company date with a shared field session."/>;
 const lats=points.map(p=>p.latitude),lons=points.map(p=>p.longitude),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),x=(p:Row)=>30+(p.longitude-minLon)/Math.max(.0001,maxLon-minLon)*640,y=(p:Row)=>210-(p.latitude-minLat)/Math.max(.0001,maxLat-minLat)*180;
 return <div className="field-route-preview"><svg viewBox="0 0 700 240" role="img" aria-label="Route overview from shared GPS points"><path d={points.map((p,i)=>`${i?'L':'M'}${x(p)} ${y(p)}`).join(' ')} fill="none" stroke="#0284c7" strokeWidth="3"/>{[points[0],points.at(-1)!].map((p,i)=><g key={i}><circle cx={x(p)} cy={y(p)} r="7" fill={i?'#059669':'#0369a1'}/><text x={x(p)+10} y={y(p)-9} fontSize="12">{i?'Latest':'Start'}</text></g>)}</svg><p>Route overview · {points.length} shared GPS points · latitude / longitude · gaps may indicate paused or unavailable GPS.</p><div className="field-coordinate-list">{points.filter((_,i)=>i%Math.max(1,Math.ceil(points.length/25))===0||i===points.length-1).map(p=><div key={p.id}><time>{new Date(p.receivedAt).toLocaleTimeString('en-GB',{timeZone:timezone})} {timezone}</time><span>{pointLabel(p)} · ±{Math.round(p.accuracy)} m</span><MapLink point={p}/></div>)}</div></div>;
}
export function FieldWorkPage(){
 const{session,can}=useApp(),self=session.user.role==='EMPLOYEE',q=useData('field-work'),sq=useData('field-work/session',self),vq=useData('field-work/visits'),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[selected,setSelected]=useState(self?String(session.user.employeeId??''):''),[date,setDate]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:session.company?.timezone||'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[search,setSearch]=useState(''),[title,setTitle]=useState(''),[customer,setCustomer]=useState(''),[outcomes,setOutcomes]=useState<Record<string,string>>({}),[visitPlan,setVisitPlan]=useState({scheduledAt:'',latitude:'',longitude:'',radiusMeters:'200',notes:''});
 const hq=useData('field-work/history?employeeId='+selected+'&date='+date,!!selected&&tab==='history'),policy=q.data?.policy,rows:Row[]=q.data?.items??[],visits:Row[]=vq.data?.items??[];
 useEffect(()=>{const poll=setInterval(()=>q.refetch().catch(()=>{}),15000);return()=>clearInterval(poll)},[q.refetch]);
 async function run(action:()=>Promise<any>){setBusy(true);setError('');try{await action();await Promise.all([q.refetch(),vq.refetch(),self?sq.refetch():Promise.resolve()]);window.dispatchEvent(new Event('tcw-field-session'));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="field-work-page"><header className="field-hero"><div><span><Navigation size={16}/>FIELD WORKSPACE</span><h1>{self?'Your work, wherever you go':'Your team in the field'}</h1><p>{self?'Share your work location, manage customer visits and record what you completed.':'See location freshness, plan visits and tailor field work for your company.'}</p></div><div className="field-hero-note"><ShieldCheck size={22}/><strong>Visible sharing controls</strong><small>On-duty tracking · 30-day history</small></div></header>
 <div className="tabs field-tabs">{['overview','visits','history',...(!self&&can('company','EDIT')?['settings','face-review']:[])].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t==='overview'?'Live locations':t==='visits'?'Visits':t==='history'?'Route history':t==='face-review'?'Face approvals':'Company settings'}</button>)}</div>
 {!q.isLoading&&!q.error&&!policy?.enabled&&<div className="field-policy-notice"><ShieldCheck size={20}/><span>Field work is disabled for this company. {self?'Ask HR to enable it for your account.':'Enable sharing and choose employees in Company settings to begin.'}</span>{!self&&can('company','EDIT')&&<button type="button" className="btn secondary small" onClick={()=>setTab('settings')}>Configure field work</button>}</div>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 {tab==='settings'?<FieldSettings onSaved={()=>q.refetch()}/>:tab==='face-review'?<FaceReview/>:tab==='overview'?<>
 {self&&<section className="panel field-session-card"><div><span className="field-kicker">MY FIELD SESSION</span><h2>{sq.data?.session?'Location sharing is on':'Start your field day'}</h2><p>Check in to attendance first. Keep this app open for reliable updates; screen-off/background tracking is not supported in this version.</p></div>{sq.data?.session?<button className="btn secondary" disabled={busy} onClick={()=>run(()=>api('field-work/session','DELETE',{},session.csrf))}><Square size={16}/>Stop sharing</button>:<div><label className="field-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to share my location with my company during this field session.</label><button className="btn primary" disabled={busy||!consent||!sq.data?.eligible} onClick={()=>run(async()=>api('field-work/session','POST',{consent:true,point:await freshLocation()},session.csrf))}><Play size={16}/>{busy?'Getting GPS…':'Start field work'}</button>{!sq.data?.eligible&&<small>HR must enable field work for your account.</small>}</div>}</section>}
 <div className="field-stats">{[['Live now',rows.filter(r=>r.state==='LIVE').length],['Update delayed',rows.filter(r=>r.state==='STALE').length],['Sharing stopped',rows.filter(r=>r.state==='STOPPED').length],['Active visits',visits.filter(v=>v.status==='ACTIVE').length]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
 <section className="panel"><div className="toolbar"><input aria-label="Search field employees" placeholder="Search employee or code" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn secondary small" onClick={()=>q.refetch()}><RefreshCw size={15}/>Refresh</button></div>{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:<>{!rows.length&&<Empty title="No field employees" description="Enable field work and assign employees in Company settings."/>}{!!rows.length&&!rows.some(r=>[r.firstName,r.lastName,r.employeeCode].join(" ").toLowerCase().includes(search.toLowerCase()))&&<Empty title="No matching employees" description="Try another name or employee code."/>}<div className="field-person-grid">{rows.filter(r=>[r.firstName,r.lastName,r.employeeCode].join(' ').toLowerCase().includes(search.toLowerCase())).map(r=><article className="field-person-card" key={r.id}><div className="person-cell"><Avatar name={r.firstName+' '+r.lastName}/><div><strong>{r.firstName} {r.lastName}</strong><small>{r.employeeCode}</small></div><span className={'field-state '+r.state.toLowerCase()}>{r.state==='STALE'?'Delayed':r.state==='LIVE'?'Live':'Stopped'}</span></div>{r.point?<><p><MapPin size={15}/>{pointLabel(r.point)}</p><small>GPS ±{Math.round(r.point.accuracy)} m · received {new Date(r.point.receivedAt).toLocaleTimeString()}</small><MapLink point={r.point}/></>:<p>No active shared location</p>}<button className="btn secondary small" onClick={()=>{setSelected(r.id);setTab('history')}}><Route size={15}/>Route history</button></article>)}</div></>}<p className="field-footnote">Locations are device-reported GPS, not verified proof of presence. A delayed update is never labelled live. Showing up to 500 employees.</p></section></>:tab==='history'?<section className="panel"><div className="toolbar"><select aria-label="Route employee" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select employee</option>{rows.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName} · {r.employeeCode}</option>)}</select><label>Company date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{hq.isLoading&&selected?<Loading/>:hq.error?<Failure error={hq.error}/>:<RoutePreview points={hq.data?.items??[]} timezone={hq.data?.timezone??session.company?.timezone??'Asia/Kolkata'}/>} {hq.data?.truncated&&<p>Showing the first 1,000 points for this date.</p>}</section>:<>
 <section className="panel field-visit-form"><h2>{self?'Plan a customer visit':'Assign a customer visit'}</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('field-work/visits','POST',{title,customer,notes:visitPlan.notes,...(!self?{employeeId:selected}:{}),...(visitPlan.scheduledAt?{scheduledAt:new Date(visitPlan.scheduledAt).toISOString()}:{}),...(visitPlan.latitude!==''&&visitPlan.longitude!==''?{latitude:Number(visitPlan.latitude),longitude:Number(visitPlan.longitude),radiusMeters:Number(visitPlan.radiusMeters)}:{})},session.csrf);setTitle('');setCustomer('');})}}>{!self&&<label>Employee<select aria-label="Employee" required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select employee</option>{rows.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName}</option>)}</select></label>}<label>Visit purpose<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Site inspection, customer meeting…"/></label><label>Customer / site<input maxLength={120} value={customer} onChange={e=>setCustomer(e.target.value)}/></label><label>Scheduled visit time<input type="datetime-local" value={visitPlan.scheduledAt} onChange={e=>setVisitPlan({...visitPlan,scheduledAt:e.target.value})}/></label><label>Site latitude (optional)<input type="number" step="any" min={-90} max={90} value={visitPlan.latitude} required={!!visitPlan.longitude} onChange={e=>setVisitPlan({...visitPlan,latitude:e.target.value})}/></label><label>Site longitude (optional)<input type="number" step="any" min={-180} max={180} value={visitPlan.longitude} required={!!visitPlan.latitude} onChange={e=>setVisitPlan({...visitPlan,longitude:e.target.value})}/></label><label>Check-in radius (metres)<input type="number" min={50} max={1000} value={visitPlan.radiusMeters} onChange={e=>setVisitPlan({...visitPlan,radiusMeters:e.target.value})}/></label><label>Visit instructions<textarea maxLength={1000} value={visitPlan.notes} onChange={e=>setVisitPlan({...visitPlan,notes:e.target.value})}/></label><button className="btn primary" disabled={busy||!policy?.enabled||!can('workforce','CREATE')}><Plus size={16}/>Plan visit</button></form></section>
 <div className="field-visits">{vq.isLoading?<Loading/>:vq.error?<Failure error={vq.error}/>:visits.length?visits.map(v=><article className="panel field-visit-card" key={v.id}><div><span className="field-kicker">{rows.find(r=>r.id===v.employeeId)?.employeeCode??'FIELD VISIT'}</span><h3>{v.title}</h3><p>{v.customer||'No customer added'}</p></div><Badge value={v.status}/>{v.notes&&<p>{v.notes}</p>}{v.latitude!==null&&v.longitude!==null&&<small>Site radius {v.radiusMeters} m · GPS accuracy must fit inside the boundary.</small>}{v.scheduledAt&&<small>Scheduled {new Date(v.scheduledAt).toLocaleString()}</small>}{v.startedAt&&<small>Started {new Date(v.startedAt).toLocaleString()}</small>}{v.checkIn&&<div className="field-visit-proof"><span>Check-in · {pointLabel(v.checkIn)} · ±{Math.round(v.checkIn.accuracy)} m</span><MapLink point={v.checkIn}/></div>}{v.outcome&&<p className="field-outcome">{v.outcome}</p>}{self&&v.status==='PLANNED'&&<div className="field-actions"><button className="btn primary" disabled={busy||!sq.data?.session} onClick={()=>run(async()=>api('field-work/'+v.id+'/start','POST',{point:await freshLocation()},session.csrf))}><MapPin size={16}/>Check in to visit</button><button className="btn secondary" disabled={busy} onClick={()=>run(()=>api('field-work/'+v.id+'/cancel','POST',{},session.csrf))}>Cancel</button></div>}{self&&v.status==='ACTIVE'&&<div><label>Visit outcome<textarea maxLength={1000} value={outcomes[v.id]??''} onChange={e=>setOutcomes({...outcomes,[v.id]:e.target.value})} placeholder="Work completed and follow-up required"/></label><button className="btn primary" disabled={busy||!outcomes[v.id]?.trim()} onClick={()=>run(async()=>api('field-work/'+v.id+'/complete','POST',{point:await freshLocation(),outcome:outcomes[v.id]},session.csrf))}><CheckCircle2 size={16}/>Complete visit</button></div>}</article>):<Empty title="No visits planned" description="Add your first customer visit above."/>}</div></>}
 </div>;
}
function FieldSettings({onSaved}:{onSaved:()=>Promise<any>}){
 const{session}=useApp(),q=useData('field-work/settings'),employees=useData('employees?pageSize=500'),[form,setForm]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{if(q.data?.policy)setForm({...q.data.policy})},[q.data]);
 if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;if(!form)return null;
 return <section className="panel field-settings"><span className="field-kicker"><Settings2 size={15}/>COMPANY CUSTOMISATION</span><h2>Field work settings</h2><p>Employees explicitly start a session while checked in. Sharing ends on checkout, stop or expiry. Location and visit history are retained for 30 days.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSaved(false);try{await api('field-work/settings','PUT',{enabled:form.enabled,intervalSeconds:Number(form.intervalSeconds),maxAccuracyMeters:Number(form.maxAccuracyMeters),maxSessionHours:Number(form.maxSessionHours),employeeIds:form.employeeIds},session.csrf);await q.refetch();await onSaved();setSaved(true);}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label className="field-consent"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enable field work for this company</label><div className="field-setting-grid">{[['intervalSeconds','Location update interval (seconds)',15,300],['maxAccuracyMeters','Maximum GPS uncertainty (metres)',20,500],['maxSessionHours','Session expiry (hours)',1,12]].map(([key,label,min,max])=><label key={String(key)}>{label}<input type="number" required min={Number(min)} max={Number(max)} value={form[String(key)]} onChange={e=>setForm({...form,[String(key)]:e.target.value})}/></label>)}</div><label>Field employees <small>Leave all unchecked to allow all company employees. Selected employees only when any are checked.</small></label><div className="field-employee-picker">{(employees.data?.items??[]).map((e:Row)=><label key={e.id}><input type="checkbox" checked={form.employeeIds.includes(e.id)} onChange={ev=>setForm({...form,employeeIds:ev.target.checked?[...form.employeeIds,e.id]:form.employeeIds.filter((id:string)=>id!==e.id)})}/>{e.firstName} {e.lastName} · {e.employeeCode}</label>)}</div>{error&&<p className="form-error">{error}</p>}{saved&&<p role="status">Company field settings saved.</p>}<button className="btn primary" disabled={busy}>{busy?'Saving…':'Save field settings'}</button></form></section>;
}
function FaceReview(){return <FaceApprovalPanel/>;}

