'use client';
import './hr-operations.css';
import React,{useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Upload,History,ClipboardCheck,GraduationCap,Wallet,ArrowRight,ShieldCheck} from 'lucide-react';
import {Row} from './config';
import {api,useApp,useData,PageTitle,Modal,RecordForm,Table,Loading,Failure,Empty,Badge,Confirm,currencyValue,displayDate} from './core';

export function SalaryWorkspace(){
  const {currency,mutate,session}=useApp();
  const params=useSearchParams(),requestedCode=params.get('employeeCode')??'';
  const [search,setSearch]=useState(requestedCode),[person,setPerson]=useState<Row|null>(null),[revision,setRevision]=useState(false),[loan,setLoan]=useState(false),[cancel,setCancel]=useState<Row|null>(null);
  const people=useData('salary-employees?q='+encodeURIComponent(search)),versions=useData(person?'salary-versions/'+person.id:'',!!person),loans=useData('payroll-loans');
  useEffect(()=>{if(!person&&requestedCode){const match=people.data?.items?.find((p:Row)=>p.employeeCode===requestedCode);if(match)setPerson(match)}},[people.data,requestedCode,person]);
  const employee=versions.data?.employee??person,history:Row[]=versions.data?.items??[],current=history[0];
  const month=new Date().toLocaleDateString('en-CA',{timeZone:session.company?.timezone??'Asia/Kolkata',year:'numeric',month:'2-digit'});
  return <div className="hr-operations">
    <PageTitle title="Salary structures & recovery" subtitle="Effective salary revisions, overtime rates and scheduled loan deductions. Amounts use company currency."/>
    <section className="panel hr-operation-intro"><Wallet size={24}/><div><strong>One salary history per employee</strong><p>Manual payroll amounts still apply to one month. Structures apply from their effective month. Loan schedules record recovery only; they do not send money.</p></div></section>
    <div className="hr-operation-grid">
      <section className="panel hr-operation-picker"><h2>Choose employee</h2><label className="field"><span>Search employee name or code</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search all employees…"/></label>
        {people.isLoading?<Loading/>:people.error?<Failure error={people.error}/>:<div className="hr-employee-options">{people.data?.items?.map((p:Row)=><button key={p.id} className={person?.id===p.id?'active':''} onClick={()=>setPerson(p)}><span><strong>{p.firstName} {p.lastName}</strong><small>{p.employeeCode}</small></span><ArrowRight size={16}/></button>)}</div>}
        <p className="subtle-note">Up to 100 matches. Search by code to find any employee.</p>
      </section>
      <section className="panel hr-salary-detail">{!employee?<Empty title="Select an employee" description="Review salary history, add a revision or schedule loan recovery."/>:<>
        <div className="row-between"><div><small>{employee.employeeCode}</small><h2>{employee.firstName} {employee.lastName}</h2></div><button className="btn primary" onClick={()=>setRevision(true)}>Add salary revision</button></div>
        <div className="hr-salary-facts">{[['Profile salary',employee.monthlySalary],['Latest basic',current?.basic],['Latest HRA',current?.hra],['Latest allowances',current?.allowances],['Monthly fixed gross',current?current.basic+current.hra+current.allowances:null],['Annual fixed gross',current?(current.basic+current.hra+current.allowances)*12:null],['Overtime / hour',current?.overtimeHourly]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value==null?'—':currencyValue(Number(value),currency)}</strong></div>)}</div>
        <p className="subtle-note">The latest revision may start in a future month. Payroll selects the structure effective for the payroll month. Revisions are permanent history entries.</p>
        {versions.isLoading?<Loading/>:versions.error?<Failure error={versions.error}/>:history.length?<Table columns={['effectiveMonth','basic','hra','allowances','overtimeHourly','reason']} rows={history} cell={(r,k)=>['basic','hra','allowances','overtimeHourly'].includes(k)?currencyValue(r[k],currency):undefined}/>:<Empty title="No structured salary yet" description="Existing monthly salary continues until the first effective revision."/>}
      </>}</section>
    </div>
    <section className="panel hr-loan-panel"><div className="row-between"><div><h2>Loan & advance recovery</h2><p>Finalized payroll reduces outstanding balances. Reopening restores the installment for recalculation.</p></div><button className="btn secondary" disabled={!person} onClick={()=>setLoan(true)}>Schedule recovery</button></div>
      {loans.isLoading?<Loading/>:loans.error?<Failure error={loans.error}/>:loans.data?.items?.length?<Table columns={['employeeId','principal','recovered','outstanding','installment','startMonth','status','reason']} rows={loans.data.items} cell={(r,k)=>['principal','recovered','outstanding','installment'].includes(k)?currencyValue(r[k],currency):k==='employeeId'?r.employeeName??r.employeeId:k==='status'?<Badge value={r.status}/>:undefined} actions={r=>r.status==='ACTIVE'?<button className="btn secondary small" onClick={()=>setCancel(r)}>Cancel future recovery</button>:null}/>:<Empty title="No recovery schedules" description="Select an employee to schedule an existing loan or advance."/>}
    </section>
    {revision&&employee&&<Modal title="Add salary revision" onClose={()=>setRevision(false)} wide><div className="modal-body"><p><strong>{employee.firstName} {employee.lastName}</strong> · The selected effective month must have no prepared payroll.</p></div><RecordForm fields={[{key:'effectiveMonth',label:'Effective month (YYYY-MM)',required:true,default:month},{key:'basic',label:'Basic salary',type:'money',required:true,min:0,default:employee.monthlySalary},{key:'hra',label:'HRA',type:'money',required:true,min:0,default:0},{key:'allowances',label:'Other allowances',type:'money',required:true,min:0,default:0},{key:'overtimeHourly',label:'Overtime rate per hour',type:'money',required:true,min:0,default:0},{key:'reason',label:'Reason for salary revision',type:'textarea',required:true}]} onCancel={()=>setRevision(false)} onSave={async values=>{await mutate('salary-versions/'+employee.id,'POST',{...values,expectedUpdatedAt:employee.updatedAt});setRevision(false)}} submit="Save salary revision"/></Modal>}
    {loan&&employee&&<Modal title="Schedule loan recovery" onClose={()=>setLoan(false)}><div className="modal-body"><p>Recovery for <strong>{employee.firstName} {employee.lastName}</strong>. No loan payment is sent from this form.</p></div><RecordForm fields={[{key:'principal',label:'Outstanding principal',type:'money',required:true,min:0.01},{key:'installment',label:'Monthly installment',type:'money',required:true,min:0.01},{key:'startMonth',label:'Start month (YYYY-MM)',required:true,default:month},{key:'reason',label:'Reason / reference',type:'textarea',required:true}]} onCancel={()=>setLoan(false)} onSave={async values=>{await mutate('payroll-loans','POST',{...values,employeeId:employee.id});setLoan(false)}} submit="Schedule recovery"/></Modal>}
    {cancel&&<Confirm title="Cancel future recovery?" description="Only unapplied installments are cancelled. Amounts already included in payroll are retained. This does not record a cash repayment." onClose={()=>setCancel(null)} onConfirm={async()=>{await mutate('payroll-loans/'+cancel.id,'DELETE');setCancel(null)}}/>}
  </div>;
}

export function PayoutReconciliation(){
  const {can,mutate,currency}=useApp(),q=useData('payout-reconciliation'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[recover,setRecover]=useState<Row|null>(null),[providerRef,setProviderRef]=useState('');
  const rows:Row[]=q.data?.items??[],filtered=rows.filter(r=>!status||String(r.status).toUpperCase()===status);
  return <div className="hr-operations"><PageTitle title="Payment reconciliation" subtitle="Review salary transfer references, provider status and UTR across payroll months."/>
    <section className="panel hr-operation-intro"><ShieldCheck size={23}/><div><strong>Verify unresolved transfers before taking another action</strong><p>Status checks read the provider; they do not send money. Transfers without a provider ID require a provider-dashboard check using the reference below. Repeated Pay requests never resend an existing transfer.</p></div></section>
    <section className="panel"><div className="toolbar"><label className="field compact"><span>Transfer status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(rows.map(r=>String(r.status).toUpperCase()))].map(s=><option key={s}>{s}</option>)}</select></label><button className="btn secondary" onClick={()=>q.refetch()}>Refresh records</button>{can('payroll','EXPORT')&&can('reports','EXPORT')&&<a className="btn secondary" href="/api/reports/salary-payments">Export payment register</a>}</div>
      {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:filtered.length?<Table columns={['month','employeeName','employeeCode','amount','status','id','providerRef','reference','utr','error']} rows={filtered} cell={(r,k)=>k==='amount'?currencyValue(r.amount,currency):k==='status'?<Badge value={r.status}/>:undefined} actions={r=>can('payroll','APPROVE')&&r.providerRef?<button className="btn secondary small" disabled={busy} onClick={async()=>{setBusy(true);try{await mutate(`payroll/${r.runId}/payout-sync`,'POST',{})}catch{}finally{setBusy(false)}}}>Check provider status</button>:can('payroll','APPROVE')&&['UNKNOWN','INITIATING'].includes(r.status)?<button className="btn secondary small" onClick={()=>{setRecover(r);setProviderRef('')}}>Recover bank reference</button>:<small>{r.provider==='MANUAL'?'Recorded outside payment':'Verify in provider dashboard'}</small>}/>:<Empty title="No transfers in this view" description="Salary transfers appear here after payout initiation."/>}
    </section>
    {recover&&<Modal title="Recover salary transfer reference" onClose={()=>{if(!busy)setRecover(null)}}><form className="modal-body" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await mutate(`payroll/${recover.runId}/payment-reference`,'POST',{payoutId:recover.id,providerRef,expectedUpdatedAt:recover.updatedAt});setRecover(null);await q.refetch()}catch{}finally{setBusy(false)}}}><p>{recover.employeeName} · {currencyValue(recover.amount,currency)}</p><p className="form-help">Find this exact transfer in the original company’s provider dashboard using reference ID <strong>{recover.id}</strong>. The software verifies its reference, amount and currency with the provider. This only checks a transfer; it sends no money.</p><label className="field"><span>Provider payout ID</span><input required maxLength={120} value={providerRef} onChange={e=>setProviderRef(e.target.value)}/></label><button className="btn primary" disabled={busy}>{busy?'Checking…':'Verify and recover reference'}</button></form></Modal>}
  </div>;
}

export function EmployeeImportModal({onClose}:{onClose:()=>void}){
  const {session,mutate,can,currency}=useApp();const [mode,setMode]=useState(can('employees','CREATE')?'CREATE':'UPDATE'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Row|null>(null),[payload,setPayload]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function check(){if(!file)return;setBusy(true);setError('');setPreview(null);try{if(file.size>2_000_000)throw new Error('Maximum import size is 2 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const body={fileName:file.name,content:btoa(binary),mode};const result=await api('employees/import/preview','POST',body,session.csrf);setPayload(body);setPreview(result)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function save(){if(!payload||!preview)return;setBusy(true);setError('');try{await mutate('employees/import/commit','POST',{...payload,expectedDigest:preview.digest});onClose()}catch(e:any){setError(e.message);setPreview(null)}finally{setBusy(false)}}
  return <Modal title="Import employees" onClose={onClose} wide><div className="modal-body hr-import">
    <div className="hr-operation-intro"><Upload size={23}/><div><strong>Preview before importing</strong><p>CSV or XLSX · 200 employees per batch · 2 MB. Headings and values accept capital or small letters. Use Excel dates, YYYY-MM-DD or DD/MM/YYYY, and company currency amounts. Existing profile and bank details are retained during updates.</p></div></div>
    <div className="hr-import-tools"><a className="btn secondary" href="/api/employees/import-template?format=xlsx">Excel template</a><a className="btn secondary" href="/api/employees/import-template?format=csv">CSV template</a></div>
    <label className="field"><span>Import mode</span><select disabled={busy} value={mode} onChange={e=>{setMode(e.target.value);setPreview(null);setPayload(null)}}>{can('employees','CREATE')&&<option value="CREATE">Create new employees</option>}{can('employees','EDIT')&&<option value="UPDATE">Update existing employee codes</option>}</select></label>
    <label className="field"><span>Employee file</span><input type="file" disabled={busy} accept=".csv,.xlsx" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setPayload(null)}}/></label>
    {error&&<div role="alert" className="notice">{error}</div>}
    {preview&&<><p><strong>{preview.total} employees</strong> · {preview.valid?'Ready to import':'Fix the errors and preview again'}</p><p className="form-help" id="employee-import-scroll-hint">Scroll sideways to review every column. Errors must be fixed before import.</p><div className="hr-import-preview" role="region" aria-label="Employee import preview" aria-describedby="employee-import-scroll-hint" tabIndex={0}><Table columns={['row','employeeCode','name','email','phone','joiningDate','departmentCode','branchCode','shiftName','designation','employmentType','status',...(can('payroll')?['monthlySalary']:[]),'action','errors']} rows={preview.items.map((r:Row)=>({...r,id:String(r.row)}))} cell={(r,k)=>k==='monthlySalary'?currencyValue(r[k],currency):k==='errors'?r.errors.length?<span className="hr-error">{r.errors.join('; ')}</span>:<Badge value="VALID"/>:undefined}/></div></>}
    <div className="hr-import-tools"><button className="btn secondary" disabled={busy||!file} onClick={check}>{busy?'Working…':'Preview file'}</button><button className="btn primary" disabled={busy||!preview?.valid} onClick={save}>Import {preview?.total??''} employees</button></div>
  </div></Modal>;
}

export function ApprovalSettings(){
  const {can,mutate}=useApp();const q=useData('approval-policies',can('company')),[busy,setBusy]=useState(false);
  if(!can('company'))return null;
  return <section className="panel hr-approval-settings"><div className="panel-heading"><div><small>REQUEST WORKFLOWS</small><h2>Approval levels</h2><p>New requests keep their assigned workflow even if this setting changes later. Without a reporting manager, requests go directly to HR.</p></div><ShieldCheck size={22}/></div>
    {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.map((r:Row)=><label className="hr-policy-row" key={r.resource}><strong>{r.resource==='leave'?'Time off':r.resource==='expenses'?'Expenses':'Travel'}</strong><select aria-label={r.resource+' approval policy'} value={r.mode} disabled={busy||!can('company','MANAGE')} onChange={async e=>{setBusy(true);try{await mutate('approval-policies','POST',{resource:r.resource,mode:e.target.value})}catch{}finally{setBusy(false)}}}><option value="SINGLE">One authorized reviewer</option><option value="MANAGER_HR">Reporting manager → HR / Finance</option></select></label>)}
  </section>;
}

export function EmployeeTasksModal({employee,onClose}:{employee:Row;onClose:()=>void}){
  const {mutate,can}=useApp(),q=useData(`employees/${employee.id}/tasks`),[kind,setKind]=useState('JOINING'),[add,setAdd]=useState(false),[busy,setBusy]=useState(false);
  const rows:Row[]=(q.data?.items??[]).filter((r:Row)=>r.kind===kind);
  return <Modal title={employee.firstName+' '+employee.lastName+' · Checklists'} onClose={onClose} wide><div className="modal-body hr-checklist"><div className="tabs">{['JOINING','EXIT'].map(k=><button key={k} className={kind===k?'active':''} onClick={()=>setKind(k)}>{k==='JOINING'?'Joining':'Exit'}</button>)}</div>
    <div className="row-between"><p>{rows.filter(r=>r.completed).length} of {rows.length} tasks complete</p>{can('employees','EDIT')&&<div className="hr-import-tools"><button className="btn secondary small" disabled={busy} onClick={async()=>{setBusy(true);try{await mutate(`employees/${employee.id}/tasks`,'POST',{kind})}catch{}finally{setBusy(false)}}}>Start standard checklist</button><button className="btn secondary small" onClick={()=>setAdd(v=>!v)}>Add task</button></div>}</div>
    {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:rows.length?<div className="hr-task-list">{rows.map(r=><label key={r.id}><input type="checkbox" checked={r.completed} disabled={busy||!can('employees','EDIT')} onChange={async e=>{setBusy(true);try{await mutate(`employees/${employee.id}/tasks`,'PATCH',{taskId:r.id,completed:e.target.checked,expectedUpdatedAt:r.updatedAt})}catch{}finally{setBusy(false)}}}/><span><strong>{r.title}</strong><small>{r.completed?'Completed '+displayDate(r.completedAt):r.dueDate?'Due '+displayDate(r.dueDate):'Pending'}</small></span></label>)}</div>:<Empty title="Checklist not started" description="Start the standard checklist or add your own tasks."/>}
    {can('documents','CREATE')&&<div className="hr-letter-links">{['appointment','experience','relieving'].map(k=><a key={k} className="btn secondary small" href={`/api/employees/${employee.id}/letter?kind=${k}`}>{k[0].toUpperCase()+k.slice(1)} letter PDF</a>)}<small>Experience and relieving letters require completed offboarding.</small></div>}
  </div>{add&&<RecordForm fields={[{key:'title',label:'Task title',required:true},{key:'dueDate',label:'Due date',type:'date'}]} onCancel={()=>setAdd(false)} onSave={async body=>{await mutate(`employees/${employee.id}/tasks`,'POST',{...body,kind});setAdd(false)}} submit="Add checklist task"/>}</Modal>;
}

export function AssetHistoryModal({asset,onClose}:{asset:Row;onClose:()=>void}){
  const q=useData(`assets/${asset.id}/history`);
  return <Modal title={asset.name+' · History'} onClose={onClose} wide><div className="modal-body">{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<Table columns={['kind','employeeName','note','createdAt']} rows={q.data.items} cell={(r,k)=>k==='createdAt'?new Date(r.createdAt).toLocaleString('en-IN'):k==='kind'?<Badge value={r.kind}/>:undefined}/>:<Empty title="No recorded events yet" description="Assignments, returns and status changes from this release are recorded here."/>}</div></Modal>;
}

export function TrainingEnrollmentModal({course,onClose}:{course:Row;onClose:()=>void}){
  const q=useData(`courses/${course.id}/enrollments`),{can,mutate}=useApp(),[edit,setEdit]=useState<Row|null>(null),[add,setAdd]=useState(false);
  return <Modal title={course.title+' · Participants'} onClose={onClose} wide><div className="modal-body"><div className="row-between"><p>Capacity {q.data?.course?.capacity??course.capacity} · {(q.data?.items??[]).filter((r:Row)=>r.status!=='CANCELLED').length} active</p>{can('training','MANAGE')&&<button className="btn primary" onClick={()=>setAdd(true)}>Enroll employee</button>}</div>
    {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<Table columns={['employeeName','employeeCode','status','score','completedAt']} rows={q.data.items} cell={(r,k)=>k==='status'?<Badge value={r.status}/>:k==='completedAt'?displayDate(r.completedAt):undefined} actions={r=><>{can('training','MANAGE')&&<button className="btn secondary small" onClick={()=>setEdit(r)}>Update progress</button>}{r.status==='COMPLETED'&&<a className="btn secondary small" href={'/api/training-certificates/'+r.id}>Certificate PDF</a>}</>}/>:<Empty title="No participants yet" description="Enroll employees, record completion and download certificates."/>}
  </div>{add&&<RecordForm fields={[{key:'employeeId',label:'Employee',type:'select',source:'employees',required:true}]} onCancel={()=>setAdd(false)} onSave={async body=>{await mutate(`courses/${course.id}/enrollments`,'POST',body);setAdd(false)}} submit="Enroll employee"/>}
  {edit&&<RecordForm key={edit.id} fields={[{key:'status',label:'Enrollment status',type:'select',required:true,options:['ENROLLED','COMPLETED','CANCELLED']},{key:'score',label:'Assessment score (optional)',type:'number',min:0,max:100}]} initial={edit} onCancel={()=>setEdit(null)} onSave={async body=>{await mutate(`courses/${course.id}/enrollments`,'PATCH',{...body,score:body.score===''?null:body.score,enrollmentId:edit.id,expectedUpdatedAt:edit.updatedAt});setEdit(null)}} submit="Save progress"/>}</Modal>;
}

export function OperationAlerts(){
  const {can,session}=useApp(),enabled=can('employees')&&!['EMPLOYEE','MANAGER','TEAM_LEADER'].includes(session.user.role),q=useData('operations/summary',enabled);
  if(!enabled||!q.data)return null;const r=q.data;
  return <div className="hr-operation-alerts">{[{label:'Checklist tasks',value:r.openTasks,href:'/employees',icon:<ClipboardCheck size={18}/>},{label:'Documents expiring / expired',value:r.expiringDocuments.length,href:'/documents',icon:<History size={18}/>},{label:'Devices need attention',value:r.offlineDevices.length,href:'/devices',icon:<ShieldCheck size={18}/>},{label:'Transfers to verify',value:r.unverifiedTransfers,href:'/payroll',icon:<Wallet size={18}/>}].filter(x=>x.value>0).map(x=><a href={x.href} key={x.label}>{x.icon}<span>{x.label}</span><strong>{x.value}</strong><ArrowRight size={15}/></a>)}</div>;
}
