'use client';
import React,{useId,useState} from 'react';
import Link from 'next/link';
import {Users,UserCheck,Clock3,CalendarDays,ArrowUpRight,ChevronRight,Wallet,Activity,RefreshCw,Server,Bell,Headphones,CheckCircle2,AlertTriangle,Building2,ArrowRight,FileText} from 'lucide-react';
import {Avatar,Badge,currencyValue,displayDate} from './core';
import {Row,readable} from './config';
import {attendanceTrendData} from './dashboard-chart';
import {overviewSnapshot} from './overview-data';
import './hr-overview.css';

function Pulse({attendance,timezone}:{attendance:Row[];timezone:string}){
 const id=useId().replace(/:/g,''),{days,values,max}=attendanceTrendData(attendance.map(r=>({date:String(r.date),status:String(r.status)})),timezone);
 return <div className="ov-chart"><svg viewBox="0 0 640 225" role="img" aria-labelledby={id+'-title '+id+'-desc'}><title id={id+'-title'}>Present employees over the last seven days</title><desc id={id+'-desc'}>{days.map((day,i)=>`${day}: ${values[i]} present`).join('; ')}</desc><defs><linearGradient id={id+'-bar'} x1="0" x2="0" y1="0" y2="1"><stop stopColor="#38bdf8"/><stop offset="1" stopColor="#0ea5e9"/></linearGradient></defs>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1="37" x2="627" y1={180-v*144} y2={180-v*144} stroke="#e8eef4" strokeDasharray={v?'3 5':undefined}/><text x="25" y={184-v*144} textAnchor="end" fill="#7c8b9e" fontSize="11">{max*v}</text></g>)}{values.map((v,i)=>{const x=60+i*82,y=180-v/max*144;return <g key={days[i]}><rect x={x} y="36" width="34" height="144" rx="7" fill={i===6?'#f0f9ff':'#f7f9fc'}/>{v>0&&<rect x={x} y={y} width="34" height={180-y} rx="7" fill={`url(#${id}-bar)`}/>}<text x={x+17} y={v?Math.max(23,y-9):168} fill={i===6?'#0369a1':'#52657a'} fontSize="12" textAnchor="middle" fontWeight="600">{v}</text><text x={x+17} y="210" fill={i===6?'#0369a1':'#7c8b9e'} fontSize="11" textAnchor="middle" fontWeight={i===6?700:400}>{new Date(days[i]+'T00:00:00Z').toLocaleDateString('en',{weekday:'short',timeZone:'UTC'})}</text></g>})}</svg></div>;
}
function Metric({label,value,detail,icon,href,tone='sky'}:{label:string;value:React.ReactNode;detail:string;icon:React.ReactNode;href?:string;tone?:string}){
 const body=<><div className="ov-metric-top"><span className={'ov-icon '+tone}>{icon}</span>{href&&<ArrowUpRight size={16}/>}</div><span className="ov-metric-label">{label}</span><strong>{value}</strong><small>{detail}</small></>;
 return href?<Link href={href} className="ov-metric">{body}</Link>:<div className="ov-metric">{body}</div>;
}
function NoItems({title,detail}:{title:string;detail:string}){return <div className="ov-empty"><span><CheckCircle2 size={22}/></span><strong>{title}</strong><p>{detail}</p></div>}
export function HROverview({session,data,events,currency,can,greeting,clock,onRefresh}:{session:any;data:Row;events:Row[];currency:string;can:(resource:string)=>boolean;greeting:string;clock:React.ReactNode;onRefresh:()=>Promise<any>}){
 const[refreshing,setRefreshing]=useState(false);const timezone=data.company?.timezone??'Asia/Kolkata',today=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const s=overviewSnapshot(data,today),attendanceAccess=can('attendance'),leaveAccess=can('leave'),payrollAccess=can('payroll'),payroll=payrollAccess?data.payroll:null;
 const devices:Row[]=data.devices??[],online=devices.filter(d=>['ONLINE','CONNECTED'].includes(d.status)).length,offline=devices.length-online;
 const nextEvents=events.filter(e=>String(e.endDate??e.date).slice(0,10)>=today).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(0,4);
 const breakdown=[['Present',s.present,'sky'],['Half Day',s.halfDay,'violet'],['Insufficient Time',s.insufficient,'amber'],['Absent',s.absent,'red'],['Not checked in',s.notChecked,'slate'],['Other / leave',s.other,'mint']] as const;
 const shortcuts=[['employees','People directory','Employee records',<Users size={19}/>],['attendance','Attendance','Daily work & punches',<Clock3 size={19}/>],['organization','Organization','Teams & departments',<Building2 size={19}/>],['payroll','Payroll','Salary & payments',<Wallet size={19}/>],['calendar','Calendar','Events & schedules',<CalendarDays size={19}/>],['reports','Reports','Report center',<FileText size={19}/>]] as const;
 const permission=(resource:string)=>can(resource);
 async function refresh(){setRefreshing(true);try{await onRefresh()}finally{setRefreshing(false)}}
 return <div className="hr-overview">
  <header className="ov-header"><div><span className="ov-eyebrow">WORKSPACE OVERVIEW</span><h1>Your people. Your day.</h1><p>Everything you need to keep your workplace moving.</p></div><button className="btn secondary ov-refresh" onClick={refresh} disabled={refreshing}><RefreshCw size={16} className={refreshing?'spin':''}/>{refreshing?'Refreshing…':'Refresh dashboard'}</button></header>
  <section className="ov-welcome"><div className="ov-welcome-person"><Avatar name={session.user.name} src={session.user.avatar}/><div><span>{greeting.toLowerCase()},</span><h2>{String(session.user.name??'').split(' ')[0]||'Welcome'} <span>👋</span></h2><p>{session.user.roleName} <i/> {data.company?.name??'Your workspace'}</p></div></div><div className="ov-welcome-note"><span className="ov-live-dot"/>Your workspace at a glance</div><div className="ov-clock">{clock}</div></section>
  <div className="ov-metrics">
   <Metric label="Total employees" value={s.people.length} detail="People in your workspace" icon={<Users size={20}/>} href={can('employees')?'/employees':undefined}/>
   <Metric label="Present today" value={attendanceAccess?s.present:'—'} detail={attendanceAccess?`${s.attendanceRate}% of your workforce`:'Attendance access required'} icon={<UserCheck size={20}/>} href={attendanceAccess?'/attendance':undefined} tone="mint"/>
   <Metric label="On leave today" value={leaveAccess?s.onLeave:'—'} detail={leaveAccess?`${s.pending.length} request${s.pending.length===1?'':'s'} awaiting review`:'Leave access required'} icon={<CalendarDays size={20}/>} href={leaveAccess?'/leave':undefined} tone="violet"/>
   <Metric label="Latest net payroll" value={!payrollAccess?'—':payroll?currencyValue(payroll.totalNet,currency):'Not prepared'} detail={!payrollAccess?'Payroll access required':payroll?`${payroll.month} · ${readable(String(payroll.status).toLowerCase())}`:'Prepare your first payroll run'} icon={<Wallet size={20}/>} href={payrollAccess?'/payroll':undefined} tone="amber"/>
  </div>
  <div className="ov-main-grid">
   <section className="ov-panel ov-pulse"><div className="ov-panel-heading"><div><span className="ov-eyebrow">ATTENDANCE INSIGHTS</span><h2>7-day attendance pulse</h2><p>Daily present employee count</p></div><span className="ov-pill"><span/>Last 7 days</span></div>{attendanceAccess?<><Pulse attendance={data.attendance??[]} timezone={timezone}/><div className="ov-chart-footer"><span><i/>Present employees</span><Link href="/attendance">View attendance <ArrowUpRight size={14}/></Link></div></>:<NoItems title="Attendance access required" detail="Your administrator can give you access to attendance insights."/>}</section>
   <section className="ov-panel ov-today"><div className="ov-panel-heading"><div><span className="ov-eyebrow">TODAY AT A GLANCE</span><h2>Workforce snapshot</h2></div><Activity size={18}/></div>{attendanceAccess?<><div className="ov-attendance-total"><strong>{s.attendanceRate}<small>%</small></strong><div><span>Present today</span><p>{s.present} of {s.people.length} employees</p></div></div><div className="ov-distribution" aria-label="Today's attendance distribution">{breakdown.filter(([,value])=>value>0).map(([label,value,tone])=><span key={label} className={tone} style={{flex:value}} title={`${label}: ${value}`}/>)}</div><div className="ov-breakdown">{breakdown.map(([label,value,tone])=><div key={label}><span><i className={tone}/>{label}</span><strong>{value}</strong></div>)}</div></>:<NoItems title="Attendance is private" detail="This view follows your role’s attendance permissions."/>}</section>
  </div>
  <div className="ov-bottom-grid">
   <section className="ov-panel"><div className="ov-panel-heading"><div><span className="ov-eyebrow">YOUR ACTION CENTER</span><h2>Leave approvals {leaveAccess&&<b className="ov-count">{s.pending.length}</b>}</h2></div>{leaveAccess&&<Link className="ov-small-link" href="/leave" aria-label="Review leave requests"><ArrowUpRight size={17}/></Link>}</div>{!leaveAccess?<NoItems title="Leave access required" detail="Your role controls which requests you can review."/>:s.pending.length?<div className="ov-approvals">{s.pending.slice(0,3).map(r=>{const e=s.people.find(p=>p.id===r.employeeId),name=e?`${e.firstName} ${e.lastName}`:'Employee';return <Link href="/leave" key={r.id} className="ov-person-row"><Avatar name={name} src={e?.photo}/><div><strong>{name}</strong><small>{displayDate(r.startDate)} · {r.days} day{r.days===1?'':'s'}</small></div><Badge value="PENDING"/></Link>})}</div>:<NoItems title="You’re all caught up" detail="New leave requests will appear here for review."/>}{leaveAccess&&<Link className="ov-panel-link" href="/leave">View leave requests <ChevronRight size={15}/></Link>}</section>
   <section className="ov-panel"><div className="ov-panel-heading"><div><span className="ov-eyebrow">ON THE CALENDAR</span><h2>Upcoming events</h2></div><CalendarDays size={18}/></div>{!can('calendar')?<NoItems title="Calendar access required" detail="Contact your administrator to view schedules."/>:nextEvents.length?<div className="ov-events">{nextEvents.map(e=><Link href="/calendar" className="ov-event-row" key={e.id}><span className="ov-event-date"><small>{new Date(String(e.date).slice(0,10)+'T00:00:00Z').toLocaleDateString('en',{month:'short',timeZone:'UTC'})}</small><strong>{String(e.date).slice(8,10)}</strong></span><div><strong>{e.title}</strong><small>{readable(String(e.kind??'EVENT').toLowerCase())}</small></div><ChevronRight size={14}/></Link>)}</div>:<NoItems title="A clear calendar" detail="Your company’s scheduled events will appear here."/>}{can('calendar')&&<Link className="ov-panel-link" href="/calendar">Open calendar <ChevronRight size={15}/></Link>}</section>
   <section className="ov-panel ov-workspace"><div className="ov-panel-heading"><div><span className="ov-eyebrow">WORKSPACE HEALTH</span><h2>Stay in the loop</h2></div><Server size={18}/></div><div className="ov-health">
    {can('devices')&&<Link href="/devices"><span className="ov-health-icon"><Server size={17}/></span><div><strong>Attendance devices</strong><small>{devices.length?`${online} online · ${offline} need attention`:'No devices configured'}</small></div><span className={'ov-health-status '+(offline?'warning':'')}>{devices.length?offline?'Review':'Online':'Set up'}</span></Link>}
    <Link href="/notifications"><span className="ov-health-icon"><Bell size={17}/></span><div><strong>Notifications</strong><small>Unread workspace updates</small></div><b>{data.unreadNotifications??0}</b></Link>
    {can('support')&&<Link href="/support"><span className="ov-health-icon"><Headphones size={17}/></span><div><strong>Support tickets</strong><small>Open requests</small></div><b>{(data.support??[]).filter((r:Row)=>r.status!=='RESOLVED').length}</b></Link>}
    {attendanceAccess&&<Link href="/attendance"><span className="ov-health-icon"><AlertTriangle size={17}/></span><div><strong>Attendance alerts</strong><small>{s.late} late · {s.overtimeMinutes} overtime minutes</small></div><b>{s.alerts}</b></Link>}
   </div></section>
  </div>
  <section className="ov-panel ov-shortcuts"><div><span className="ov-eyebrow">QUICK ACCESS</span><h2>Your everyday tools</h2></div><div className="ov-shortcut-grid">{shortcuts.filter(([resource])=>permission(resource)).map(([resource,label,detail,icon])=><Link href={'/'+resource} key={resource}><span className="ov-shortcut-icon">{icon}</span><div><strong>{label}</strong><small>{detail}</small></div><ArrowRight size={16}/></Link>)}</div></section>
 </div>;
}
