'use client';
import React,{useEffect,useState} from 'react';
import {CalendarClock,Landmark,ShieldCheck,Wallet} from 'lucide-react';
import {useApp,useData,Loading,Failure,Table,Badge,Modal,currencyValue} from './core';
import {Row} from './config';
import './payroll-payments.css';

export function CompanyPaymentSettings(){
 const {can,mutate}=useApp(),q=useData('payroll-payment-settings'),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[form,setForm]=useState({provider:'BANK_FILE',bankName:'',accountLabel:'Company salary account',mode:'NEFT',enabled:false}),[credentials,setCredentials]=useState({keyId:'',keySecret:'',sourceAccount:'',corporateId:''});
 useEffect(()=>{const c=q.data?.connection;if(c)setForm({provider:c.provider,bankName:c.bankName,accountLabel:c.accountLabel,mode:c.mode,enabled:c.enabled});setConfirmed(false);setCredentials({keyId:'',keySecret:'',sourceAccount:'',corporateId:''})},[q.data?.connection?.revision]);
 if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;
 const editable=can('company','EDIT')&&can('payroll','APPROVE'),api=['RAZORPAYX','BANK_API'].includes(form.provider),c=q.data?.connection;
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await mutate('payroll-payment-settings','PUT',{...form,enabled:api&&form.enabled,expectedRevision:c?.revision??0,confirm:true,...(api&&Object.values(credentials).some(Boolean)?{credentials}:{})});await q.refetch();setConfirmed(false)}catch{}finally{setBusy(false)}}
 return <section className="panel company-payments"><div className="payroll-payment-title"><Landmark size={24}/><div><h2>Company payment settings</h2><p>Each company connects its own salary account. Credentials stay encrypted and are never shown again.</p></div></div><div className="payment-summary"><span>Saved account <strong>{c?.accountLabel??'Not configured'} {c?.accountHint??''}</strong></span><span>Live payments <Badge value={c?.enabled?'ENABLED':'DISABLED'}/></span><span>Company timezone <strong>{q.data?.timezone}</strong></span></div>
 <form onSubmit={save}><fieldset disabled={!editable||busy} className="payment-form-grid"><label className="field"><span>Payment method</span><select aria-label="Payment method" value={form.provider} onChange={e=>{setForm({...form,provider:e.target.value,enabled:false});setCredentials({keyId:'',keySecret:'',sourceAccount:'',corporateId:''});setConfirmed(false)}}><option value="BANK_FILE">Bank file / corporate portal</option><option value="MANUAL">Manual bank transfer / cash / cheque</option><option value="RAZORPAYX">RazorpayX payout API</option><option value="BANK_API">Business bank API</option></select></label><label className="field"><span>Account label</span><input required maxLength={120} value={form.accountLabel} onChange={e=>setForm({...form,accountLabel:e.target.value})}/></label><label className="field"><span>Bank / installed connector</span>{form.provider==='BANK_API'&&(q.data?.bankConnectors??[]).length>0?<select aria-label="Bank / installed connector" value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value,enabled:false})}><option value="">Select installed bank connector</option>{(q.data?.bankConnectors??[]).map((b:Row)=><option key={b.code} value={b.code}>{b.label}</option>)}{form.bankName&&!(q.data?.bankConnectors??[]).some((b:Row)=>b.code===form.bankName)&&<option value={form.bankName}>{form.bankName} · not installed</option>}</select>:<input maxLength={120} value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value})}/>}</label><label className="field"><span>Default transfer mode</span><select aria-label="Default transfer mode" value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}>{['NEFT','IMPS','RTGS'].map(m=><option key={m}>{m}</option>)}</select></label>
 {api&&<><p className="payment-span form-help">Use credentials supplied for this company’s own API-enabled account. Leave all credential fields blank to keep the saved connection. Enter all fields to replace it.</p>{!q.data?.secureStorageReady&&<p className="payment-span notice">Secure credential storage requires administrator setup before an API account can be saved.</p>}{form.provider==='BANK_API'&&!(q.data?.bankConnectors??[]).length&&<p className="payment-span notice">No business bank connector is installed yet. Your bank must provide its API documentation, sandbox access and onboarding requirements to the software administrator. Bank files and manual payment remain available.</p>}{(['keyId','keySecret','sourceAccount',...(form.provider==='BANK_API'?['corporateId']:[])] as (keyof typeof credentials)[]).map(key=><label className="field" key={key}><span>{{keyId:'API key ID',keySecret:'API secret',sourceAccount:'Source account identifier',corporateId:'Bank corporate ID'}[key]}</span><input type={key==='keySecret'?'password':'text'} autoComplete="off" value={credentials[key]} onChange={e=>setCredentials({...credentials,[key]:e.target.value})}/></label>)}<label className="terms-check payment-span"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>Enable live payments from this company’s account</span></label></>}
 <label className="terms-check payment-span"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I am authorized to configure this company’s salary payment account and have checked these details.</span></label><div className="payment-span"><button className="btn primary" disabled={!confirmed||busy}>{busy?'Saving…':'Save company payment settings'}</button></div></fieldset></form><p className="form-help">Manual and bank-file modes record payments made outside the software. Automatic salary transfer needs a connected live API, finalized payroll and a separately approved schedule. Bank approval, balance, transfer limits and settlement time still apply.</p></section>;
}

export function PayrollPaymentCenter({run,onChanged}:{run:Row;onChanged:()=>void}){
 const {can,mutate,currency}=useApp(),q=useData(`payroll/${run.id}/payment-overview`,true,10000),[manual,setManual]=useState<Row|null>(null),[planning,setPlanning]=useState(false),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[date,setDate]=useState(''),[time,setTime]=useState('10:00'),[mode,setMode]=useState('NEFT'),[manualMode,setManualMode]=useState('BANK_TRANSFER'),[reference,setReference]=useState(''),[paidDate,setPaidDate]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)),[note,setNote]=useState('');
 if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;
 const rows:Row[]=q.data?.items??[],schedules:Row[]=q.data?.schedules??[],active=schedules.find(s=>['SCHEDULED','RUNNING'].includes(s.status)),approved=can('payroll','APPROVE');
 async function submitSchedule(e:React.FormEvent){e.preventDefault();setBusy(true);try{await mutate(`payroll/${run.id}/payment-schedule`,'POST',{localDate:date,localTime:time,mode,confirm:true});setPlanning(false);setConfirmed(false);await q.refetch();onChanged()}catch{}finally{setBusy(false)}}
 async function submitManual(e:React.FormEvent){e.preventDefault();if(!manual)return;setBusy(true);try{await mutate(`payroll/${run.id}/manual-payment`,'POST',{employeeId:manual.employeeId,expectedNet:manual.net,mode:manualMode,reference,...(manual.payoutUpdatedAt?{expectedPayoutUpdatedAt:manual.payoutUpdatedAt}:{}),paidAt:new Date(paidDate+'T00:00:00').toISOString(),note,confirm:true});setManual(null);setConfirmed(false);await q.refetch();onChanged()}catch{}finally{setBusy(false)}}
 return <section className="panel payroll-payment-center"><div className="payroll-payment-title"><CalendarClock size={24}/><div><h3>Salary payment controls</h3><p>Approve a time for API transfer or record a payment already made through your bank, cash or cheque.</p></div></div><div className="payment-toolbar">{approved&&<button className="btn primary" disabled={!q.data?.ready||!!active} onClick={()=>{setPlanning(true);setConfirmed(false)}}>Schedule automatic salary</button>}<a className="btn secondary" href={`/api/reports/bank-payout?runId=${run.id}`}>Download unpaid bank advice</a><button className="btn secondary" onClick={()=>q.refetch()}>Refresh payment checks</button></div>{q.data?.issues?.length>0&&<p className="form-help">API readiness: {q.data?.issues?.join(' · ')}</p>}<p className="form-help">Due payouts are checked every 10 seconds, subject to service availability and queued work. Bank processing decides when an employee receives the credit. Schedules missed by over 15 minutes require fresh approval.</p>
 {schedules.length>0&&<div className="payment-schedules"><h4>Salary schedules</h4><Table columns={['scheduledAt','timezone','mode','status','error']} rows={schedules} cell={(r,k)=>k==='scheduledAt'?new Date(r.scheduledAt).toLocaleString('en-IN',{timeZone:r.timezone}):k==='status'?<Badge value={r.status}/>:undefined} actions={r=>r.status==='SCHEDULED'&&approved?<button className="btn secondary small" disabled={busy} onClick={async()=>{setBusy(true);try{await mutate(`payroll/${run.id}/payment-schedule`,'DELETE');await q.refetch();onChanged()}catch{}finally{setBusy(false)}}}>Cancel schedule</button>:null}/></div>}
 <Table columns={['employeeName','employeeCode','net','accountHint','ifsc','paymentStatus','issues']} rows={rows.map(r=>({...r,id:r.employeeId}))} cell={(r,k)=>k==='net'?currencyValue(r.net,currency):k==='paymentStatus'?<Badge value={r.paymentStatus}/>:k==='issues'?r.issues.join('; ')||'—':undefined} actions={r=>approved&&r.net>0&&(r.paymentStatus==='NOT_STARTED'||r.canRecordReplacement)?<button className="btn secondary small" disabled={!!active} onClick={()=>{setManual(r);setReference('');setNote('');setConfirmed(false)}}>{r.canRecordReplacement?'Record replacement paid':'Record manual payment'}</button>:null}/>
 {planning&&<Modal title="Approve automatic salary payment" onClose={()=>{if(!busy)setPlanning(false)}}><form className="modal-body company-payments" onSubmit={submitSchedule}><p>Selected payroll: <strong>{run.month}</strong> · {currencyValue(Number(q.data?.remainingNet??0),currency)}. Timezone: <strong>{q.data?.timezone}</strong>.</p><div className="payment-form-grid"><label className="field"><span>Payment date</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Payment time ({q.data?.timezone})</span><input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label className="field"><span>Transfer mode</span><select aria-label="Transfer mode" value={mode} onChange={e=>setMode(e.target.value)}>{['NEFT','IMPS','RTGS'].map(m=><option key={m}>{m}</option>)}</select></label></div><p className="form-help">This approval authorizes automatic transfer of all remaining unclaimed salaries in this finalized run. Changed bank details or payment setup block the schedule. Submitted, failed or unknown transfers are never automatically sent again.</p><label className="terms-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified the salaries, employee accounts and available bank balance and authorize payment at this time.</span></label><button className="btn primary" disabled={!confirmed||busy}>{busy?'Scheduling…':'Approve salary schedule'}</button></form></Modal>}
 {manual&&<Modal title="Record salary paid outside software" onClose={()=>{if(!busy)setManual(null)}}><form className="modal-body company-payments" onSubmit={submitManual}><p><strong>{manual.employeeName} · {manual.employeeCode}</strong></p><p>Full net salary: <strong>{currencyValue(manual.net,currency)}</strong></p><label className="field"><span>Payment method</span><select aria-label="Payment method" value={manualMode} onChange={e=>setManualMode(e.target.value)}><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CHEQUE">Cleared cheque</option></select></label><label className="field"><span>Actual payment date (your device timezone)</span><input required type="date" value={paidDate} onChange={e=>setPaidDate(e.target.value)}/></label><label className="field"><span>UTR / cleared cheque / signed receipt reference</span><input required minLength={3} maxLength={120} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field"><span>Payment note</span><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="terms-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm the full salary was actually paid and this reference is correct. This records payment and updates the challan.</span></label><button className="btn primary" disabled={!confirmed||busy}>{busy?'Recording…':'Record confirmed salary payment'}</button></form></Modal>}
 </section>;
}
