'use client';
import React,{useEffect,useState} from 'react';
import {CalendarClock,Landmark,ShieldCheck,Wallet,FileDown,CheckCircle2,AlertCircle,RefreshCw,Search,LockKeyhole,ArrowRight} from 'lucide-react';
import {useApp,useData,Loading,Failure,Table,Modal,currencyValue} from './core';
import {Row} from './config';
import './payroll-payments.css';

const paymentMethods=[
 {value:'BANK_FILE',label:'Bank file',detail:'Export salaries for your corporate bank portal.',icon:FileDown},
 {value:'MANUAL',label:'Manual payment',detail:'Record salary already paid by bank, cash or cheque.',icon:Wallet},
 {value:'RAZORPAYX',label:'RazorpayX',detail:'Send salaries through your company payout account.',icon:Landmark},
 {value:'BANK_API',label:'Business bank API',detail:'Use an administrator-installed bank integration.',icon:ShieldCheck},
];
function PaymentStatus({value}:{value:string}){
 const status=String(value).toUpperCase(),labels:Record<string,string>={PROCESSED:'Paid',PAID:'Paid',NOT_STARTED:'Not started',NO_PAYMENT_DUE:'No payment due',INITIATING:'Submitting',UNKNOWN:'Needs review',DISPATCHED:'Submitted',NEEDS_ATTENTION:'Needs attention'};
 const tone=['PAID','PROCESSED'].includes(status)?'success':['FAILED','REVERSED','REJECTED','BLOCKED','UNKNOWN','NEEDS_ATTENTION'].includes(status)?'danger':['NOT_STARTED','NO_PAYMENT_DUE','CANCELLED'].includes(status)?'neutral':'pending';
 return <span className={`payment-status ${tone}`}><i aria-hidden="true"/>{labels[status]??status.toLowerCase().replaceAll('_',' ')}</span>;
}
export function CompanyPaymentSettings(){
 const {can,mutate}=useApp(),q=useData('payroll-payment-settings'),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[form,setForm]=useState({provider:'BANK_FILE',bankName:'',accountLabel:'Company salary account',mode:'NEFT',enabled:false}),[credentials,setCredentials]=useState({keyId:'',keySecret:'',sourceAccount:'',corporateId:''});
 useEffect(()=>{const c=q.data?.connection;if(c)setForm({provider:c.provider,bankName:c.bankName,accountLabel:c.accountLabel,mode:c.mode,enabled:c.enabled});setConfirmed(false);setCredentials({keyId:'',keySecret:'',sourceAccount:'',corporateId:''})},[q.data?.connection?.revision]);
 if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;
 const editable=can('company','EDIT')&&can('payroll','APPROVE'),api=['RAZORPAYX','BANK_API'].includes(form.provider),c=q.data?.connection;
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await mutate('payroll-payment-settings','PUT',{...form,enabled:api&&form.enabled,expectedRevision:c?.revision??0,confirm:true,...(api&&Object.values(credentials).some(Boolean)?{credentials}:{})});await q.refetch();setConfirmed(false)}catch{}finally{setBusy(false)}}
 return <section className="panel company-payments payment-settings-shell">
 <header className="payment-header"><div className="payment-header-icon"><Landmark size={24}/></div><div><span className="payment-eyebrow">BANKING & PAYOUTS</span><h2>Company payment settings</h2><p>Choose how your company pays salaries and connect its own salary account.</p></div><span className="payment-security"><LockKeyhole size={14}/>Company-only access</span></header>
 <div className="payment-summary"><div><span className="payment-summary-icon"><Wallet size={19}/></span><span>Saved account<strong>{c?.accountLabel??'Not configured'}</strong><small>{c?.accountHint||'No account number displayed'}</small></span></div><div><span className="payment-summary-icon"><ShieldCheck size={19}/></span><span>Live payments<strong className={c?.enabled?'payment-text-success':''}>{c?.enabled?'Enabled':'Disabled'}</strong><small>{c?.hasCredentials?'API credentials saved securely':'Connect an API to send salaries'}</small></span></div><div><span className="payment-summary-icon"><CalendarClock size={19}/></span><span>Company timezone<strong>{q.data?.timezone}</strong><small>Used for salary schedules</small></span></div></div>
 <div className="payment-settings-layout">
 <form onSubmit={save}>{!editable&&<div className="payment-notice"><LockKeyhole size={18}/><p>You can view this account. Company edit and payroll approval permissions are needed to make changes.</p></div>}<fieldset disabled={!editable||busy} className="payment-settings-fields">
 <section className="payment-form-section"><div className="payment-section-heading"><span>01</span><div><h3>Choose a payment method</h3><p>Select how salaries will be sent or recorded.</p></div></div><div className="payment-methods">{paymentMethods.map(m=><button type="button" key={m.value} aria-pressed={form.provider===m.value} className={`payment-method ${form.provider===m.value?'selected':''}`} onClick={()=>{setForm({...form,provider:m.value,enabled:false});setCredentials({keyId:'',keySecret:'',sourceAccount:'',corporateId:''});setConfirmed(false)}}><m.icon size={20}/><strong>{m.label}</strong><small>{m.detail}</small>{form.provider===m.value&&<CheckCircle2 size={16} className="payment-method-check"/>}</button>)}</div><label className="field"><span>Payment method</span><select aria-label="Payment method" value={form.provider} onChange={e=>{setForm({...form,provider:e.target.value,enabled:false});setCredentials({keyId:'',keySecret:'',sourceAccount:'',corporateId:''});setConfirmed(false)}}><option value="BANK_FILE">Bank file / corporate portal</option><option value="MANUAL">Manual bank transfer / cash / cheque</option><option value="RAZORPAYX">RazorpayX payout API</option><option value="BANK_API">Business bank API</option></select></label></section><section className="payment-form-section"><div className="payment-section-heading"><span>02</span><div><h3>Salary account details</h3><p>Give your salary account a name your payroll team recognizes.</p></div></div><div className="payment-form-grid"><label className="field"><span>Account label</span><input required maxLength={120} value={form.accountLabel} onChange={e=>setForm({...form,accountLabel:e.target.value})}/></label><label className="field"><span>Bank / installed connector</span>{form.provider==='BANK_API'&&(q.data?.bankConnectors??[]).length>0?<select aria-label="Bank / installed connector" value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value,enabled:false})}><option value="">Select installed bank connector</option>{(q.data?.bankConnectors??[]).map((b:Row)=><option key={b.code} value={b.code}>{b.label}</option>)}{form.bankName&&!(q.data?.bankConnectors??[]).some((b:Row)=>b.code===form.bankName)&&<option value={form.bankName}>{form.bankName} · not installed</option>}</select>:<input maxLength={120} value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value})}/>}</label><label className="field"><span>Default transfer mode</span><select aria-label="Default transfer mode" value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}>{['NEFT','IMPS','RTGS'].map(m=><option key={m}>{m}</option>)}</select></label>
 </div></section>{api&&<section className="payment-form-section"><div className="payment-section-heading"><span>03</span><div><h3>Secure API connection</h3><p>Use credentials issued for this company’s payout account.</p></div></div><div className="payment-form-grid"><p className="payment-span form-help">Use credentials supplied for this company’s own API-enabled account. Leave all credential fields blank to keep the saved connection. Enter all fields to replace it.</p>{!q.data?.secureStorageReady&&<p className="payment-span notice">Secure credential storage requires administrator setup before an API account can be saved.</p>}{form.provider==='BANK_API'&&!(q.data?.bankConnectors??[]).length&&<p className="payment-span notice">No business bank connector is installed yet. Your bank must provide its API documentation, sandbox access and onboarding requirements to the software administrator. Bank files and manual payment remain available.</p>}{(['keyId','keySecret','sourceAccount',...(form.provider==='BANK_API'?['corporateId']:[])] as (keyof typeof credentials)[]).map(key=><label className="field" key={key}><span>{{keyId:'API key ID',keySecret:'API secret',sourceAccount:'Source account identifier',corporateId:'Bank corporate ID'}[key]}</span><input type={key==='keySecret'?'password':'text'} autoComplete="off" value={credentials[key]} onChange={e=>setCredentials({...credentials,[key]:e.target.value})}/></label>)}<label className="terms-check payment-span"><input type="checkbox" disabled={!q.data?.secureStorageReady||(form.provider==='BANK_API'&&!(q.data?.bankConnectors??[]).some((b:Row)=>b.code===form.bankName))} checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>Enable live payments from this company’s account</span></label></div></section>}
 <footer className="payment-save"><label className="terms-check payment-span"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I am authorized to configure this company’s salary payment account and have checked these details.</span></label><div className="payment-save-actions"><span><ShieldCheck size={16}/>Changes apply only to this company</span><button className="btn primary" disabled={!confirmed||busy}>{busy?'Saving…':'Save company payment settings'}<ArrowRight size={16}/></button></div></footer></fieldset></form><aside className="payment-guide"><div className="payment-guide-icon"><ShieldCheck size={24}/></div><h3>Your salary payment checklist</h3><p>Account details alone do not authorize a bank transfer.</p><ol><li><strong>Set up your company account</strong><span>Choose bank files, manual payment or a live payout API.</span></li><li><strong>Check employee bank details</strong><span>Add the account number, IFSC and account holder in each employee’s profile.</span></li><li><strong>Finalize and approve payroll</strong><span>Review net salaries before paying now or approving a schedule.</span></li><li><strong>Track payments and challans</strong><span>Check each transfer’s status and UTR in payroll.</span></li></ol><a className="btn secondary" href="/payroll">Open payroll<ArrowRight size={16}/></a><div className="payment-guide-foot"><LockKeyhole size={16}/><span>Manual and bank-file modes record payments made outside the software. Automatic salary transfer needs a live API. Bank approval, balance, limits and settlement time still apply.</span></div></aside></div></section>;
}

export function PayrollPaymentCenter({run,onChanged}:{run:Row;onChanged:()=>void}){
 const {can,mutate,currency}=useApp(),q=useData(`payroll/${run.id}/payment-overview`,true,10000),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('ALL'),[manual,setManual]=useState<Row|null>(null),[planning,setPlanning]=useState(false),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[date,setDate]=useState(''),[time,setTime]=useState('10:00'),[mode,setMode]=useState('NEFT'),[manualMode,setManualMode]=useState('BANK_TRANSFER'),[reference,setReference]=useState(''),[paidDate,setPaidDate]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)),[note,setNote]=useState('');
 if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;
 const rows:Row[]=q.data?.items??[],schedules:Row[]=q.data?.schedules??[],active=schedules.find(s=>['SCHEDULED','RUNNING'].includes(s.status)),approved=can('payroll','APPROVE');
 const isPaid=(r:Row)=>['PAID','PROCESSED'].includes(String(r.paymentStatus).toUpperCase()),needsAttention=(r:Row)=>r.issues.length>0||['FAILED','REVERSED','UNKNOWN','REJECTED'].includes(String(r.paymentStatus).toUpperCase());
 const paid=rows.filter(isPaid).length,attention=rows.filter(needsAttention).length;
 const visibleRows=rows.filter(r=>`${r.employeeName} ${r.employeeCode} ${r.ifsc}`.toLowerCase().includes(search.toLowerCase())&&(statusFilter==='ALL'||(statusFilter==='UNPAID'?r.paymentStatus==='NOT_STARTED':statusFilter==='PAID'?isPaid(r):needsAttention(r))));
 async function submitSchedule(e:React.FormEvent){e.preventDefault();setBusy(true);try{await mutate(`payroll/${run.id}/payment-schedule`,'POST',{localDate:date,localTime:time,mode,confirm:true});setPlanning(false);setConfirmed(false);await q.refetch();onChanged()}catch{}finally{setBusy(false)}}
 async function submitManual(e:React.FormEvent){e.preventDefault();if(!manual)return;setBusy(true);try{await mutate(`payroll/${run.id}/manual-payment`,'POST',{employeeId:manual.employeeId,expectedNet:manual.net,mode:manualMode,reference,...(manual.payoutUpdatedAt?{expectedPayoutUpdatedAt:manual.payoutUpdatedAt}:{}),paidAt:new Date(paidDate+'T00:00:00').toISOString(),note,confirm:true});setManual(null);setConfirmed(false);await q.refetch();onChanged()}catch{}finally{setBusy(false)}}
 return <section className="panel payroll-payment-center">
 <header className="payment-header"><div className="payment-header-icon"><CalendarClock size={24}/></div><div><span className="payment-eyebrow">SALARY DISBURSEMENT</span><h3>Salary payment controls</h3><p>Schedule approved salary transfers or record payments already made.</p></div><a className="btn secondary small" href="/payroll?tab=payments"><Landmark size={15}/>Payment settings</a></header>
 <div className="payment-center-body"><div className="payment-metrics"><div><Wallet size={20}/><span>Unclaimed salary<strong>{currencyValue(Number(q.data?.remainingNet??0),currency)}</strong></span></div><div><CheckCircle2 size={20}/><span>Employees paid<strong>{paid}<small> / {rows.length}</small></strong></span></div><div><AlertCircle size={20}/><span>Needs attention<strong>{attention}<small> employee{attention===1?'':'s'}</small></strong></span></div></div>
 <div className={`payment-readiness ${q.data?.ready?'ready':''}`}><div>{q.data?.ready?<CheckCircle2 size={21}/>:<AlertCircle size={21}/>}<div><strong>{active?'Salary schedule active':q.data?.ready?'Ready to schedule salary':'Complete setup before automatic payment'}</strong><p>{active?'An approved schedule is active. Manual payments are paused until it finishes or is cancelled.':q.data?.ready?'Review the employee accounts below, then approve a payment date and time.':q.data?.issues?.join(' · ')}</p></div></div>{!q.data?.ready&&!active&&<a href="/payroll?tab=payments">Review payment setup<ArrowRight size={15}/></a>}</div>
 <div className="payment-toolbar">{approved&&<button className="btn primary" disabled={!q.data?.ready||!!active} onClick={()=>{setPlanning(true);setConfirmed(false)}}><CalendarClock size={16}/>Schedule automatic salary</button>}<a className="btn secondary" href={`/api/reports/bank-payout?runId=${run.id}`}><FileDown size={16}/>Download unpaid bank advice</a><button className="btn secondary" onClick={()=>q.refetch()} disabled={q.isFetching}><RefreshCw size={16}/>Refresh payment checks</button></div>
 <p className="payment-timing-note"><CalendarClock size={15}/><span>Schedules use {q.data?.timezone}. Transfer starts around the approved time; actual credit depends on your bank. Missed schedules need fresh approval.</span></p>
 {schedules.length>0&&<div className="payment-schedules"><h4>Salary schedules</h4><Table columns={['scheduledAt','timezone','mode','status','error']} rows={schedules} cell={(r,k)=>k==='scheduledAt'?new Date(r.scheduledAt).toLocaleString('en-IN',{timeZone:r.timezone}):k==='status'?<PaymentStatus value={r.status}/>:undefined} actions={r=>r.status==='SCHEDULED'&&approved?<button className="btn secondary small" disabled={busy} onClick={async()=>{setBusy(true);try{await mutate(`payroll/${run.id}/payment-schedule`,'DELETE');await q.refetch();onChanged()}catch{}finally{setBusy(false)}}}>Cancel schedule</button>:null}/></div>}
 <div className="payment-table-heading"><div><h4>Employee payment details</h4><p>{visibleRows.length} of {rows.length} employees · account numbers are masked</p></div><div className="payment-filters"><label className="payment-search"><Search size={16}/><input aria-label="Search salary payments" placeholder="Search name, code or IFSC" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter salary payments" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All payments</option><option value="UNPAID">Not started</option><option value="PAID">Paid</option><option value="ATTENTION">Needs attention</option></select></div></div>
 <Table columns={['employeeName','employeeCode','net','accountHint','ifsc','paymentStatus','issues']} rows={visibleRows.map(r=>({...r,id:r.employeeId}))} cell={(r,k)=>k==='net'?currencyValue(r.net,currency):k==='paymentStatus'?<PaymentStatus value={r.paymentStatus}/>:k==='issues'?r.issues.join('; ')||'—':undefined} actions={r=>approved&&r.net>0&&(r.paymentStatus==='NOT_STARTED'||r.canRecordReplacement)?<button className="btn secondary small" disabled={!!active} onClick={()=>{setManual(r);setReference('');setNote('');setConfirmed(false)}}>{r.canRecordReplacement?'Record replacement paid':'Record manual payment'}</button>:null}/>
 {visibleRows.length===0&&<div className="payment-empty"><Search size={24}/><strong>{rows.length?'No matching salary payments':'No employees in this payroll'}</strong><p>{rows.length?'Try another name or payment status.':'Add employees and prepare payroll to see payments here.'}</p>{rows.length>0&&<button className="btn secondary small" onClick={()=>{setSearch('');setStatusFilter('ALL')}}>Clear filters</button>}</div>}<p className="payment-scroll-hint">Scroll the table sideways to see bank details and payment actions.</p></div>
 {planning&&<Modal title="Approve automatic salary payment" onClose={()=>{if(!busy)setPlanning(false)}}><form className="modal-body company-payments" onSubmit={submitSchedule}><p>Selected payroll: <strong>{run.month}</strong> · {currencyValue(Number(q.data?.remainingNet??0),currency)}. Timezone: <strong>{q.data?.timezone}</strong>.</p><div className="payment-form-grid"><label className="field"><span>Payment date</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Payment time ({q.data?.timezone})</span><input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label className="field"><span>Transfer mode</span><select aria-label="Transfer mode" value={mode} onChange={e=>setMode(e.target.value)}>{['NEFT','IMPS','RTGS'].map(m=><option key={m}>{m}</option>)}</select></label></div><p className="form-help">This approval authorizes automatic transfer of all remaining unclaimed salaries in this finalized run. Changed bank details or payment setup block the schedule. Submitted, failed or unknown transfers are never automatically sent again.</p><label className="terms-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified the salaries, employee accounts and available bank balance and authorize payment at this time.</span></label><button className="btn primary" disabled={!confirmed||busy}>{busy?'Scheduling…':'Approve salary schedule'}</button></form></Modal>}
 {manual&&<Modal title="Record salary paid outside software" onClose={()=>{if(!busy)setManual(null)}}><form className="modal-body company-payments" onSubmit={submitManual}><p><strong>{manual.employeeName} · {manual.employeeCode}</strong></p><p>Full net salary: <strong>{currencyValue(manual.net,currency)}</strong></p><label className="field"><span>Payment method</span><select aria-label="Payment method" value={manualMode} onChange={e=>setManualMode(e.target.value)}><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CHEQUE">Cleared cheque</option></select></label><label className="field"><span>Actual payment date (your device timezone)</span><input required type="date" value={paidDate} onChange={e=>setPaidDate(e.target.value)}/></label><label className="field"><span>UTR / cleared cheque / signed receipt reference</span><input required minLength={3} maxLength={120} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field"><span>Payment note</span><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="terms-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm the full salary was actually paid and this reference is correct. This records payment and updates the challan.</span></label><button className="btn primary" disabled={!confirmed||busy}>{busy?'Recording…':'Record confirmed salary payment'}</button></form></Modal>}
 </section>;
}
