'use client';
import React,{useEffect,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {Users,UserCheck,Building2,CalendarDays,Plus,Search,LayoutGrid,List,RefreshCw,ChevronLeft,ChevronRight,Pencil,Trash2,ClipboardCheck,Smartphone,Mail,MapPin,Clock3,ArrowUpRight,Upload,ShieldCheck,Wallet,X,Eye} from 'lucide-react';
import {modules,type Row} from './config';
import {useApp,useData,Modal,RecordForm,Confirm,Loading,Failure,Empty,Badge,Avatar,PhotoViewer,currencyValue,displayDate} from './core';
import {EmployeeImportModal,EmployeeTasksModal} from './hr-operations';
import {EmployeeAppAccessModal} from './modules';
import './people.css';

const sections=[
 {title:'Identity & contact',description:'The essentials that identify this employee and keep you connected.',keys:['photo','employeeCode','firstName','lastName','email','phone']},
 {title:'Employment & reporting',description:'Assign the right department, location, shift and reporting manager.',keys:['departmentId','teamId','branchId','designation','shiftId','managerId','employmentType','joiningDate','status','personal.workLocation','personal.shiftName','personal.probationEnd','personal.confirmationDate']},
 {title:'Personal & emergency',description:'Optional personal information and an emergency contact.',keys:['personal.gender','personal.dob','personal.bloodGroup','personal.maritalStatus','personal.nationality','personal.address','personal.city','personal.state','personal.pincode','personal.emergencyContact','personal.emergencyPhone']},
 {title:'Salary & bank',description:'Profile salary and bank details used by your payroll team. Use Salary structures for an effective salary revision.',keys:['monthlySalary','personal.bankName','personal.accountHolder','personal.accountNumber','personal.ifsc','personal.bankBranch']},
 {title:'Compliance identifiers',description:'Optional identity, provident fund and insurance records.',keys:['personal.aadhaar','personal.pan','personal.uan','personal.pfNumber','personal.esicNumber']},
 {title:'Skills & HR notes',description:'Keep qualifications, experience and internal notes together.',keys:['personal.qualification','personal.experience','personal.skills','personal.notes']}
];
const sensitive=new Set(['monthlySalary','personal.bankName','personal.accountHolder','personal.accountNumber','personal.ifsc','personal.bankBranch']);
const fullName=(p:Row)=>[p.firstName,p.lastName].filter(Boolean).join(' ');
const human=(value:any)=>String(value??'').toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export function PeopleDirectory(){
 const {session,can,mutate,currency}=useApp(),params=useSearchParams();
 const restricted=['EMPLOYEE','MANAGER','TEAM_LEADER'].includes(session.user.role);
 const canCreate=can('employees','CREATE')&&!restricted,canEdit=can('employees','EDIT')&&!restricted,canDelete=can('employees','DELETE')&&!restricted;
 const canImport=can('employees','IMPORT')&&!restricted&&(canCreate||canEdit);
 const [search,setSearch]=useState(params.get('search')??''),[query,setQuery]=useState(search),[status,setStatus]=useState(''),[department,setDepartment]=useState(''),[branch,setBranch]=useState(''),[shift,setShift]=useState(''),[team,setTeam]=useState(params.get('teamId')??''),[sort,setSort]=useState('recent'),[page,setPage]=useState(1),[view,setView]=useState<'list'|'cards'>('list');
 const [editing,setEditing]=useState<Row|null>(null),[profile,setProfile]=useState<Row|null>(null),[deleting,setDeleting]=useState<Row|null>(null),[importing,setImporting]=useState(false),[tasks,setTasks]=useState<Row|null>(null),[access,setAccess]=useState<Row|null>(null),[photo,setPhoto]=useState<{src:string;name:string}|null>(null);
 useEffect(()=>{setSearch(params.get('search')??'');setTeam(params.get('teamId')??'');setPage(1)},[params]);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1)},250);return()=>clearTimeout(timer)},[search]);
 const filters=new URLSearchParams({q:query,status,departmentId:department,branchId:branch,shiftId:shift,teamId:team,sort,page:String(page),pageSize:'24',includeSummary:'true'});
 const data=useData('employees?'+filters),reportAccess=useData('reports/access',can('employees','EXPORT')&&can('reports','EXPORT'));
 const teams=useData('teams?pageSize=500',can('organization'));
 const rows:Row[]=data.data?.items??[],total=Number(data.data?.total??0),summary=data.data?.summary,facets=data.data?.filters??{},pages=Math.max(1,Math.ceil(total/24));
 useEffect(()=>{if(data.data&&page>pages)setPage(pages)},[data.data,page,pages]);
 const filtered=!!(search||status||department||branch||shift||team);
 function clear(){setSearch('');setQuery('');setStatus('');setDepartment('');setBranch('');setShift('');setTeam('');setPage(1)}
 const add=canCreate?<button type="button" className="btn primary" onClick={()=>setEditing(team?{teamId:team}:{})}><Plus size={18}/>Add Employee</button>:undefined;
 const actions=(p:Row)=><div className="pd-actions">{!restricted&&<button type="button" aria-label={'Checklists for '+fullName(p)} title="Joining / exit checklists" onClick={()=>setTasks(p)}><ClipboardCheck size={16}/></button>}{can('users','MANAGE')&&!restricted&&<button type="button" aria-label={'Employee App Access for '+fullName(p)} title="Employee App access" onClick={()=>setAccess(p)}><Smartphone size={16}/></button>}{canEdit&&<button type="button" aria-label="Edit employee" title={'Edit '+fullName(p)} onClick={()=>setEditing(p)}><Pencil size={16}/></button>}{canDelete&&<button type="button" className="pd-delete" aria-label="Delete employee" title={'Delete '+fullName(p)} onClick={()=>setDeleting(p)}><Trash2 size={16}/></button>}</div>;
 const person=(p:Row)=><div className="pd-person">{p.photo?<button type="button" className="pd-avatar" aria-label={'Open '+fullName(p)+' photo'} onClick={()=>setPhoto({src:p.photo,name:fullName(p)})}><Avatar name={fullName(p)} src={p.photo}/></button>:<Avatar name={fullName(p)}/>}<button type="button" className="pd-person-link" onClick={()=>setProfile(p)} aria-label={'View profile of '+fullName(p)}><strong>{fullName(p)}</strong><span>{p.employeeCode}</span></button></div>;
 const change=(fn:(v:string)=>void)=>(e:React.ChangeEvent<HTMLSelectElement>)=>{fn(e.target.value);setPage(1)};
 return <div className="people-workspace">
  <header className="pd-hero"><div><span className="pd-eyebrow"><Users size={16}/>PEOPLE & CULTURE</span><h1>Your team, connected.</h1><p>Every employee. Every detail. One organized workspace.</p><span className="pd-company"><Building2 size={14}/>{session.company?.name??'Your company'}</span></div><div className="pd-hero-actions">{add}<button type="button" className="btn secondary" disabled={data.isFetching} onClick={()=>data.refetch()}><RefreshCw size={16} className={data.isFetching?'spin':''}/>Refresh people</button></div></header>
  <section className="pd-stats" aria-label="People overview">{[{label:'Total people',value:summary?.total,detail:'Across your accessible organization',icon:Users},{label:'Active employees',value:summary?.active,detail:summary?`${summary.probation} on probation · ${summary.notice} on notice`:'Employment status',icon:UserCheck},{label:'Departments',value:summary?.departments,detail:'With employees assigned',icon:Building2},{label:'Joining this month',value:summary?.joining,detail:'Company calendar month',icon:CalendarDays}].map(s=><article key={s.label}><div><span>{s.label}</span><s.icon size={19}/></div><strong>{data.error?'—':s.value??'—'}</strong><small>{s.detail}</small></article>)}</section>
  <section className="pd-directory" aria-labelledby="pd-title"><div className="pd-directory-heading"><div><span className="pd-eyebrow">WORKFORCE DIRECTORY</span><h2 id="pd-title">Employee Directory</h2><p>Find a colleague, keep their record current, or manage app access.</p></div><div className="pd-directory-tools">{canImport&&<button type="button" className="btn secondary small" onClick={()=>setImporting(true)}><Upload size={16}/>Import employees</button>}{can('employees','EXPORT')&&can('reports','EXPORT')&&(reportAccess.data?.available?<Link className="btn secondary small" href="/reports"><ArrowUpRight size={16}/>Export reports</Link>:<span className="pd-maintenance" title="Reports are currently under maintenance"><ShieldCheck size={14}/>{reportAccess.isLoading?'Checking reports…':reportAccess.error?'Reports unavailable':'Reports under maintenance'}</span>)}</div></div>
   <div className="pd-toolbar"><label className="pd-search"><Search size={18}/><input name="people-directory-search" aria-label="Search people directory" placeholder="Search name, employee ID or email…" autoComplete="off" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button type="button" aria-label="Clear people search" onClick={()=>setSearch('')}><X size={16}/></button>}</label><select aria-label="Sort people" value={sort} onChange={change(setSort)}><option value="recent">Recently added</option><option value="name">Name A–Z</option><option value="joined">Latest joining date</option></select><div className="pd-view" aria-label="Directory view"><button type="button" aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={18}/></button><button type="button" aria-label="Card view" aria-pressed={view==='cards'} onClick={()=>setView('cards')}><LayoutGrid size={18}/></button></div></div>
   <div className="pd-filters"><select aria-label="Filter by status" value={status} onChange={change(setStatus)}><option value="">All statuses</option>{['ACTIVE','PROBATION','NOTICE','INACTIVE'].map(s=><option value={s} key={s}>{human(s)}</option>)}</select>{[['Department',department,setDepartment,facets.departments],['Branch',branch,setBranch,facets.branches],['Shift',shift,setShift,facets.shifts],['Team',team,setTeam,teams.data?.items]].map(([label,value,setter,items])=><select key={String(label)} aria-label={'Filter by '+String(label).toLowerCase()} value={String(value)} onChange={change(setter as (v:string)=>void)}><option value="">All {String(label)==='Branch'?'branches':String(label).toLowerCase()+'s'}</option>{((items??[]) as Row[]).map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select>)}{filtered&&<button type="button" className="pd-clear" onClick={clear}>Clear filters <X size={14}/></button>}</div>
   <div className="pd-results" aria-live="polite"><span>{data.isLoading?'Loading people…':data.error?'People unavailable':`${total} ${filtered?'matching ':''}${total===1?'employee':'employees'}`}</span><small>{query?`Results for “${query}”`:'Select an employee name to open their full profile.'}</small></div>
   {data.isLoading?<Loading/>:data.error?<Failure error={data.error} retry={()=>data.refetch()}/>:!rows.length?<Empty title={filtered?'No matching people':'Build your people directory'} description={filtered?'Try another name or clear your filters.':'Add your first employee or import your existing team.'} action={filtered?<button type="button" className="btn secondary" onClick={clear}>Clear filters</button>:add}/>:view==='cards'?<div className="pd-card-grid">{rows.map(p=><article className="pd-card" key={p.id}><div className="pd-card-top">{person(p)}<Badge value={p.status}/></div><h3>{p.designation||'Designation not assigned'}</h3><p><Building2 size={14}/>{p.departmentName||'Department not assigned'}</p><p><MapPin size={14}/>{p.branchName||'Branch not assigned'}</p><p><Clock3 size={14}/>{p.shiftName||'Shift not assigned'}</p><p><Mail size={14}/><span>{p.email}</span></p><footer><button type="button" className="pd-open" onClick={()=>setProfile(p)}>View profile <ArrowUpRight size={14}/></button>{actions(p)}</footer></article>)}</div>:<div className="pd-list"><table><thead><tr><th>Employee</th><th>Role & department</th><th>Location & shift</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{person(p)}<span className="pd-email">{p.email}</span></td><td data-label="Role & department"><strong>{p.designation||'Not assigned'}</strong><span>{p.departmentName||'Department not assigned'}</span></td><td data-label="Location & shift"><span>{p.branchName||'Branch not assigned'}</span><small><Clock3 size={12}/>{p.shiftName||'Shift not assigned'}</small></td><td data-label="Status"><Badge value={p.status}/></td><td data-label="Actions"><button type="button" className="pd-mobile-profile" onClick={()=>setProfile(p)}><Eye size={15}/>Profile</button>{actions(p)}</td></tr>)}</tbody></table></div>}
   {!data.isLoading&&!data.error&&total>0&&<footer className="pd-pagination"><span>Showing {(page-1)*24+1}–{Math.min(page*24,total)} of {total} people</span><div><button type="button" aria-label="Previous people page" disabled={page<=1||data.isFetching} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>Page {page} of {pages}</span><button type="button" aria-label="Next people page" disabled={page>=pages||data.isFetching} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></footer>}
  </section>
  <div className="pd-footnote"><ShieldCheck size={16}/><span>Employee records and actions follow your workspace permissions.</span>{can('organization')&&<Link href="/organization">Manage organization <ArrowUpRight size={14}/></Link>}</div>
  {editing&&<EmployeeEditor employee={editing} onClose={()=>setEditing(null)}/>}
  {profile&&<EmployeeProfile employee={profile} onClose={()=>setProfile(null)} onEdit={canEdit?p=>{setProfile(null);setEditing(p)}:undefined} onTasks={!restricted?p=>{setProfile(null);setTasks(p)}:undefined} onAccess={can('users','MANAGE')&&!restricted?p=>{setProfile(null);setAccess(p)}:undefined} onPhoto={(src,name)=>setPhoto({src,name})}/>}
  {deleting&&<Confirm title="Delete employee permanently?" description={`Delete ${fullName(deleting)} (${deleting.employeeCode})? This deactivates the employee, removes linked login accounts and deletes operational attendance, leave, goals, expenses, travel, checklist and document records. Assigned assets become available. Raw punches and historical payroll are retained. Operational deletions cannot be undone.`} onClose={()=>setDeleting(null)} onConfirm={()=>mutate('employees/'+deleting.id,'DELETE')}/>}
  {importing&&<EmployeeImportModal onClose={()=>setImporting(false)}/>}{tasks&&<EmployeeTasksModal employee={tasks} onClose={()=>setTasks(null)}/>}{access&&<EmployeeAppAccessModal employee={access} onClose={()=>setAccess(null)}/>}{photo&&<PhotoViewer {...photo} onClose={()=>setPhoto(null)}/>}
 </div>;
}

function EmployeeEditor({employee,onClose}:{employee:Row;onClose:()=>void}){
 const {can,mutate}=useApp(),data=useData(employee.id?'employees/'+employee.id:'',!!employee.id);
 const row=employee.id?data.data:employee;
 return <Modal title={employee.id?'Edit employee':'Add employee'} onClose={onClose} wide><div className="pd-form-intro"><span><Users size={23}/></span><div><strong>{employee.id?'Keep their story up to date':'Welcome someone new to your team'}</strong><p>Complete the required details. Personal and compliance information can be added later.</p></div></div>{employee.id&&data.isLoading?<Loading/>:employee.id&&data.error?<Failure error={data.error} retry={()=>data.refetch()}/>:row&&<EmployeeRecordForm row={row} onClose={onClose}/>}</Modal>;
}
function EmployeeRecordForm({row,onClose}:{row:Row;onClose:()=>void}){
 const {can,mutate}=useApp(),[snapshot]=useState(row);
 const fields=modules.employees.fields.filter(f=>can('payroll')||!sensitive.has(f.key));
 return <RecordForm fields={fields} initial={snapshot} sections={sections} formClassName="pd-employee-form" submit={snapshot.id?'Save changes':'Create employee'} onCancel={onClose} onSave={async body=>{await mutate('employees'+(snapshot.id?'/'+snapshot.id:''),snapshot.id?'PATCH':'POST',{...body,...(snapshot.id?{expectedUpdatedAt:snapshot.updatedAt}:{})});onClose()}}/>;
}

function EmployeeProfile({employee,onClose,onEdit,onTasks,onAccess,onPhoto}:{employee:Row;onClose:()=>void;onEdit?:(p:Row)=>void;onTasks?:(p:Row)=>void;onAccess?:(p:Row)=>void;onPhoto:(src:string,name:string)=>void}){
 const {can,currency}=useApp(),data=useData('employees/'+employee.id),[tab,setTab]=useState('overview');
 const p=data.data??employee,personal=p.personal??{};
 const tabs=[['overview','Overview'],['personal','Personal & emergency'],...(can('payroll')?[['salary','Salary & bank']]:[]),['compliance','Compliance'],['notes','Skills & notes']];
 const facts=(items:[string,any][])=> <dl className="pd-profile-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value===undefined||value===null||value===''?'Not added':value}</dd></div>)}</dl>;
 return <Modal title="Employee profile" onClose={onClose} wide className="pd-profile-modal"><div className="pd-profile">
  {data.isLoading?<Loading/>:data.error?<Failure error={data.error} retry={()=>data.refetch()}/>:<>
   <header className="pd-profile-head">{p.photo?<button type="button" className="pd-avatar" aria-label={'Open '+fullName(p)+' photo'} onClick={()=>onPhoto(p.photo,fullName(p))}><Avatar large name={fullName(p)} src={p.photo}/></button>:<Avatar large name={fullName(p)}/>}<div><span>{p.employeeCode}</span><h2>{fullName(p)}</h2><p>{p.designation||'Designation not assigned'} · {p.departmentName||'Department not assigned'}</p><Badge value={p.status}/></div></header>
   <div className="pd-profile-actions">{onEdit&&<button type="button" className="btn primary small" onClick={()=>onEdit(p)}><Pencil size={15}/>Edit profile</button>}{onTasks&&<button type="button" className="btn secondary small" onClick={()=>onTasks(p)}><ClipboardCheck size={15}/>Checklists</button>}{onAccess&&<button type="button" className="btn secondary small" onClick={()=>onAccess(p)}><Smartphone size={15}/>Employee App Access</button>}</div>
   <nav className="pd-profile-tabs" aria-label="Employee profile sections">{tabs.map(([key,label])=><button type="button" key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
   <section key={tab} className="pd-profile-section" tabIndex={0} aria-label={tab==='overview'?'Employment details':tabs.find(t=>t[0]===tab)?.[1]}>
    {tab==='overview'&&<><h3>Employment details</h3>{facts([['Employee ID',p.employeeCode],['Email',p.email],['Mobile number',p.phone],['Team',p.teamName],['Department',p.departmentName],['Branch / location',p.branchName],['Assigned shift',p.shiftName],['Reports to',p.managerName||(p.managerId?'Not available':'HR (Company HR)')],['Employment type',human(p.employmentType)],['Joining date',displayDate(p.joiningDate)],['Work location',personal.workLocation],['Shift / roster note',personal.shiftName],['Probation end',personal.probationEnd?displayDate(personal.probationEnd):null],['Confirmation date',personal.confirmationDate?displayDate(personal.confirmationDate):null]])}</>}
    {tab==='personal'&&<><h3>Personal & emergency details</h3>{facts([['Gender',personal.gender?human(personal.gender):null],['Date of birth',personal.dob?displayDate(personal.dob):null],['Blood group',personal.bloodGroup],['Marital status',personal.maritalStatus],['Nationality',personal.nationality],['Residential address',personal.address],['City',personal.city],['State',personal.state],['PIN code',personal.pincode],['Emergency contact name',personal.emergencyContact],['Emergency contact phone',personal.emergencyPhone]])}</>}
    {tab==='salary'&&can('payroll')&&<><div className="pd-salary-banner"><Wallet size={22}/><div><span>MONTHLY PROFILE SALARY</span><strong>{p.monthlySalary==null?'Not added':currencyValue(p.monthlySalary,currency)}</strong></div></div><h3>Bank details</h3>{facts([['Bank name',personal.bankName],['Account holder name',personal.accountHolder],['Bank account number',personal.accountNumber],['IFSC',personal.ifsc],['Bank branch',personal.bankBranch]])}<p className="pd-profile-note">Effective salary revisions and manual monthly payroll amounts are managed in Payroll.</p>{can('payroll','MANAGE')&&<Link className="btn secondary small" href={'/payroll?tab=structures&employeeCode='+encodeURIComponent(p.employeeCode)}>Open salary structures <ArrowUpRight size={15}/></Link>}</>}
    {tab==='compliance'&&<><h3>Compliance identifiers</h3>{facts([['Aadhaar number',personal.aadhaar],['PAN',personal.pan],['UAN',personal.uan],['PF number',personal.pfNumber],['ESIC number',personal.esicNumber]])}</>}
    {tab==='notes'&&<><h3>Qualifications & HR notes</h3>{facts([['Qualification',personal.qualification],['Previous experience',personal.experience],['Skills',personal.skills],['HR notes',personal.notes]])}</>}
   </section><footer className="pd-profile-footer"><ShieldCheck size={14}/><span>{p.updatedAt?'Updated '+displayDate(p.updatedAt):'Employee master record'}</span></footer>
  </>}
 </div></Modal>;
}
