'use client';
import React,{useState,useEffect} from 'react';
import {Target,Plus,Search,RefreshCw,CheckCircle2,Clock3,TrendingUp,CalendarDays,Pencil,Trash2,ChevronLeft,ChevronRight,ArrowUpRight} from 'lucide-react';
import {useApp,useData,Avatar,Badge,Modal,RecordForm,Confirm,Loading,Failure,Empty,displayDate} from './core';
import {modules,Row} from './config';
import './performance.css';
const PAGE_SIZE=12;
const nameOf=(person:Row|undefined)=>person?`${person.firstName??''} ${person.lastName??''}`.trim()||'Employee':'Employee';
const percent=(row:Row)=>Math.max(0,Math.min(100,Math.round(Number(row.progress||0)/Math.max(1,Number(row.target||1))*100)));
export function PerformanceDashboard(){
 const {session,can,mutate}=useApp();
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[employeeId,setEmployeeId]=useState(''),[sort,setSort]=useState('recent'),[overdue,setOverdue]=useState(false),[page,setPage]=useState(1);
 const [edit,setEdit]=useState<Row|null|undefined>(),[selected,setSelected]=useState<Row|null>(null),[remove,setRemove]=useState<Row|null>(null);
 const restricted=['EMPLOYEE','MANAGER','TEAM_LEADER'].includes(session.user.role);
 const canCreate=can('performance','CREATE')&&!restricted,canEdit=can('performance','EDIT')&&!restricted,canDelete=can('performance','DELETE')&&!restricted;
 const query=new URLSearchParams({q:search,status,employeeId,sort,overdue:overdue?'1':'0',page:String(page),pageSize:String(PAGE_SIZE)});
 const goals=useData('goals?'+query),employees=useData('employees?pageSize=500',can('employees'));
 const rows:Row[]=goals.data?.items??[],people:Row[]=employees.data?.items??[],summary=goals.data?.summary;
 const person=(row:Row)=>row.employee??people.find(p=>p.id===row.employeeId);
 const total=Number(goals.data?.total??rows.length),pages=Math.max(1,Math.ceil(total/PAGE_SIZE));
 useEffect(()=>{if(goals.data&&!goals.isFetching)setPage(p=>Math.min(p,pages))},[goals.data,goals.isFetching,pages]);
 useEffect(()=>{if(selected){const fresh=rows.find(r=>r.id===selected.id);if(fresh)setSelected(fresh)}},[goals.data]);
 const reset=()=>{setSearch('');setStatus('');setEmployeeId('');setSort('recent');setOverdue(false);setPage(1)};
 const change=(fn:()=>void)=>{fn();setPage(1)};
 const add=()=>setEdit(null);
 return <div className="performance-workspace">
  <header className="performance-hero"><div><span className="performance-eyebrow"><Target size={15}/>GROWTH & ACHIEVEMENT</span><h1>Performance</h1><p>Give every goal a clear owner, measurable target and finish date.</p></div><div className="performance-hero-actions"><button className="btn secondary" disabled={goals.isFetching} onClick={()=>void goals.refetch()}><RefreshCw size={16}/>Refresh</button>{canCreate&&<button className="btn primary" onClick={add}><Plus size={18}/>Create goal</button>}</div></header>
  <div className="performance-stats">{[{label:'Total goals',value:summary?.total,icon:Target,tone:'blue',note:'Across your accessible team'},{label:'Active goals',value:summary?.active,icon:TrendingUp,tone:'sky',note:'Work in progress'},{label:'Completed',value:summary?.completed,icon:CheckCircle2,tone:'green',note:'Targets reached'},{label:'Overdue',value:summary?.overdue,icon:Clock3,tone:'amber',note:'Active goals past their due date'}].map(card=><article key={card.label} className={'performance-stat '+card.tone}><span><card.icon size={21}/></span><div><small>{card.label}</small><strong>{card.value??'—'}</strong><p>{card.note}</p></div></article>)}</div>
  <section className="performance-library"><div className="performance-library-head"><div><span className="performance-eyebrow">GOAL LIBRARY</span><h2>{restricted?'Your accessible goals':'Team goals'}</h2><p>Track real progress against each goal’s target.</p></div><div role="tablist" aria-label="Goal status" className="performance-tabs">{[['','All goals'],['ACTIVE','Active'],['COMPLETED','Completed'],['CANCELLED','Cancelled']].map(([value,label])=><button role="tab" aria-selected={status===value&&!overdue} key={value} onClick={()=>change(()=>{setStatus(value);setOverdue(false)})}>{label}</button>)}</div></div>
  <div className="performance-filters"><label className="performance-search"><Search size={17}/><input aria-label="Search goal titles" placeholder="Search goal titles…" value={search} onChange={e=>change(()=>setSearch(e.target.value))}/></label><label><span>Owner</span><select aria-label="Filter goal owner" value={employeeId} onChange={e=>change(()=>setEmployeeId(e.target.value))}><option value="">All accessible employees</option>{people.map(p=><option key={p.id} value={p.id}>{nameOf(p)} · {p.employeeCode}</option>)}</select></label><label><span>Sort</span><select aria-label="Sort goals" value={sort} onChange={e=>change(()=>setSort(e.target.value))}><option value="recent">Newest first</option><option value="due">Due date first</option></select></label><button className={'performance-overdue '+(overdue?'active':'')} aria-pressed={overdue} onClick={()=>change(()=>{setOverdue(v=>!v);setStatus('')})}><Clock3 size={15}/>Overdue only</button><button className="text-button" onClick={reset}>Reset filters</button></div>
  {goals.isLoading?<Loading/>:goals.error?<Failure error={goals.error as Error} retry={()=>goals.refetch()}/>:!rows.length?<Empty title={search||status||employeeId||overdue?'No matching goals':'Make your first goal measurable'} description={search||status||employeeId||overdue?'Reset the filters to see your other goals.':'Choose an employee, define a target and set a due date.'} action={search||status||employeeId||overdue?<button className="btn secondary" onClick={reset}>Clear filters</button>:canCreate?<button className="btn primary" onClick={add}><Plus size={17}/>Create goal</button>:undefined}/>:<div className="performance-grid">{rows.map(row=><article key={row.id} className={'performance-goal '+(row.overdue?'is-overdue':'')}><div className="performance-goal-top"><span className="performance-goal-icon"><Target size={20}/></span><Badge value={row.status}/></div><button className="performance-goal-title" onClick={()=>setSelected(row)}>{row.title}<ArrowUpRight size={17}/></button><div className="performance-owner"><Avatar name={nameOf(person(row))} src={person(row)?.photo}/><span><strong>{nameOf(person(row))}</strong><small>{person(row)?.designation??person(row)?.employeeCode??''}</small></span></div><div className="performance-progress"><div><span>Target progress</span><strong>{percent(row)}%</strong></div><progress aria-label={'Progress for '+row.title} max={Number(row.target)||1} value={Number(row.progress)||0}/><small>{Number(row.progress)} of {Number(row.target)} units</small></div><div className="performance-goal-foot"><span className={row.overdue?'overdue':''}><CalendarDays size={14}/>{displayDate(row.dueDate)}{row.overdue&&<b>Overdue</b>}</span><button className="text-button" onClick={()=>setSelected(row)} aria-label={'View '+row.title}>Details<ChevronRight size={15}/></button></div>{(canEdit||canDelete)&&<div className="performance-card-actions">{canEdit&&<button className="btn secondary small" aria-label={'Edit '+row.title} onClick={()=>setEdit(row)}><Pencil size={14}/>Update goal</button>}{canDelete&&<button className="icon-button" aria-label={'Delete '+row.title} onClick={()=>setRemove(row)}><Trash2 size={15}/></button>}</div>}</article>)}</div>}
  <footer className="performance-pagination"><span>{total?`Showing ${(page-1)*PAGE_SIZE+1}–${Math.min(page*PAGE_SIZE,total)} of ${total} goals`:'No goals in this view'}</span><div><button className="icon-button" aria-label="Previous goal page" disabled={page===1||goals.isFetching} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>Page {page} of {pages}</span><button className="icon-button" aria-label="Next goal page" disabled={page>=pages||goals.isFetching} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></footer>
  </section>
  {selected&&<Modal title="Goal details" onClose={()=>setSelected(null)}><div className="performance-detail"><div className="performance-goal-top"><Badge value={selected.status}/>{selected.overdue&&<span className="performance-overdue active">Overdue</span>}</div><h3>{selected.title}</h3><div className="performance-owner"><Avatar large name={nameOf(person(selected))} src={person(selected)?.photo}/><span><strong>{nameOf(person(selected))}</strong><small>{person(selected)?.employeeCode}</small></span></div><div className="performance-detail-progress"><strong>{percent(selected)}%</strong><span>{Number(selected.progress)} / {Number(selected.target)} units</span><progress max={Number(selected.target)||1} value={Number(selected.progress)||0}/></div><dl><dt>Due date</dt><dd>{displayDate(selected.dueDate)}</dd><dt>Created</dt><dd>{displayDate(selected.createdAt)}</dd><dt>Last updated</dt><dd>{displayDate(selected.updatedAt)}</dd></dl>{canEdit&&<button className="btn primary" onClick={()=>{setEdit(selected);setSelected(null)}}><Pencil size={16}/>Update goal</button>}</div></Modal>}
  {edit!==undefined&&<Modal title={edit?'Update goal':'Create goal'} wide onClose={()=>setEdit(undefined)}><RecordForm formClassName="performance-goal-form" fields={modules.goals.fields.map(f=>f.key==='progress'?{...f,hint:'Completed goals must reach their target. Progress cannot exceed the target.'}:f)} initial={edit??{status:'ACTIVE',target:100,progress:0}} sections={[{title:'Ownership & objective',description:'Assign one clear owner and describe the outcome.',keys:['employeeId','title']},{title:'Measure & schedule',description:'Use the same unit for target and progress. Completed goals must reach the target.',keys:['target','progress','dueDate','status']}]} onCancel={()=>setEdit(undefined)} onSave={async body=>{await mutate('goals'+(edit?'/'+edit.id:''),edit?'PATCH':'POST',{...body,...(edit?.updatedAt?{expectedUpdatedAt:edit.updatedAt}:{})});setEdit(undefined)}} submit={edit?'Save changes':'Create goal'}/></Modal>}
  {remove&&<Confirm title="Delete goal?" description={'Delete “'+remove.title+'”? This permanently removes the goal and its progress.'} onClose={()=>setRemove(null)} onConfirm={async()=>{await mutate('goals/'+remove.id,'DELETE');if(selected?.id===remove.id)setSelected(null);setRemove(null)}}/>}
 </div>;
}
