'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Fingerprint,ShieldCheck} from 'lucide-react';
import {api,useApp,useData,Failure,Loading} from './core';
import {freshLocation,LocationAccessError} from './location';
import {LocationHelp} from './location-help';
function bridge(){return typeof window==='undefined'?undefined:(window as any).TCWBiometric;}
const requests=new Map<string,{resolve:(v:any)=>void;reject:(e:Error)=>void;timer:number}>();
function request(action:string,data:any={}){const native=bridge();if(!native?.postMessage)return Promise.reject(new Error('Install the latest TCW Employee APK to use phone biometrics.'));
 native.onmessage=(event:any)=>{try{const response=JSON.parse(event.data),pending=requests.get(response.id);if(!pending)return;requests.delete(response.id);clearTimeout(pending.timer);response.error?pending.reject(new Error(response.error)):pending.resolve(response.result);}catch{}};
 return new Promise<any>((resolve,reject)=>{const id=crypto.randomUUID(),timer=window.setTimeout(()=>{requests.delete(id);reject(new Error('Phone verification timed out. Retry.'));native.postMessage(JSON.stringify({id:crypto.randomUUID(),action:'cancel'}));},100000);requests.set(id,{resolve,reject,timer});try{native.postMessage(JSON.stringify({id,action,...data}));}catch(e){clearTimeout(timer);requests.delete(id);reject(new Error('Phone biometric service is unavailable. Reopen the app.'));}});
}
function cancel(){bridge()?.postMessage(JSON.stringify({id:crypto.randomUUID(),action:'cancel'}));}
export function hasPhoneBiometric(){return !!bridge()?.postMessage;}
export function PhoneBiometricFlow({intent,onClose,onComplete,onCamera}:{intent:'IN'|'OUT';onClose:()=>void;onComplete?:(result:any)=>void|Promise<any>;onCamera:()=>void}){
 const{session}=useApp(),devices=useData('attendance/biometric-device'),field=useData('field-work/session',intent==='IN'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[completed,setCompleted]=useState(false),[error,setError]=useState(''),[locationError,setLocationError]=useState(false),[message,setMessage]=useState('Use the face or fingerprint enrolled on this phone.'),[supported,setSupported]=useState<boolean|null>(null),mounted=useRef(true),lock=useRef(false);
 useEffect(()=>{mounted.current=true;request('status').then(r=>{if(mounted.current)setSupported(!!r.supported)}).catch(e=>{if(mounted.current){setSupported(false);setError(e.message)}});return()=>{mounted.current=false;cancel()}},[]);
 async function run(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setLocationError(false);try{
  if(devices.isLoading||devices.error||(intent==='IN'&&(field.isLoading||field.error)))throw new Error('Attendance requirements could not load. Retry.');
  if(intent==='IN'&&field.data?.eligible){if(!consent)throw new Error('Agree to on-duty location sharing first.');setMessage('Checking precise GPS…');const point=await freshLocation();if(point.accuracy>Number(field.data.policy.maxAccuracyMeters))throw new LocationAccessError('UNAVAILABLE',`GPS accuracy must be within ${field.data.policy.maxAccuracyMeters} metres.`);}
  if(!mounted.current)return;
  const deviceData=devices.data;if(!deviceData)throw new Error('Phone details could not load. Refresh approval.');
  // Public key lookup identifies this device without opening a second biometric dialog.
  const local=await request('key',{accountKey:deviceData.accountKey});if(!mounted.current)return;
  let device:any;
  if(local.publicKey){const bytes=Uint8Array.from(atob(local.publicKey),(c:string)=>c.charCodeAt(0)),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join('');device=deviceData.items?.find((d:any)=>d.keyHash===hash);}
  if(!device){
   setMessage('Link this phone with your biometrics…');const challenge:any=await api('attendance/biometric-challenge','POST',{purpose:'REGISTER',intent},session.csrf);if(!mounted.current)return;
   const signed=await request('sign',{accountKey:challenge.accountKey,payload:challenge.payload,register:true});if(!mounted.current)return;
   const registered:any=await api('attendance/biometric-device','POST',{challengeId:challenge.challengeId,signature:signed.signature,publicKey:signed.publicKey,label:'Employee phone',intent},session.csrf);if(!mounted.current)return;await devices.refetch();setMessage(registered.status==='APPROVED'?'Phone approved. Tap Verify to check attendance.':'Phone linked. Ask HR to approve it in Field work → Face approvals → Phone biometrics.');return;
  }
  if(device.status!=='APPROVED'){await devices.refetch();setMessage('This phone is awaiting HR approval. Ask HR to approve it in Field work → Face approvals → Phone biometrics.');return;}
  setMessage('Verify with your phone…');const punch:any=await api('attendance/biometric-challenge','POST',{purpose:'PUNCH',intent,deviceId:device.id},session.csrf);if(!mounted.current)return;
  const proof=await request('sign',{accountKey:punch.accountKey,payload:punch.payload,register:false});if(!mounted.current)return;
  const point=intent==='IN'&&field.data?.eligible?await freshLocation():null;if(!mounted.current)return;
  setMessage('Saving attendance…');const result:any=await api('attendance/biometric-scan','POST',{challengeId:punch.challengeId,signature:proof.signature,intent,clientNonce:crypto.randomUUID(),...(point?{point,locationConsent:consent}:{})},session.csrf);if(!mounted.current)return;setCompleted(true);
  window.dispatchEvent(new Event('tcw-field-session'));setMessage(result.punchType==='IN'?'Checked in — working timer started':'Checked out — work session closed');try{await onComplete?.(result);}catch{setMessage('Attendance saved. Refresh to see your latest status.');}window.setTimeout(()=>{if(mounted.current)onClose()},650);
 }catch(e:any){if(mounted.current){setError(e.message||'Phone verification failed.');setLocationError(e instanceof LocationAccessError);}}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 const blocked=completed||busy||supported!==true||devices.isLoading||!!devices.error||(intent==='IN'&&(field.isLoading||!!field.error))||(intent==='IN'&&field.data?.eligible&&!consent);
 return <div className="face-scan-modal phone-biometric-flow"><div className="phone-biometric-mark"><Fingerprint size={60}/><h2>Phone biometric verification</h2><p>Use your phone’s face or fingerprint. No three-pose camera scan is needed.</p></div>{intent==='IN'&&field.data?.eligible&&<label className="face-location-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/><span>I agree to share my location during field duty. Keep precise location on until Check OUT.</span></label>}{devices.isLoading||field.isLoading?<Loading/>:devices.error||field.error?<Failure error={(devices.error||field.error)!}/>:null}<div className="face-scan-status" role={error?'alert':'status'}><ShieldCheck size={20}/><div><strong>{error?'Phone verification needs attention':'Verify on your phone'}</strong><p>{error||message}</p>{supported===false&&<p>This phone needs a supported strong biometric enrolled in phone settings. You can use camera verification instead.</p>}</div></div>{locationError&&<LocationHelp/>}<button className="btn secondary small" disabled={busy} onClick={()=>{void devices.refetch();void field.refetch()}}>Refresh approval</button><p>First-time phone setup needs HR approval. Anyone enrolled in this phone’s biometrics can unlock its TCW key; use your own phone.</p><button className="btn secondary" disabled={busy} onClick={onCamera}>Use camera verification</button><div className="face-scan-actions"><button className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={blocked} onClick={run}><Fingerprint size={18}/>{busy?'Verifying…':'Verify with phone'}</button></div></div>;
}
export function PhoneBiometricReviewPanel(){const{session}=useApp(),q=useData('attendance/biometric-review'),[confirmed,setConfirmed]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');async function review(row:any,decision:'APPROVE'|'REVOKE'){setBusy(true);setError('');try{await api('attendance/biometric-review','POST',{deviceId:row.id,decision,expectedUpdatedAt:row.updatedAt,identityConfirmed:true},session.csrf);await q.refetch();}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <section className="field-face-panel"><div className="panel"><h2>Phone biometrics</h2><p>Verify the employee and their own phone before approving. Phone biometrics authenticate anyone enrolled on that phone, rather than comparing their face with the HR photo.</p>{error&&<p role="alert">{error}</p>}</div>{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<div className="field-face-reviews">{q.data.items.map((r:any)=><article className="panel" key={r.id}><strong>{r.employee.firstName} {r.employee.lastName} · {r.employee.employeeCode}</strong><p>{r.label} · {r.status}</p><small>Key: {r.keyHash.slice(0,16)}</small><label className="field-consent"><input type="checkbox" checked={!!confirmed[r.id]} onChange={e=>setConfirmed({...confirmed,[r.id]:e.target.checked})}/>I checked this employee and their phone.</label><div className="field-actions">{r.status==='PENDING'&&<button className="btn primary" disabled={busy||!confirmed[r.id]} onClick={()=>review(r,'APPROVE')}>Approve phone</button>}<button className="btn secondary" disabled={busy||!confirmed[r.id]} onClick={()=>review(r,'REVOKE')}>Revoke phone</button></div></article>)}</div>:<div className="panel">No phones awaiting approval.</div>}</section>}
