'use client';
import React,{useEffect,useState} from 'react';
import {Plus,Upload,Download,FileText,ShieldCheck,LogOut,Send,Printer,Pencil,Eye,Check,Bell,Trash2,Sparkles,KeyRound,RefreshCw,Search,Clock3,AlertTriangle,Building2,UserCircle} from 'lucide-react';
import {useApp,useData,api,PageTitle,Table,Modal,RecordForm,Confirm,Loading,Failure,Empty,Badge,displayDate,currencyValue} from './core';
import {Row,Field,readable} from './config';
export function CompanySettings(){
 const q=useData('company');const{mutate,can,notify}=useApp();const[logo,setLogo]=useState<string|null|undefined>(undefined),[saved,setSaved]=useState(false);
 const fields:Field[]=[{key:'name',label:'Company name',required:true},{key:'legalName',label:'Legal name'},{key:'industry',label:'Industry'},{key:'website',label:'Website',type:'url'},{key:'email',label:'Company email',type:'email'},{key:'phone',label:'Phone'},{key:'address',label:'Address',type:'textarea'},{key:'city',label:'City'},{key:'state',label:'State'},{key:'country',label:'Country'},{key:'postalCode',label:'Postal code'},{key:'taxId',label:'GST / Tax ID'},{key:'pan',label:'PAN'},{key:'currency',label:'Currency code',required:true},{key:'timezone',label:'Timezone',required:true},{key:'financialYear',label:'Financial year'},{key:'dateFormat',label:'Date format'},{key:'supportEmail',label:'Support email',type:'email'},{key:'footer',label:'Document footer'},{key:'primaryColor',label:'Brand color',type:'color'},{key:'salaryDay',label:'Monthly salary processing day',type:'number',required:true,default:1,min:1,max:31,hint:'Automatic payroll preparation runs on this day (or the last day of shorter months).'},{key:'autoPayroll',label:'Automatically prepare payroll',type:'checkbox',default:false},{key:'payoutProvider',label:'Salary payout method',type:'select',required:true,default:'NONE',options:['NONE','BANK_FILE','RAZORPAYX'],hint:'BANK_FILE exports an approved bank CSV. RAZORPAYX enables guarded live salary payouts when server credentials are configured.'},{key:'payoutMode',label:'Default live payout mode',type:'select',required:true,default:'IMPS',options:['IMPS','NEFT','RTGS']},{key:'payoutAccountLabel',label:'Payout account / label',hint:'Friendly label only. Never store payout API secrets here.'}];
 if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;
 const company=q.data!;
 return <><PageTitle title="Company settings" subtitle="Manage your company details, workspace logo, brand color, payroll preferences, and operating settings."/><div className="panel settings-panel"><div className="brand-upload"><div className="company-logo">{(logo??company.logo)?<img src={logo??company.logo} alt={company.name+' logo'}/>:<span>{String(company.name??'Company').split(/\s+/).filter(Boolean).slice(0,2).map((v:string)=>v[0]?.toUpperCase()).join('')||'CO'}</span>}</div><div><h3>Company workspace logo</h3><p>Upload a PNG or JPEG up to 5 MB. This logo appears for your company inside TCW HR. The main TCW HR Software / Tech Cyber Warrior product logo is platform branding and is not changed here.</p>{can('company','EDIT')&&<div className="brand-actions"><label className="btn secondary small"><Upload size={16}/>Change company logo<input type="file" accept="image/png,image/jpeg" className="sr-only" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){notify('Choose a logo up to 5 MB.',true);return;}const reader=new FileReader();reader.onload=()=>setLogo(String(reader.result));reader.readAsDataURL(file)}}/></label>{(logo??company.logo)&&<button type="button" className="btn secondary small" onClick={()=>setLogo(null)}><Trash2 size={15}/>Remove company logo</button>}</div>}</div></div><RecordForm fields={fields} initial={{...company,...company.profile,primaryColor:company.profile?.primaryColor??'#3474ef'}} onCancel={()=>{setLogo(undefined);q.refetch()}} submit="Save company profile" onSave={async body=>{if(!can('company','EDIT'))throw new Error('You do not have permission to edit company settings.');const{name,currency,timezone,...profile}=body;await mutate('company','PATCH',{name,currency,timezone,profile,logo:logo===undefined?company.logo:logo});setSaved(true)}}/>{saved&&<p className="saved-note">Company profile saved.</p>}</div></>;
}
export function UsersPage(){
 const q=useData('users'),roles=useData('roles');const{mutate}=useApp();const[edit,setEdit]=useState<Row|null|undefined>(undefined),[roleView,setRoleView]=useState<Row|null>(null),[credentials,setCredentials]=useState<Row|null>(null);
 const fields:Field[]=[{key:'name',label:'Full name',required:true,hint:'Enter the user’s full name as it should appear in TCW HR.'},{key:'email',label:'Email address',type:'email',required:true,hint:'Used for account recovery and important notifications.'},{key:'loginId',label:'User ID',hint:'Optional. Leave blank and TCW HR will generate a short ID such as TCW2104.'},{key:'password',label:edit?'New password':'Temporary password',type:'password',required:false,hint:edit?'Optional. Leave blank to keep the current password.':'Optional. Leave blank to generate a secure 8-character temporary password. If delivery is configured, login details can be sent by email or SMS.'},{key:'role',label:'Role',type:'select',required:true,options:roles.data?.items?.map((r:Row)=>r.code)??[],hint:'Choose the role that matches this user’s responsibilities.'},{key:'employeeId',label:'Linked employee',source:'employees',type:'select',required:false,hint:'Optional. Link an employee so the account is connected to that employee record and mobile number.'},{key:'active',label:'Active account',type:'checkbox',default:true,hint:'Turn this off to block sign-in without deleting the user.'}];
 return <><PageTitle title="Users & roles" subtitle="Create user accounts, assign the right role, and link employee records when needed."><button className="btn primary" onClick={()=>setEdit(null)}><Plus size={18}/>Add user</button></PageTitle><div className="panel">{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:<Table columns={['name','email','loginId','role','active']} rows={q.data?.items??[]} cell={(r,k)=>k==='role'?<button className="text-button" onClick={()=>setRoleView(roles.data?.items?.find((v:Row)=>v.code===r.role.code))}>{r.role.name}</button>:k==='active'?<Badge value={r.active?'ACTIVE':'INACTIVE'}/>:undefined} actions={r=><button className="icon-button" aria-label={'Edit '+r.name} onClick={()=>setEdit({...r,role:r.role.code})}><Pencil size={16}/></button>}/>}</div>{edit!==undefined&&<Modal title={edit?'Edit user':'Add user'} onClose={()=>setEdit(undefined)}><RecordForm fields={fields} initial={edit??undefined} onCancel={()=>setEdit(undefined)} onSave={async body=>{if(!body.password)delete body.password;if(!body.loginId)delete body.loginId;const result=await mutate('users'+(edit?'/'+edit.id:''),edit?'PATCH':'POST',body);setEdit(undefined);if(!edit&&result?.temporaryPassword)setCredentials({name:result.name,email:result.email,loginId:result.loginId,temporaryPassword:result.temporaryPassword})}}/></Modal>}{credentials&&<Modal title="User login created" onClose={()=>setCredentials(null)}><div className="modal-body credential-sheet"><p>Save these temporary credentials now. The password is only shown once. If a linked employee mobile number is available, an SMS is queued automatically; email is queued as well.</p><div className="profile-grid"><div><span>User</span><strong>{credentials.name}</strong></div><div><span>User ID</span><strong>{credentials.loginId}</strong></div><div><span>Email</span><strong>{credentials.email}</strong></div><div><span>Temporary password</span><strong className="mono-secret">{credentials.temporaryPassword}</strong></div></div><button className="btn primary" type="button" onClick={()=>navigator.clipboard?.writeText(`User ID: ${credentials.loginId}\nTemporary Password: ${credentials.temporaryPassword}\nEmail: ${credentials.email}`)}>Copy login details</button></div></Modal>}{roleView&&<Modal title={roleView.name+' permissions'} onClose={()=>setRoleView(null)}><div className="modal-body permissions-grid">{roleView.permissions.map((p:string)=><span key={p}><Check size={14}/>{readable(p.replace(':',' · '))}</span>)}</div></Modal>}</>;
}
export function PlatformProfilePage(){
 const company=useData('system/platform-profile'),account=useData('auth/profile');const{session,notify}=useApp();
 const[companyForm,setCompanyForm]=useState<Row>({}),[accountForm,setAccountForm]=useState<Row>({}),[logo,setLogo]=useState<string|null|undefined>(undefined),[savingCompany,setSavingCompany]=useState(false),[savingAccount,setSavingAccount]=useState(false);
 useEffect(()=>{if(company.data)setCompanyForm({companyName:company.data.companyName??'Tech Cyber Warrior',legalName:company.data.legalName??'',email:company.data.email??'',phone:company.data.phone??'',website:company.data.website??'',address:company.data.address??'',city:company.data.city??'',state:company.data.state??'',country:company.data.country??'',postalCode:company.data.postalCode??'',taxId:company.data.taxId??'',pan:company.data.pan??'',supportEmail:company.data.supportEmail??''})},[company.data]);
 useEffect(()=>{if(account.data?.user)setAccountForm({name:account.data.user.name??'',email:account.data.user.email??''})},[account.data]);
 const currentLogo=logo===undefined?(company.data?.logo??'/tcw-logo.png'):logo;
 async function saveCompany(e:React.FormEvent){e.preventDefault();setSavingCompany(true);try{await api('system/platform-profile','PUT',{...companyForm,logo:currentLogo},session.csrf);setLogo(undefined);await company.refetch();notify('Super Admin company profile saved.')}catch(e:any){notify(e.message,true)}finally{setSavingCompany(false)}}
 async function saveAccount(e:React.FormEvent){e.preventDefault();setSavingAccount(true);try{await api('auth/profile','PATCH',accountForm,session.csrf);await account.refetch();notify('Super Admin profile saved.');setTimeout(()=>window.location.reload(),350)}catch(e:any){notify(e.message,true)}finally{setSavingAccount(false)}}
 function updateCompany(key:string,value:any){setCompanyForm(v=>({...v,[key]:value}))}
 return <><PageTitle title="Company & admin profile" subtitle="Manage Tech Cyber Warrior platform identity and your Super Admin account. Customer company profiles are not changed from this page."/>
 <div className="platform-profile-grid">
  <section className="panel platform-company-profile"><div className="panel-heading"><div><h2>Tech Cyber Warrior company profile</h2><p>Main company details used for the Super Admin platform identity.</p></div><Building2 size={21}/></div>
   {company.isLoading?<Loading/>:company.error?<Failure error={company.error}/>:<form onSubmit={saveCompany}>
    <div className="platform-profile-logo"><div className="platform-profile-logo-preview">{currentLogo?<img src={currentLogo} alt="Tech Cyber Warrior logo"/>:<span>TCW</span>}</div><div><strong>Main company logo</strong><p>This logo is used across the HR and Super Admin product branding.</p><div className="platform-profile-logo-actions"><label className="btn secondary small"><Upload size={15}/>Change logo<input className="sr-only" type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){notify('Choose a PNG or JPEG logo up to 5 MB.',true);return;}const reader=new FileReader();reader.onload=()=>setLogo(String(reader.result));reader.readAsDataURL(file)}}/></label><button type="button" className="btn secondary small" onClick={()=>setLogo('/tcw-logo.png')}><RefreshCw size={15}/>Reset logo</button></div></div></div>
    <div className="platform-profile-fields">
     <label><span>Company name</span><input required value={companyForm.companyName??''} onChange={e=>updateCompany('companyName',e.target.value)}/></label>
     <label><span>Legal name</span><input value={companyForm.legalName??''} onChange={e=>updateCompany('legalName',e.target.value)}/></label>
     <label><span>Company email</span><input type="email" value={companyForm.email??''} onChange={e=>updateCompany('email',e.target.value)}/></label>
     <label><span>Phone</span><input value={companyForm.phone??''} onChange={e=>updateCompany('phone',e.target.value)}/></label>
     <label><span>Website</span><input type="url" value={companyForm.website??''} onChange={e=>updateCompany('website',e.target.value)}/></label>
     <label><span>Support email</span><input type="email" value={companyForm.supportEmail??''} onChange={e=>updateCompany('supportEmail',e.target.value)}/></label>
     <label className="span-two"><span>Address</span><textarea rows={3} value={companyForm.address??''} onChange={e=>updateCompany('address',e.target.value)}/></label>
     <label><span>City</span><input value={companyForm.city??''} onChange={e=>updateCompany('city',e.target.value)}/></label>
     <label><span>State</span><input value={companyForm.state??''} onChange={e=>updateCompany('state',e.target.value)}/></label>
     <label><span>Country</span><input value={companyForm.country??''} onChange={e=>updateCompany('country',e.target.value)}/></label>
     <label><span>Postal code</span><input value={companyForm.postalCode??''} onChange={e=>updateCompany('postalCode',e.target.value)}/></label>
     <label><span>GST / Tax ID</span><input value={companyForm.taxId??''} onChange={e=>updateCompany('taxId',e.target.value)}/></label>
     <label><span>PAN</span><input value={companyForm.pan??''} onChange={e=>updateCompany('pan',e.target.value)}/></label>
    </div>
    <div className="form-footer"><button className="btn primary" disabled={savingCompany}>{savingCompany?'Saving…':'Save company profile'}</button></div>
   </form>}
  </section>
  <section className="panel platform-admin-profile"><div className="panel-heading"><div><h2>Super Admin profile</h2><p>Your own platform administrator identity.</p></div><UserCircle size={21}/></div>
   {account.isLoading?<Loading/>:account.error?<Failure error={account.error}/>:<form onSubmit={saveAccount}><div className="platform-admin-card"><div className="platform-admin-avatar">{String(accountForm.name??'SA').split(/\s+/).filter(Boolean).slice(0,2).map((v:string)=>v[0]?.toUpperCase()).join('')}</div><div><strong>{accountForm.name||'Super Admin'}</strong><small>{session.user.loginId??session.user.email} · {session.user.roleName}</small></div></div><div className="platform-profile-fields single"><label><span>Full name</span><input required value={accountForm.name??''} onChange={e=>setAccountForm(v=>({...v,name:e.target.value}))}/></label><label><span>Email address</span><input type="email" required value={accountForm.email??''} onChange={e=>setAccountForm(v=>({...v,email:e.target.value}))}/></label></div><div className="form-footer"><a className="btn secondary" href="/security">Password & sessions</a><button className="btn primary" disabled={savingAccount}>{savingAccount?'Saving…':'Save admin profile'}</button></div></form>}
  </section>
 </div></>;
}
export function SecurityPage(){
 const{mutate,session}=useApp();const q=useData('auth/sessions');const[revoke,setRevoke]=useState<Row|null>(null),[formKey,setFormKey]=useState(0);
 return <><PageTitle title="My security" subtitle="Manage your password and signed-in sessions."/><div className="settings-grid"><section className="panel"><div className="panel-heading"><h2>Change password</h2><ShieldCheck size={20}/></div><RecordForm key={formKey} fields={[{key:'currentPassword',label:'Current password',type:'password',required:true},{key:'password',label:'New password',type:'password',required:true,hint:'At least 8 characters with uppercase, lowercase, number and symbol.'}]} onCancel={()=>setFormKey(v=>v+1)} onSave={async body=>{await mutate('auth/change-password','POST',body);window.location.assign(session.user.scope==='PLATFORM'?'/admin-login':'/login')}} submit="Change password"/></section><section className="panel"><div className="panel-heading"><h2>Active sessions</h2></div>{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.map((r:Row)=><div className="session-row" key={r.id}><div><strong>{r.userAgent.slice(0,90)||'Unknown device'}</strong><small>{r.ip} · {displayDate(r.createdAt)}</small>{r.id===q.data?.currentId&&<Badge value="CURRENT"/>}</div><button className="icon-button" title="Revoke session" aria-label="Revoke session" onClick={()=>setRevoke(r)}><LogOut size={18}/></button></div>)}</section></div>{revoke&&<Confirm title="Revoke this session?" description="This device will need to sign in again." onClose={()=>setRevoke(null)} onConfirm={async()=>{await mutate('auth/sessions/'+revoke.id,'DELETE');if(revoke.id===q.data?.currentId)window.location.assign(session.user.scope==='PLATFORM'?'/admin-login':'/login')}}/>}</>;
}
export function DocumentsPage(){
 const q=useData('documents');const{can,mutate}=useApp();const[open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null);
 return <><PageTitle title="Document center" subtitle="Secure company and employee documents in one place.">{can('documents','CREATE')&&<button className="btn primary" onClick={()=>setOpen(true)}><Upload size={17}/>Upload document</button>}</PageTitle><div className="panel">{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<Table columns={['title','category','fileName','size','createdAt']} rows={q.data.items} cell={(r,k)=>k==='size'?`${(r.size/1024).toFixed(1)} KB`:k==='createdAt'?displayDate(r.createdAt):undefined} actions={r=><a className="icon-button" href={'/api/documents/'+r.id} aria-label={'Download '+r.title}><Download size={17}/></a>}/>:<Empty title="A home for your documents" description="Upload PDF, PNG, or JPEG files up to 10 MB."/>}</div>{open&&<Modal title="Upload document" onClose={()=>setOpen(false)}><div className="modal-body upload-zone"><FileText size={28}/><label>Choose PDF, PNG, or JPEG<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]??null)}/></label></div><RecordForm fields={[{key:'title',label:'Document title',required:true},{key:'category',label:'Category',required:true},{key:'employeeId',label:'Employee (optional)',type:'select',source:'employees',required:false}]} onCancel={()=>setOpen(false)} onSave={async body=>{if(!file)throw new Error('Choose a file to upload.');const form=new FormData();form.append('file',file);Object.entries(body).forEach(([k,v])=>{if(v)form.append(k,String(v))});await mutate('documents','POST',form);setOpen(false);setFile(null)}} submit="Upload document"/></Modal>}</>;
}
export function ReportsPage(){
 const{can}=useApp();const[preview,setPreview]=useState<string|null>(null),[from,setFrom]=useState(new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 const reports=[['employees','Employee directory','employees'],['attendance','Attendance records','attendance'],['leave','Leave requests','leave'],['payroll','Payroll runs','payroll'],['expenses','Expense claims','expenses'],['assets','Asset inventory','assets'],['goals','Performance goals','performance'],['candidates','Recruitment pipeline','recruitment']];
 const q=useData(preview===null?'':`${preview}${preview==='attendance'?`?from=${from}&to=${to}`:'?pageSize=500'}`,!!preview);
 return <><PageTitle title="Reports & analytics" subtitle="Export the records your role is authorized to access."/><div className="date-filters report-filters"><label>Attendance from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Attendance to<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="record-cards report-cards">{reports.filter(([, ,res])=>can(res,'EXPORT')).map(([name,label])=><section className="panel report-card" key={name}><span className="card-symbol"><FileText/></span><h2>{label}</h2><p>{name==='attendance'?'Selected date range.':'Current records, up to 500 per export.'}</p><div className="card-actions"><button className="btn secondary small" onClick={()=>setPreview(name)}><Eye size={16}/>Preview</button><a className="btn primary small" href={`/api/reports/${name}${name==='attendance'?`?from=${from}&to=${to}`:''}`}><Download size={16}/>CSV</a></div></section>)}</div>{preview&&<Modal title={readable(preview)+' report preview'} onClose={()=>setPreview(null)} wide><div className="modal-body">{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<><p>Showing the first 25 records in this preview.</p><Table rows={q.data.items.slice(0,25)} columns={Object.keys(q.data.items[0]).filter(k=>!['tenantId','personal','items','updatedAt'].includes(k)).slice(1,8)} cell={(r,k)=>typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}/><button className="btn secondary no-print" onClick={()=>window.print()}><Printer size={16}/>Print / Save PDF</button></>:<Empty title="No report data"/>}</div></Modal>}</>;
}
export function AuditPage(){const q=useData('audit');return <><PageTitle title="Audit trail" subtitle="A record of important changes and sign-in events. Latest 200 events."/><div className="panel">{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:q.data?.items?.length?<Table columns={['action','entity','actorId','ip','createdAt']} rows={q.data.items} cell={(r,k)=>k==='action'?readable(r.action.toLowerCase()):k==='createdAt'?new Date(r.createdAt).toLocaleString('en-IN'):undefined}/>:<Empty title="No events recorded"/>}</div></>}
export function SystemPage(){
 const q=useData('system'),ai=useData('system/ai-config'),branding=useData('system/branding'),companies=useData('platform/companies');const{session,notify,mutate}=useApp();
 const[form,setForm]=useState({provider:'OPENAI_COMPATIBLE',baseUrl:'',model:'',apiKey:'',enabled:false}),[testing,setTesting]=useState(false);
 const[brandLogo,setBrandLogo]=useState<string|null|undefined>(undefined),[brandSaving,setBrandSaving]=useState(false);
 const[updateForm,setUpdateForm]=useState({tenantId:'',title:'',message:''}),[updateSending,setUpdateSending]=useState(false);
 useEffect(()=>{if(ai.data)setForm(v=>({...v,provider:ai.data.provider??'OPENAI_COMPATIBLE',baseUrl:ai.data.baseUrl??'',model:ai.data.model??'',enabled:!!ai.data.enabled,apiKey:''}))},[ai.data]);
 async function saveAI(e:React.FormEvent){e.preventDefault();await mutate('system/ai-config','PUT',form);setForm(v=>({...v,apiKey:''}));await ai.refetch();await q.refetch();}
 async function testAI(){setTesting(true);try{const r=await api('system/ai-config/test','POST',{},session.csrf);notify(`AI connection successful · ${r.model}`)}catch(e:any){notify(e.message,true)}finally{setTesting(false)}}
 async function saveBranding(){setBrandSaving(true);try{await api('system/branding','PUT',{logo:brandLogo===undefined?(branding.data?.logo??null):brandLogo},session.csrf);setBrandLogo(undefined);await branding.refetch();notify('Platform logo updated.')}catch(e:any){notify(e.message,true)}finally{setBrandSaving(false)}}
 async function sendCompanyUpdate(e:React.FormEvent){e.preventDefault();setUpdateSending(true);try{const r=await api('system/company-update','POST',updateForm,session.csrf);notify(`Update sent to ${r.company.name}.`);setUpdateForm({tenantId:'',title:'',message:''})}catch(e:any){notify(e.message,true)}finally{setUpdateSending(false)}}
 const currentLogo=brandLogo===undefined?(branding.data?.logo??'/tcw-logo.png'):brandLogo;
 return <><PageTitle title="System health" subtitle="Platform health, branding, company communications, and secure AI provider settings."/>
 {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:<div className="record-cards system-health-cards">{Object.entries(q.data??{}).map(([k,v])=><div className="panel report-card" key={k}><h2>{readable(k)}</h2>{typeof v==='string'?<Badge value={v}/>:<strong className="large-number">{String(v)}</strong>}</div>)}</div>}
 <section className="panel platform-branding-panel"><div className="panel-heading"><div><h2>Platform branding</h2><p>Change the main TCW HR Software logo used across the HR and Super Admin portals. Company workspace logos remain separate.</p></div><Upload size={21}/></div>{branding.isLoading?<Loading/>:<div className="platform-branding-body"><div className="platform-logo-preview">{currentLogo?<img src={currentLogo} alt="Platform logo preview"/>:<span>TCW</span>}</div><div className="platform-branding-actions"><label className="btn secondary"><Upload size={16}/>Choose platform logo<input className="sr-only" type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){notify('Choose a logo up to 5 MB.',true);return;}const reader=new FileReader();reader.onload=()=>setBrandLogo(String(reader.result));reader.readAsDataURL(file)}}/></label><button type="button" className="btn secondary" onClick={()=>setBrandLogo(null)}><Trash2 size={16}/>Reset to default</button><button type="button" className="btn primary" disabled={brandSaving} onClick={saveBranding}>{brandSaving?'Saving…':'Save platform logo'}</button></div></div>}</section>
 <section className="panel company-update-panel"><div className="panel-heading"><div><h2>Send company update</h2><p>Publish a targeted announcement to one company. It appears in that company’s Notification center for all users.</p></div><Send size={21}/></div><form className="company-update-form" onSubmit={sendCompanyUpdate}><label><span>Company</span><select required value={updateForm.tenantId} onChange={e=>setUpdateForm({...updateForm,tenantId:e.target.value})}><option value="">Select company</option>{(companies.data?.items??[]).map((r:Row)=><option key={r.id} value={r.id}>{r.name} · {r.code}</option>)}</select></label><label><span>Update title</span><input required maxLength={160} value={updateForm.title} onChange={e=>setUpdateForm({...updateForm,title:e.target.value})} placeholder="Example: Payroll module update"/></label><label className="span-two"><span>Message</span><textarea required maxLength={2000} rows={5} value={updateForm.message} onChange={e=>setUpdateForm({...updateForm,message:e.target.value})} placeholder="Write the update that company users should see."/></label><div className="form-footer span-two"><button className="btn primary" disabled={updateSending||!updateForm.tenantId}>{updateSending?'Sending…':'Send update to company'}<Send size={16}/></button></div></form></section>
 <section className="panel ai-config-panel"><div className="panel-heading"><div><h2>AI Agent provider (optional)</h2><p>The built-in TCW AI Agent works without an API key. Add an OpenAI-compatible provider only if you want enhanced natural-language answers; keys remain encrypted at rest.</p></div><Sparkles size={21}/></div>{ai.isLoading?<Loading/>:ai.error?<Failure error={ai.error}/>:<form className="ai-config-form" onSubmit={saveAI}><div className="ai-config-status"><span className={'ai-status-dot '+(ai.data?.configured?'online':'')}/><div><strong>{ai.data?.configured?'AI ready':'AI not configured'}</strong><small>{ai.data?.configured?`${ai.data.model} · ${ai.data.apiKeyHint??'key stored'} · ${ai.data.source}`:'No provider key is required for monitoring and basic help.'}</small></div></div><div className="ai-config-grid"><label><span>Provider</span><select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="OPENAI_COMPATIBLE">OpenAI-compatible API</option></select></label><label><span>Base URL</span><input type="url" required={form.enabled} value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})} placeholder="https://api.example.com/v1"/></label><label><span>Model</span><input required={form.enabled} value={form.model} onChange={e=>setForm({...form,model:e.target.value})} placeholder="Provider model name"/></label><label><span>API key</span><div className="secret-input"><KeyRound size={17}/><input type="password" value={form.apiKey} onChange={e=>setForm({...form,apiKey:e.target.value})} placeholder={ai.data?.apiKeyHint?`Stored ${ai.data.apiKeyHint} · leave blank to keep`:'Paste API key'}/></div></label></div><label className="ai-enable"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span><strong>Enable enhanced AI responses</strong><small>The small TCW Agent continues monitoring and basic help even when this option is off.</small></span></label><div className="ai-config-actions"><button type="button" className="btn secondary" disabled={!ai.data?.configured||testing} onClick={testAI}><RefreshCw size={17} className={testing?'spin':''}/>{testing?'Testing…':'Test connection'}</button><button className="btn primary"><Check size={17}/>Save AI settings</button></div></form>}</section></>;
}
export function NotificationsPage(){
 const q=useData('notifications');const{session}=useApp();const[filter,setFilter]=useState('ALL'),[search,setSearch]=useState('');const rows:Row[]=q.data?.items??[];
 useEffect(()=>{if(!q.data||Number(q.data.unread??0)<=0)return;let active=true;(async()=>{try{await api('notifications/all','PATCH',{},session.csrf);if(active)await q.refetch()}catch{}})();return()=>{active=false}},[q.data?.unread,session.csrf]);
 const visible=rows.filter(r=>{const unread=!r.readAt;if(filter==='UNREAD'&&!unread)return false;if(filter==='SYSTEM'&&!/device|subscription|trial|payroll|system|support/i.test(`${r.title} ${r.message}`))return false;const needle=search.trim().toLowerCase();return !needle||`${r.title} ${r.message}`.toLowerCase().includes(needle)});
 const important=(r:Row)=>/overdue|offline|failed|expired|missing|urgent|error/i.test(`${r.title} ${r.message}`);
 return <><PageTitle title="Notification center" subtitle="Every company alert, workflow update and system signal in one timeline."/><div className="notification-summary"><div><strong>{q.data?.unread??rows.filter(r=>!r.readAt).length}</strong><span>Unread</span></div><div><strong>{rows.filter(important).length}</strong><span>Attention</span></div><div><strong>{rows.length}</strong><span>Recent updates</span></div></div><section className="panel notification-center"><div className="notification-toolbar"><div className="support-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search notifications…"/></div><div className="tabs compact"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>All</button><button className={filter==='UNREAD'?'active':''} onClick={()=>setFilter('UNREAD')}>Unread</button><button className={filter==='SYSTEM'?'active':''} onClick={()=>setFilter('SYSTEM')}>Operations</button></div></div>{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:visible.length?<div className="notification-timeline">{visible.map(r=><article className={'notification-row '+(!r.readAt?'unread ':'')+(important(r)?'important':'')} key={r.id}><span className="notification-icon">{important(r)?<AlertTriangle size={18}/>:<Bell size={18}/>}</span><div className="grow"><div className="row-between"><strong>{r.title}</strong><small><Clock3 size={13}/>{new Date(r.createdAt).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</small></div><p>{r.message}</p></div></article>)}</div>:<Empty title="Nothing in this view" description="Try another filter or search term."/>}</section></>}
export function AIPage(){
 const{session}=useApp();const status=useData('ai/status');const[question,setQuestion]=useState(''),[messages,setMessages]=useState<Row[]>([]),[busy,setBusy]=useState(false);
 const suggestions=['Summarize attendance exceptions this week','What should HR review before payroll?','Summarize current leave activity','Give me a concise workforce overview'];
 async function ask(text:string){if(!text.trim()||busy)return;setQuestion('');setBusy(true);setMessages(m=>[...m,{role:'user',text}]);try{const r=await api('ai','POST',{question:text},session.csrf);setMessages(m=>[...m,{role:'assistant',text:r.answer,model:r.model}])}catch(e:any){setMessages(m=>[...m,{role:'error',text:e.message}])}finally{setBusy(false)}}
 async function send(e:React.FormEvent){e.preventDefault();await ask(question)}
 return <><PageTitle title="TCW HR AI assistant" subtitle="Ask questions over authorized company facts without giving the model direct database access."><span className={'ai-ready-chip '+(status.data?.configured?'ready':'')}>{status.data?.configured?'AI Connected':'Setup Required'}</span></PageTitle><div className="ai-workspace"><aside className="panel ai-prompt-panel"><div className="ai-orb"><Sparkles size={28}/></div><h2>Start with a useful question</h2><p>The assistant can summarize attendance, leave and workforce signals visible to your role.</p><div className="ai-suggestions">{suggestions.map(v=><button key={v} disabled={!status.data?.configured||busy} onClick={()=>ask(v)}>{v}</button>)}</div><small>{status.data?.configured?`Model: ${status.data.model}`:'Ask your Super Admin to configure the AI provider in System health.'}</small></aside><div className="panel chat-panel ai-chat-panel"><div className="chat-messages">{!messages.length&&<Empty title={status.data?.configured?'Your HR copilot is ready':'AI setup is required'} description={status.data?.configured?'Choose a suggestion or ask a question below.':'The assistant will become available after the Super Admin saves and tests an API key.'}/>} {messages.map((m,i)=><div className={'chat-message '+m.role} key={i}><strong>{m.role==='user'?'You':m.role==='error'?'Service status':'TCW HR assistant'}</strong><p>{m.text}</p>{m.model&&<small>{m.model}</small>}</div>)}{busy&&<Loading/>}</div><form className="chat-compose" onSubmit={send}><input aria-label="Ask the assistant" value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about attendance, leave or payroll readiness…" required disabled={!status.data?.configured}/><button className="btn primary" disabled={busy||!status.data?.configured}><Send size={18}/><span>Send</span></button></form><small className="chat-note">AI supports human review only. Hiring, pay and disciplinary decisions remain with your team.</small></div></div></>;
}

