'use client';
import React,{useEffect,useState} from 'react';
import {RefreshCw,ShieldCheck,ArrowRight,Clock3,Check,Building2,Download,Monitor,AlertTriangle} from 'lucide-react';
import {useApp,useData,api,PageTitle,Loading,Failure,Confirm} from './core';
import './software-update.css';
const short=(v:any)=>String(v??'').slice(0,12)||'—';
export function SoftwareUpdatePage(){
 const{session,notify}=useApp();const q=useData('releases/status',true,30000);const[confirm,setConfirm]=useState(false),[checking,setChecking]=useState(false),[saving,setSaving]=useState(false);
 const s=q.data,available=!!s?.available,approved=!!s?.approved,isPlatform=session.user.scope==='PLATFORM';
 const[openedVersion,setOpenedVersion]=useState('');useEffect(()=>{if(!openedVersion&&s?.currentVersion)setOpenedVersion(String(s.currentVersion))},[openedVersion,s?.currentVersion]);
 const refreshNeeded=!!openedVersion&&!!s?.currentVersion&&openedVersion!==s.currentVersion;
 async function refreshDevice(){setSaving(true);try{const reg=await navigator.serviceWorker?.getRegistration?.();await reg?.update();if(reg?.installing){const worker=reg.installing;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(new Error('The device update is still preparing. Try again shortly.'))},15000);function changed(){if(['installed','activated','redundant'].includes(worker.state)){clearTimeout(timer);worker.removeEventListener('statechange',changed);resolve()}}worker.addEventListener('statechange',changed);changed()})}if(reg?.waiting){const worker=reg.waiting;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(new Error('The device update has not activated yet. Try again shortly.'))},15000);function changed(){if(worker.state==='activated'){clearTimeout(timer);worker.removeEventListener('statechange',changed);resolve()}}worker.addEventListener('statechange',changed);worker.postMessage({type:'TCW_ACTIVATE_APPROVED_WORKER'});changed()})}window.location.reload()}catch(e:any){notify(e.message??'Could not refresh this device.',true);setSaving(false)}}
 async function check(){setChecking(true);try{const r=await q.refetch();if(r.error)throw r.error;notify(r.data?.available?'A company release is available.':'You are on the current company release.')}catch(e:any){notify(e.message??'Could not check for updates.',true)}finally{setChecking(false)}}
 async function approve(){if(!s?.candidate)return;setSaving(true);try{await api('releases/approve','POST',{version:s.candidate.version},session.csrf);setConfirm(false);await q.refetch();notify('Release approved. Installation starts after all active company approvals and release checks pass.')}catch(e:any){notify(e.message??'Approval failed.',true);throw e}finally{setSaving(false)}}
 return <div className="update-center"><PageTitle title="Software update" subtitle="Review the next release. Your company controls when it goes live."/>
  {q.isLoading?<Loading/>:q.error?<Failure error={q.error} retry={()=>q.refetch()}/>:<>
   <section className={'update-hero '+(available?'has-update':'')}><div className="update-hero-mark">{available?<Download size={30}/>:<ShieldCheck size={32}/>}</div><div className="update-hero-copy"><span className="update-eyebrow">TCW HR · RELEASE CENTER</span><h2>{!s?.enabled?'Release control needs setup':available?approved?'Your company has approved this release':'A new company release is ready':'Your company is up to date'}</h2><p>{!s?.enabled?'Production release control has not been enabled. Contact your platform administrator.':available?approved?s?.ready?'All approvals are in. Verified installation is queued.':'Your current release stays active while other company approvals are pending.':'Your current software stays active until this release is approved and verified.':'You’re running the currently approved production release.'}</p></div><span className="update-status"><i/>{!s?.enabled?'SETUP REQUIRED':available?approved?'APPROVED':'AWAITING APPROVAL':'UP TO DATE'}</span></section>
   <div className="update-columns"><section className="update-panel"><div className="update-panel-head"><span className="update-small-icon"><Monitor size={19}/></span><div><small>RUNNING NOW</small><h3>Current company release</h3></div></div><div className="update-build"><span>Production build</span><strong>{short(s?.currentVersion)}</strong></div><dl className="update-facts"><div><dt>Release policy</dt><dd>Company approval</dd></div><div><dt>Installation</dt><dd>Verified release only</dd></div><div><dt>Last checked</dt><dd>{s?.checkedAt?new Date(s.checkedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'—'}</dd></div></dl><div className="update-safe-note"><ShieldCheck size={16}/><span>Your HR records remain on the server.</span></div></section>
    <section className="update-panel update-next"><div className="update-panel-head"><span className="update-small-icon"><RefreshCw size={19}/></span><div><small>{available?'AVAILABLE UPDATE':'RELEASE STATUS'}</small><h3>{available?'Review your next release':'No update waiting'}</h3></div></div>{available?<><span className="update-next-build">Build {short(s?.candidate?.version)}</span><h4>{s?.candidate?.title}</h4><p className="update-description">Approval applies to your whole company. Installation follows once every active company on this shared platform has approved and all checks have passed.</p>{approved&&<div className="update-approved"><Check size={17}/>{s?.ready?'Approved · installation queued':'Approved · waiting for company approvals'}</div>}{!s?.canApprove&&!approved&&<div className="update-safe-note"><Building2 size={16}/>Your HR/Admin must approve company updates.</div>}</>:<div className="update-empty"><ShieldCheck size={34}/><strong>Everything is current</strong><p>Check whenever you’re ready. New code in development does not automatically replace the company release.</p></div>}
     <div className="update-actions"><button className="btn secondary" disabled={checking||saving} onClick={check}><RefreshCw size={16}/>{checking?'Checking…':'Check for updates'}</button>{available&&s?.canApprove&&!approved&&<button className="btn primary" disabled={saving||checking} onClick={()=>setConfirm(true)}>Approve company update<ArrowRight size={16}/></button>}<button className={'btn '+(refreshNeeded?'primary':'secondary')} disabled={saving||checking} onClick={refreshDevice}>{saving?'Preparing…':refreshNeeded?'Apply approved release on this device':'Refresh this device'}<ArrowRight size={16}/></button></div>{isPlatform&&available&&<p className="update-description">Company approvals: {s?.approvedCompanies} / {s?.totalCompanies}</p>}</section></div>
   <section className="update-process"><div><span>01</span><h3>Review</h3><p>Read the release and check the build.</p></div><div><span>02</span><h3>Approve</h3><p>Your HR/Admin approves for the company.</p></div><div><span>03</span><h3>Install</h3><p>Verified releases enter the production queue.</p></div></section><div className="update-platform-note"><Clock3 size={17}/><p>All portals share one production release. Every active company must approve before it changes. The release queue checks about every 5 minutes; deployment can take longer. Your browser is never automatically reloaded.</p></div>
  </>}{confirm&&s?.candidate&&<Confirm title="Approve this company update?" description={'Approve build '+short(s.candidate.version)+' for all users in your company. The current release remains active until all active companies approve and verified deployment completes.'} onClose={()=>setConfirm(false)} onConfirm={approve}/>}</div>;
}
