'use client';
import React,{useEffect,useState} from 'react';
import {RefreshCw,ShieldCheck,ArrowRight,Clock3,Check,Building2,Download,Monitor} from 'lucide-react';
import {useApp,useData,api,PageTitle,Loading,Failure} from './core';
import './software-update.css';
const short=(v:any)=>String(v??'').slice(0,12)||'—';
export function SoftwareUpdatePage(){
 const{session,notify}=useApp();const q=useData('releases/status',true,30000);const[checking,setChecking]=useState(false),[saving,setSaving]=useState(false);
 const s=q.data,available=!!s?.available,requested=!!s?.updateRequested;
 const[openedVersion,setOpenedVersion]=useState('');useEffect(()=>{if(!openedVersion&&s?.currentVersion)setOpenedVersion(String(s.currentVersion))},[openedVersion,s?.currentVersion]);
 const refreshNeeded=!!openedVersion&&!!s?.currentVersion&&openedVersion!==s.currentVersion;
 async function refreshDevice(){setSaving(true);try{const reg=await navigator.serviceWorker?.getRegistration?.();await reg?.update();if(reg?.installing){const worker=reg.installing;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(new Error('The device update is still preparing. Try again shortly.'))},15000);function changed(){if(['installed','activated','redundant'].includes(worker.state)){clearTimeout(timer);worker.removeEventListener('statechange',changed);resolve()}}worker.addEventListener('statechange',changed);changed()})}if(reg?.waiting){const worker=reg.waiting;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(new Error('The device update has not activated yet. Try again shortly.'))},15000);function changed(){if(worker.state==='activated'){clearTimeout(timer);worker.removeEventListener('statechange',changed);resolve()}}worker.addEventListener('statechange',changed);worker.postMessage({type:'TCW_ACTIVATE_APPROVED_WORKER'});changed()})}window.location.reload()}catch(e:any){notify(e.message??'Could not update this device.',true);setSaving(false)}}
 async function check(){setChecking(true);try{const r=await q.refetch();if(r.error)throw r.error;if(r.data?.checkUnavailable){notify('Could not verify the latest update. Check again shortly; your current software remains active.',true);return;}notify(openedVersion&&r.data?.currentVersion&&openedVersion!==r.data.currentVersion?'A new version is ready for this device. Choose Update to load it.':r.data?.available?'A software update is available.':'Your software is up to date.')}catch(e:any){notify(e.message??'Could not check for updates.',true)}finally{setChecking(false)}}
 async function update(){if(!s?.candidate||saving)return;setSaving(true);try{await api('releases/update','POST',{version:s.candidate.version},session.csrf);await q.refetch();notify('Update requested. Deployment will start after release checks pass.')}catch(e:any){notify(e.message??'Could not start the software update.',true)}finally{setSaving(false)}}
 return <div className="update-center"><PageTitle title="Software update" subtitle="Check for the latest version and update your software when you’re ready."/>
  {q.isLoading?<Loading/>:q.error?<Failure error={q.error} retry={()=>q.refetch()}/>:<>
   <section className={'update-hero '+(available?'has-update':'')}><div className="update-hero-mark">{available?<Download size={30}/>:<ShieldCheck size={32}/>}</div><div className="update-hero-copy"><span className="update-eyebrow">TCW HR · SOFTWARE UPDATES</span><h2>{!s?.enabled?'Manual updates need setup':refreshNeeded?'Your software update is live':s?.checkUnavailable?'Update check is temporarily unavailable':available?requested?'Your software update is queued':'A software update is available':'Your software is up to date'}</h2><p>{!s?.enabled?'Manual updates have not been enabled. Contact your platform administrator.':refreshNeeded?'Choose Update when you’re ready to load the new release on this device.':s?.checkUnavailable?'Your current software remains active. Check again shortly to verify the latest update.':available?requested?'The update request is saved. Your current version stays active until verification and deployment finish.':'Choose Update to start. Your software stays on the current version until you do.':'You’re running the latest production version.'}</p></div><span className="update-status"><i/>{!s?.enabled?'SETUP REQUIRED':refreshNeeded?'READY TO UPDATE':s?.checkUnavailable?'CHECK AGAIN':available?requested?'UPDATE QUEUED':'UPDATE AVAILABLE':'UP TO DATE'}</span></section>
   <div className="update-columns"><section className="update-panel"><div className="update-panel-head"><span className="update-small-icon"><Monitor size={19}/></span><div><small>RUNNING NOW</small><h3>Current software version</h3></div></div><div className="update-build"><span>Production build</span><strong>{short(s?.currentVersion)}</strong></div><dl className="update-facts"><div><dt>Update control</dt><dd>Manual update</dd></div><div><dt>Installation</dt><dd>Verified release only</dd></div><div><dt>Last checked</dt><dd>{s?.checkedAt?new Date(s.checkedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'—'}</dd></div></dl><div className="update-safe-note"><ShieldCheck size={16}/><span>Your HR records remain on the server.</span></div></section>
    <section className="update-panel update-next"><div className="update-panel-head"><span className="update-small-icon"><RefreshCw size={19}/></span><div><small>{available?'AVAILABLE UPDATE':'UPDATE STATUS'}</small><h3>{s?.checkUnavailable?'Update check unavailable':available?'Your next software update':'No update waiting'}</h3></div></div>{available?<><span className="update-next-build">Build {short(s?.candidate?.version)}</span><h4>{s?.candidate?.title}</h4><p className="update-description">One click starts this software update. All three portals use the same version, so deployment updates the shared software.</p>{requested&&<div className="update-queued"><Check size={17}/>Update requested · verification and deployment pending</div>}{!s?.canUpdate&&!requested&&<div className="update-safe-note"><Building2 size={16}/>Your HR/Admin can start software updates.</div>}</>:<div className="update-empty"><ShieldCheck size={34}/><strong>{s?.checkUnavailable?'Check again shortly':'Everything is current'}</strong><p>{s?.checkUnavailable?'We could not verify the latest update. Your current version and HR records remain available.':'New releases stay available until an authorized administrator chooses Update.'}</p></div>}
     <div className="update-actions">{!refreshNeeded&&!s?.checkUnavailable&&available&&s?.canUpdate&&!requested&&<button className="btn primary" disabled={saving||checking} onClick={update}>{saving?'Starting update…':'Update'}<Download size={16}/></button>}<button className="btn secondary" disabled={checking||saving} onClick={check}><RefreshCw size={16}/>{checking?'Checking…':'Check for updates'}</button>{refreshNeeded&&<button className="btn primary" disabled={saving||checking} onClick={refreshDevice}>{saving?'Preparing…':'Update'}<ArrowRight size={16}/></button>}</div></section></div>
   <section className="update-process"><div><span>01</span><h3>Check</h3><p>Review the available version.</p></div><div><span>02</span><h3>Update</h3><p>Choose Update to start directly.</p></div><div><span>03</span><h3>Ready</h3><p>The new version goes live after verified deployment.</p></div></section><div className="update-platform-note"><Clock3 size={17}/><p>All portals share one production version. The release queue checks about every 5 minutes; verification and deployment can take longer. Your browser is never automatically reloaded.</p></div>
  </>}</div>;
}
