'use client';
import React,{useEffect,useRef,useState} from 'react';
import {RefreshCw,ShieldCheck,ArrowRight,Clock3,Check,Building2,Download,Monitor,LoaderCircle} from 'lucide-react';
import {useApp,useData,api,PageTitle,Loading,Failure} from './core';
import {downloadRelease,formatDownloadBytes,type DownloadProgress} from './update-download';
import './software-update.css';
const short=(v:any)=>String(v??'').slice(0,12)||'—';
const consentKey='tcw-manual-update-target';
async function activateDevice(){
 const reg=await navigator.serviceWorker?.getRegistration?.();await reg?.update();
 async function wait(worker:ServiceWorker,states:string[]){await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(new Error('The device update is still preparing. Retry Update shortly.'))},20000);function changed(){if(worker.state==='redundant'){clearTimeout(timer);worker.removeEventListener('statechange',changed);reject(new Error('The device update could not activate. Retry Update.'));}else if(states.includes(worker.state)){clearTimeout(timer);worker.removeEventListener('statechange',changed);resolve();}}worker.addEventListener('statechange',changed);changed();});}
 if(reg?.installing)await wait(reg.installing,['installed','activated']);
 if(reg?.waiting){const worker=reg.waiting;const ready=wait(worker,['activated']);worker.postMessage({type:'TCW_ACTIVATE_APPROVED_WORKER'});await ready;}
}
export function SoftwareUpdatePage(){
 const {session,notify}=useApp(),q=useData('releases/status',true,10000),s=q.data;
 const [checking,setChecking]=useState(false),[saving,setSaving]=useState(false),[openedVersion,setOpenedVersion]=useState(''),[target,setTarget]=useState('');
 const [progress,setProgress]=useState<DownloadProgress|null>(null),[phase,setPhase]=useState<'idle'|'download'|'install'>('idle'),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null),inflight=useRef(false);
 const available=!!s?.available,requested=!!s?.updateRequested,refreshNeeded=!!openedVersion&&!!s?.currentVersion&&openedVersion!==s.currentVersion;
 useEffect(()=>{if(openedVersion||!s?.currentVersion)return;const build=document.body.dataset.tcwBuild;const actual=build&&/^[a-f0-9]{40}$/.test(build)?build:String(s.currentVersion);setOpenedVersion(actual);try{const saved=sessionStorage.getItem(consentKey);if(saved===actual)sessionStorage.removeItem(consentKey);else if(saved&&/^[a-f0-9]{40}$/.test(saved))setTarget(saved);}catch{}},[openedVersion,s?.currentVersion]);
 useEffect(()=>()=>{controller.current?.abort()},[]);
 function remember(version:string){setTarget(version);try{sessionStorage.setItem(consentKey,version)}catch{}}
 function forget(){setTarget('');try{sessionStorage.removeItem(consentKey)}catch{}}
 async function install(version:string){
  if(inflight.current)return;inflight.current=true;setSaving(true);setError('');setPhase('download');setProgress(null);const abort=new AbortController();controller.current=abort;
  try{await downloadRelease(version,p=>{if(!abort.signal.aborted)setProgress(p)},{signal:abort.signal});setPhase('install');await activateDevice();if(abort.signal.aborted)return;forget();window.location.reload();}
  catch(e:any){abort.abort();forget();setError(e.name==='AbortError'?'Download paused. Choose Update to try again.':e.message??'Could not download this update. Retry Update.');setPhase('idle');setSaving(false);}
  finally{inflight.current=false;controller.current=null;}
 }
 // Only a device that explicitly chose Update may finish and open the new version.
 useEffect(()=>{if(target&&s?.currentVersion===target&&openedVersion&&openedVersion!==target&&!inflight.current&&!error)void install(target)},[target,s?.currentVersion,openedVersion,error]);
 async function check(){setChecking(true);try{const r=await q.refetch();if(r.error)throw r.error;if(r.data?.checkUnavailable){notify('Could not verify the latest update. Check again shortly.',true);return;}if(!target)notify(openedVersion&&r.data?.currentVersion&&openedVersion!==r.data.currentVersion?'A new version is ready for this device. Choose Update.':r.data?.available?'A software update is available.':'Your software is up to date.')}catch(e:any){notify(e.message??'Could not check for updates.',true)}finally{setChecking(false)}}
 async function update(){if(saving)return;setError('');if(refreshNeeded){remember(s.currentVersion);void install(s.currentVersion);return;}if(!s?.candidate)return;setSaving(true);try{const version=s.candidate.version;await api('releases/update','POST',{version},session.csrf);remember(version);await q.refetch();notify('Update started. Keep this page open; app files download when the servers are ready.')}catch(e:any){setError(e.message??'Could not start the update. Try again.')}finally{setSaving(false)}}
 const deploying=s?.deployment?.stage==='deploying',verifying=s?.deployment?.stage==='verifying',retrying=s?.deployment?.stage==='retrying';
 const active=phase!=='idle',title=active?phase==='download'?'Downloading your software update':'Opening your updated software':!s?.enabled?'Manual updates need setup':refreshNeeded?'Your software update is live':s?.checkUnavailable?'Update check is temporarily unavailable':available?requested?'Your software update is starting':'A software update is available':'Your software is up to date';
 const description=active?'Your HR records stay safely on the server.':refreshNeeded?'Choose Update to download the new app files and open this version.':s?.checkUnavailable?'Your current software remains active. Check again shortly.':requested?target?'Keep this page open. Once the servers are ready, your app files will download and this device will open the update.':'Another administrator started this release. Server preparation is in progress; choose Update when it is ready for this device.':available?'Choose Update to prepare the servers, download the app files and open the new version on this device.':'You’re running the latest production version.';
 const percent=progress?Math.min(progress.completed===progress.files?100:99,Math.floor(progress.received/progress.total*100)):0;
 return <div className="update-center"><PageTitle title="Software update" subtitle="One clear update flow, from server preparation to download and installation."/>
 {q.isLoading?<Loading/>:q.error?<Failure error={q.error} retry={()=>q.refetch()}/>:<>
  <section className={'update-hero '+(available?'has-update':'')}><div className="update-hero-mark">{active?<LoaderCircle className="spin" size={30}/>:available?<Download size={30}/>:<ShieldCheck size={32}/>}</div><div className="update-hero-copy"><span className="update-eyebrow">TCW HR · SOFTWARE UPDATES</span><h2>{title}</h2><p>{description}</p></div><span className="update-status"><i/>{active?phase==='download'?'DOWNLOADING':'INSTALLING':refreshNeeded?'READY TO UPDATE':requested?'PREPARING SERVERS':available?'UPDATE AVAILABLE':'UP TO DATE'}</span></section>
  <div className="update-columns"><section className="update-panel"><div className="update-panel-head"><span className="update-small-icon"><Monitor size={19}/></span><div><small>THIS DEVICE</small><h3>Current software version</h3></div></div><div className="update-build"><span>Opened on this device</span><strong>{short(openedVersion||s?.currentVersion)}</strong></div><dl className="update-facts"><div><dt>Server version</dt><dd>{short(s?.currentVersion)}</dd></div><div><dt>Update control</dt><dd>Manual update</dd></div><div><dt>Last checked</dt><dd>{s?.checkedAt?new Date(s.checkedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'—'}</dd></div></dl><div className="update-safe-note"><ShieldCheck size={16}/><span>Your HR records remain on the server.</span></div></section>
  <section className="update-panel update-next"><div className="update-panel-head"><span className="update-small-icon"><RefreshCw size={19}/></span><div><small>{available||refreshNeeded?'AVAILABLE UPDATE':'UPDATE STATUS'}</small><h3>{available||refreshNeeded?'Your next software update':'No update waiting'}</h3></div></div>{(available||refreshNeeded)&&<><span className="update-next-build">Build {short(refreshNeeded?s.currentVersion:s?.candidate?.version)}</span><h4>{s?.candidate?.title||'Verified software update'}</h4></>}
   {(requested||target)&&!active&&!refreshNeeded&&<div className="update-server-progress" role="status"><div><LoaderCircle size={19} className="spin"/><strong>{retrying?'Retrying server preparation':deploying?'Building and starting the servers':verifying?'Verifying the requested release':'Starting the update service'}</strong></div><progress aria-label="Server preparation"/><p>{retrying?'The update service lost its connection. Your saved request will retry automatically.':deploying?'The requested version has reached production. App files will download after the servers respond with the new version.':verifying?'The exact release checks must pass before server preparation starts.':'Your request is saved. The release watcher checks for it continuously while active.'}</p><small>No app files are downloading during server preparation.</small></div>}
   {progress&&<div className="update-download-progress" role="status"><div><strong>{phase==='install'?'Download complete':'App file download'}</strong><span>{percent}%</span></div><progress aria-label="App file download" max={100} value={percent}/><p><strong>{formatDownloadBytes(progress.received)}</strong> / {formatDownloadBytes(progress.total)}</p><small>{progress.completed} of {progress.files} files · Sizes before network compression</small></div>}
   {!available&&!refreshNeeded&&!active&&<div className="update-empty"><ShieldCheck size={34}/><strong>{s?.checkUnavailable?'Check again shortly':'Everything is current'}</strong><p>{s?.checkUnavailable?'Your current version remains available.':'New releases are applied only after an authorized administrator chooses Update.'}</p></div>}
   {error&&<div className="update-error" role="alert">{error}</div>}
   {!s?.canUpdate&&available&&!requested&&<div className="update-safe-note"><Building2 size={16}/>Your HR/Admin can start software updates.</div>}
   <div className="update-actions">{!active&&!s?.checkUnavailable&&(refreshNeeded||(available&&s?.canUpdate&&!requested))&&<button className="btn primary" disabled={saving||checking} onClick={update}>{saving?'Starting update…':'Update'}<Download size={16}/></button>}{!active&&<button className="btn secondary" disabled={checking||saving} onClick={check}><RefreshCw size={16}/>{checking?'Checking…':'Check for updates'}</button>}{phase==='download'&&<button className="btn secondary" onClick={()=>controller.current?.abort()}>Pause download</button>}</div>
  </section></div>
  <section className="update-process"><div><span>01</span><h3>Prepare servers</h3><p>The requested, verified release starts on all portals.</p></div><div><span>02</span><h3>Download</h3><p>Follow actual file progress in KB, MB or GB.</p></div><div><span>03</span><h3>Open update</h3><p>The device that chose Update opens the ready version.</p></div></section><div className="update-platform-note"><Clock3 size={17}/><p>Server builds can take several minutes. Downloads start after deployment; server preparation does not have a download size. Devices that have not chosen Update are never automatically reloaded.</p></div>
 </>}</div>;
}
