'use client';
import React,{useMemo,useState} from 'react';
import {Headphones,Plus,Search,Clock3,ShieldAlert,CheckCircle2,Building2,MessageSquare,ArrowUpRight,Send,RefreshCw,LifeBuoy} from 'lucide-react';
import './support-design.css';
import {Avatar,Badge,Empty,Failure,Loading,Modal,useApp,useData,displayDate} from './core';
import {Field,Row,readable} from './config';

const createFields:Field[]=[
 {key:'subject',label:'Subject',required:true},
 {key:'category',label:'Category',type:'select',required:true,default:'GENERAL',options:['TECHNICAL','LOGIN','BILLING','ATTENDANCE','PAYROLL','LEAVE','GENERAL']},
 {key:'priority',label:'Priority',type:'select',required:true,default:'NORMAL',options:['LOW','NORMAL','HIGH','URGENT']},
 {key:'message',label:'Describe the issue',type:'textarea',required:true,hint:'Include the exact screen, error and what you expected to happen.'}
];

function SupportTicketForm({ticket,onClose,onSaved}:{ticket?:Row;onClose:()=>void;onSaved:(ticket:Row)=>void}){
 const{mutate}=useApp(),agent=!!ticket;
 const[subject,setSubject]=useState(''),[category,setCategory]=useState('GENERAL'),[priority,setPriority]=useState('NORMAL'),[message,setMessage]=useState('');
 const[status,setStatus]=useState(String(ticket?.status??'OPEN')),[assignedTo,setAssignedTo]=useState(String(ticket?.assignedTo??''));
 const[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();if(saving)return;if(!message.trim()||!agent&&!subject.trim()){setError('Add a subject and a clear description before sending.');return;}setSaving(true);setError('');try{const saved=await mutate(agent?`platform/support/${ticket!.id}`:'support',agent?'PATCH':'POST',agent?{status,assignedTo:assignedTo.trim(),response:message.trim()}:{subject:subject.trim(),category,priority,message:message.trim()});onSaved(saved);}catch(e){setError(e instanceof Error?e.message:'Unable to save this ticket. Please try again.');}finally{setSaving(false);}}
 return <form className="support-new-form" aria-label={agent?'Support agent update':'Support ticket request'} onSubmit={save}>
  <div className="support-form-intro"><span><Headphones size={23}/></span><div><strong>{agent?'Move this request forward':'Tell us how we can help'}</strong><p>{agent?'Update the ticket and share a clear response with the customer.':'Choose a topic, describe the issue and send it to TCW Support.'}</p></div></div>
  {agent?<section className="support-form-section"><header><b>01</b><div><h3>Ticket ownership</h3><p>{ticket!.ticketNumber} · {ticket!.subject}</p></div></header><div className="support-form-columns"><label><span>Status</span><select aria-label="Update ticket status" value={status} onChange={e=>setStatus(e.target.value)}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select></label><label><span>Assigned agent</span><input aria-label="Assigned agent" value={assignedTo} maxLength={120} onChange={e=>setAssignedTo(e.target.value)} placeholder="Agent name"/></label></div></section>:<section className="support-form-section"><header><b>01</b><div><h3>Choose the topic</h3><p>Route your request to the right area.</p></div></header><div className="support-topic-grid">{createFields[1].options?.map(v=><button type="button" key={v} aria-pressed={category===v} onClick={()=>setCategory(v)}><MessageSquare size={16}/>{readable(v.toLowerCase())}{category===v&&<CheckCircle2 size={14}/>}</button>)}</div><label><span>Subject <em>*</em></span><input aria-label="Ticket subject" value={subject} maxLength={200} required onChange={e=>setSubject(e.target.value)} placeholder="A short summary of the issue"/></label><label><span>Priority</span><select aria-label="New ticket priority" value={priority} onChange={e=>setPriority(e.target.value)}>{['LOW','NORMAL','HIGH','URGENT'].map(v=><option key={v} value={v}>{readable(v.toLowerCase())}</option>)}</select><small>Choose Urgent when the issue blocks your team’s work.</small></label></section>}
  <section className="support-form-section"><header><b>02</b><div><h3>{agent?'Customer response':'Describe the issue'}</h3><p>{agent?'The customer can read this response in their ticket conversation.':'Include the screen, what happened and what you expected.'}</p></div></header><textarea aria-label={agent?'Customer response':'Describe the issue'} value={message} maxLength={5000} required rows={6} onChange={e=>setMessage(e.target.value)} placeholder={agent?'Explain the action taken or the next step…':'What happened? When did it happen? What should happen instead?'}/><div className="support-form-counter"><span>Keep passwords and OTPs out of your message.</span><small>{message.length.toLocaleString()} / 5,000</small></div></section>
  {error&&<div className="support-form-error" role="alert">{error}</div>}<footer className="support-form-footer"><button type="button" className="btn secondary" onClick={onClose} disabled={saving}>Cancel</button><button type="submit" className="btn primary" disabled={saving||!message.trim()||!agent&&!subject.trim()}><Send size={16}/>{saving?'Sending…':agent?'Save ticket update':'Create ticket'}</button></footer>
 </form>;
}

function TicketThread({ticket,platform}:{ticket:Row;platform:boolean}){
 const q=useData(`support/${ticket.id}/messages`);const{mutate,can}=useApp();const[internal,setInternal]=useState(false);const[error,setError]=useState('');const[reply,setReply]=useState(''),[sending,setSending]=useState(false);
 async function send(e:React.FormEvent){e.preventDefault();if(!reply.trim())return;setSending(true);setError('');try{await mutate(`support/${ticket.id}/messages`,'POST',{message:reply.trim(),internal:platform&&internal});setReply('')}catch(e){setError(e instanceof Error?e.message:'Unable to send reply. Please try again.')}finally{setSending(false)}}
 const messages:Row[]=q.data?.items??[];
 return <section className="ticket-thread support-conversation"><div className="ticket-thread-head"><div><span className="detail-label">Conversation</span><strong>{messages.length} update{messages.length===1?'':'s'}</strong></div><button type="button" className="icon-button" aria-label="Refresh conversation" disabled={q.isFetching} onClick={()=>q.refetch()}><RefreshCw size={17}/></button></div>{q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:messages.length?<div className="ticket-thread-list">{messages.map(m=><article key={m.id} className={'ticket-message-bubble '+(m.authorScope==='PLATFORM'?'support':'customer')+(m.internal?' internal':'')}><div className="ticket-message-meta"><Avatar name={m.authorName??'Support'}/><strong>{m.authorName}</strong><span>{m.authorScope==='PLATFORM'?'TCW Support':'Company'} · {new Date(m.createdAt).toLocaleString('en-IN')}</span>{m.internal&&<Badge value="INTERNAL"/>}</div><p>{m.message}</p></article>)}</div>:<Empty title="No conversation yet" description="Updates to this ticket will appear here."/>}{can('support',platform?'EDIT':'CREATE')&&<form className="ticket-reply" onSubmit={send}><div className="support-composer-heading"><MessageSquare size={16}/><strong>{internal?'Private internal note':'Write a reply'}</strong></div><textarea value={reply} onChange={e=>setReply(e.target.value)} maxLength={5000} aria-label="Ticket reply" placeholder={internal?"Private note for support agents…":"Write a reply…"} required/>{platform&&<label className="support-private-note"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/>Internal note · visible only to support agents</label>}{error&&<p className="support-reply-error" role="alert">{error}</p>}{!platform&&ticket.status==='RESOLVED'&&<small>Sending a reply reopens this ticket.</small>}<div className="support-composer-footer"><small>{reply.length.toLocaleString()} / 5,000</small><button className="btn primary" disabled={sending||!reply.trim()}>{sending?'Sending…':<><Send size={16}/>Send reply</>}</button></div></form>}</section>
}

export function SupportPage(){
 const{session,mutate,can}=useApp();const platform=session.user.scope==='PLATFORM';
 const q=useData(platform?'platform/support':'support?pageSize=250');
 const[open,setOpen]=useState(false),[detail,setDetail]=useState<Row|null>(null),[review,setReview]=useState<Row|null>(null),[status,setStatus]=useState('ACTIVE'),[priority,setPriority]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('UPDATED'),[page,setPage]=useState(1);
 const rows:Row[]=q.data?.items??[];
 const filtered=useMemo(()=>rows.filter(r=>{
   const active=status==='ACTIVE'?!['RESOLVED'].includes(r.status):status==='ALL'||r.status===status;
   const p=!priority||r.priority===priority;
   const needle=query.trim().toLowerCase();
   const text=`${r.ticketNumber??''} ${r.subject??''} ${r.category??''} ${r.company?.name??''}`.toLowerCase();
   return active&&p&&(!category||r.category===category)&&(!needle||text.includes(needle));
 }).sort((a,b)=>sort==='PRIORITY'?(['URGENT','HIGH','NORMAL','LOW'].indexOf(a.priority)-['URGENT','HIGH','NORMAL','LOW'].indexOf(b.priority)):sort==='OLDEST'?+new Date(a.createdAt)-+new Date(b.createdAt):+new Date(b.updatedAt??b.createdAt)-+new Date(a.updatedAt??a.createdAt)),[rows,status,priority,category,sort,query]);
 const pages=Math.max(1,Math.ceil(filtered.length/12)),safePage=Math.min(page,pages),pageRows=filtered.slice((safePage-1)*12,safePage*12),currentDetail=detail?(rows.find(r=>r.id===detail.id)??detail):null;
 const reset=()=>{setStatus('ACTIVE');setPriority('');setCategory('');setQuery('');setSort('UPDATED');setPage(1)};
 const openCount=rows.filter(r=>r.status==='OPEN').length,inProgress=rows.filter(r=>r.status==='IN_PROGRESS').length,urgent=rows.filter(r=>r.priority==='URGENT'&&r.status!=='RESOLVED').length,resolved=rows.filter(r=>r.status==='RESOLVED').length;
 return <div className="support-v4 support-v5">
  <header className="support-v4-hero"><div className="support-v5-heading"><span className="support-v4-hero-icon"><LifeBuoy size={28}/></span><div><small>WORKSPACE / SUPPORT</small><h1>{platform?'Support command center':'Support center'}</h1><p>{platform?'One place for every customer request, response and resolution.':'Your requests, conversations and answers. All in one place.'}</p></div></div>{!platform&&can('support','CREATE')&&<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>New ticket</button>}</header>
  <div className="support-v5-overview">{[{label:'Open',value:openCount,detail:'Awaiting a response',icon:Headphones,status:'OPEN'},{label:'In progress',value:inProgress,detail:'Being worked on',icon:Clock3,status:'IN_PROGRESS'},{label:'Urgent',value:urgent,detail:'Needs attention',icon:ShieldAlert,status:'ACTIVE'},{label:'Resolved',value:resolved,detail:'Issue completed',icon:CheckCircle2,status:'RESOLVED'}].map(item=><button type="button" key={item.label} onClick={()=>{setStatus(item.status);setPriority(item.label==='Urgent'?'URGENT':'');setPage(1)}}><span><item.icon size={20}/></span><div><small>{item.label}</small><strong>{item.value}</strong><p>{item.detail}</p></div><ArrowUpRight size={15}/></button>)}</div>
  <div className="support-v4-layout"><section className="panel support-board"><div className="support-v4-board-heading"><div><h2>Ticket inbox</h2><span>{filtered.length} matching request{filtered.length===1?'':'s'}</span></div><button className="btn secondary small" disabled={q.isFetching} onClick={()=>q.refetch()}>{q.isFetching?'Refreshing…':'Refresh'}</button></div>
   <div className="support-toolbar"><div className="support-search"><Search size={17}/><input aria-label="Search support tickets" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search ticket, subject or company…"/></div><div className="toolbar-actions"><select aria-label="Ticket status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="ACTIVE">Active tickets</option><option value="ALL">All tickets</option><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select><select aria-label="Ticket priority" value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option value="">All priorities</option>{['URGENT','HIGH','NORMAL','LOW'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Ticket category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All categories</option>{createFields[1].options?.map(v=><option key={v} value={v}>{readable(v.toLowerCase())}</option>)}</select><select aria-label="Sort support tickets" value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="UPDATED">Recently updated</option><option value="OLDEST">Oldest first</option><option value="PRIORITY">Highest priority</option></select><button className="text-button" onClick={reset}>Reset filters</button></div></div>
   {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:filtered.length?<div className="support-ticket-list">{pageRows.map(r=>{
    const overdue=r.slaDueAt&&new Date(r.slaDueAt)<new Date()&&r.status!=='RESOLVED';
    return <article className={'support-ticket '+(overdue?'sla-overdue':'')} key={r.id} role="button" tabIndex={0} aria-label={'Open ticket '+r.ticketNumber+': '+r.subject} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setDetail(r)}}} onClick={()=>setDetail(r)}>
      <div className="support-ticket-main"><div className="ticket-number">{r.ticketNumber??'TCW SUPPORT'}</div><h3>{r.subject}</h3><p>{r.message}</p><div className="ticket-meta">{platform&&r.company&&<span><Building2 size={14}/>{r.company.name} · {r.company.code}</span>}<span><MessageSquare size={14}/>{readable(String(r.category??'GENERAL').toLowerCase())}</span><span><Clock3 size={14}/>{displayDate(r.createdAt)}</span></div></div>
      <div className="support-ticket-side"><Badge value={r.priority}/><Badge value={r.status}/>{overdue&&<span className="sla-chip overdue">SLA due</span>}{!overdue&&r.slaDueAt&&<span className="sla-chip">SLA {new Date(r.slaDueAt).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</span>}<button className="text-button" onClick={e=>{e.stopPropagation();platform&&can('support','EDIT')?setReview(r):setDetail(r)}}>{platform&&can('support','EDIT')?'Work ticket':'View details'} <ArrowUpRight size={14}/></button></div>
    </article>})}</div>:<Empty title="No tickets in this view" description={platform?'The support queue is clear for the selected filters.':'Create a ticket whenever your team needs product or billing help.'}/>}
  {filtered.length>12&&<div className="support-v4-pagination"><span>Page {safePage} of {pages}</span><button className="btn secondary small" disabled={safePage===1} onClick={()=>setPage(safePage-1)}>Previous</button><button className="btn secondary small" disabled={safePage===pages} onClick={()=>setPage(safePage+1)}>Next</button></div>}</section><aside className="support-v4-guide"><span className="support-v4-guide-icon"><MessageSquare size={22}/></span><h2>Get help faster</h2><p>A clear request helps us understand what happened.</p><ol><li><strong>Name the screen</strong><span>Attendance, Payroll, People or another module.</span></li><li><strong>Describe the issue</strong><span>Include the steps and exact error you see.</span></li><li><strong>Share what you expected</strong><span>Include the date, shift or ticket reference when relevant.</span></li></ol><div className="support-v4-privacy"><ShieldAlert size={17}/><p>Keep passwords, OTPs and bank details out of support messages.</p></div></aside></div>
  {open&&<Modal title="New support request" onClose={()=>setOpen(false)} wide><SupportTicketForm onClose={()=>setOpen(false)} onSaved={ticket=>{setOpen(false);setDetail(ticket)}}/></Modal>}
  {currentDetail&&<Modal title="Ticket details" onClose={()=>setDetail(null)} wide><div className="support-ticket-detail"><header className="support-detail-title"><div><span>{currentDetail.ticketNumber??'Support request'}</span><h2>{currentDetail.subject}</h2></div><Badge value={currentDetail.status}/></header><div className="support-detail-workspace"><main><section className="support-original-request"><span className="detail-label">ORIGINAL REQUEST</span><p>{currentDetail.message}</p></section><TicketThread key={currentDetail.id} ticket={currentDetail} platform={platform}/></main><aside className="support-ticket-context"><h3>Request details</h3><dl><div><dt>Category</dt><dd>{readable(String(currentDetail.category??'GENERAL').toLowerCase())}</dd></div><div><dt>Priority</dt><dd><Badge value={currentDetail.priority}/></dd></div><div><dt>Created</dt><dd>{new Date(currentDetail.createdAt).toLocaleString('en-IN')}</dd></div>{currentDetail.slaDueAt&&<div><dt>Response due</dt><dd>{new Date(currentDetail.slaDueAt).toLocaleString('en-IN')}</dd></div>}{currentDetail.assignedTo&&<div><dt>Assigned to</dt><dd>{currentDetail.assignedTo}</dd></div>}{currentDetail.closedAt&&<div><dt>Resolved</dt><dd>{new Date(currentDetail.closedAt).toLocaleString('en-IN')}</dd></div>}</dl><div className="support-resolution-note"><CheckCircle2 size={18}/><strong>{currentDetail.status==='RESOLVED'?'This request is resolved':currentDetail.status==='IN_PROGRESS'?'Your request is in progress':'Your request is open'}</strong><p>{currentDetail.status==='RESOLVED'?'Still need help? Reply below to reopen your request.':'Responses and updates appear in this conversation.'}</p></div>{platform&&can('support','EDIT')&&<button type="button" className="btn primary" onClick={()=>{setReview(currentDetail);setDetail(null)}}>Update ticket</button>}</aside></div></div></Modal>}
  {review&&<Modal title="Update support request" onClose={()=>setReview(null)} wide><SupportTicketForm ticket={review} onClose={()=>setReview(null)} onSaved={ticket=>{setReview(null);setDetail(ticket)}}/></Modal>}
 </div>;
}
