'use client';
import './hr-operations.css';
import React,{useState} from 'react';
import {ShieldCheck} from 'lucide-react';
import {Row} from './config';
import {api,useApp,useData,Loading,Failure,Modal,RecordForm} from './core';
export function TwoFactorSettings(){
  const {session}=useApp(),q=useData('auth/two-factor'),[open,setOpen]=useState<'setup'|'disable'|null>(null),[setup,setSetup]=useState<Row|null>(null),[codes,setCodes]=useState<string[]|null>(null);
  return <section className="panel hr-two-factor"><div className="panel-heading"><div><h2>Authenticator protection</h2><p>Add a second factor to sign-in for this account.</p></div><ShieldCheck size={22}/></div><div className="modal-body">
    {q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:<><strong>{q.data?.enabled?'Two-factor authentication is enabled':'Two-factor authentication is off'}</strong><p className="subtle-note">{q.data?.enabled?`${q.data.recoveryCodesRemaining} recovery codes remaining. Keep these somewhere safe.`:'Use an authenticator app that accepts a setup key. Setup does not activate protection until a valid code is confirmed.'}</p><button className="btn secondary" disabled={!q.data?.configured} onClick={()=>setOpen(q.data?.enabled?'disable':'setup')}>{q.data?.enabled?'Disable authenticator':'Set up authenticator'}</button>{!q.data?.configured&&<p className="subtle-note">Server encryption configuration is required before setup is available.</p>}</>}
  </div>{open==='setup'&&<Modal title="Set up authenticator" onClose={()=>{setOpen(null);setSetup(null)}}><div className="modal-body">{setup?<><p>In your authenticator app, choose <strong>Enter setup key</strong>, select time-based codes, and enter this key. Setup expires after 10 minutes.</p><code className="hr-auth-key">{setup.secret}</code><p>Account: {session.user.email} · Issuer: TCW HR</p></>:<p>Confirm your password to create a private authenticator setup key.</p>}</div><RecordForm key={setup?'confirm':'begin'} fields={[{key:'currentPassword',label:'Current password',type:'password',required:true},...(setup?[{key:'code',label:'Authenticator code',required:true}]:[])]} onCancel={()=>{setOpen(null);setSetup(null)}} onSave={async values=>{if(!setup){setSetup(await api('auth/two-factor/setup','POST',values,session.csrf));}else{const result=await api('auth/two-factor/enable','POST',values,session.csrf);setCodes(result.recoveryCodes);setOpen(null);setSetup(null);await q.refetch()}}} submit={setup?'Enable authenticator':'Create setup key'}/></Modal>}
  {open==='disable'&&<Modal title="Disable authenticator" onClose={()=>setOpen(null)}><div className="modal-body"><p>Confirm your password and an unused authenticator or recovery code. Other sessions will be signed out.</p></div><RecordForm fields={[{key:'currentPassword',label:'Current password',type:'password',required:true},{key:'code',label:'Authenticator or recovery code',required:true}]} onCancel={()=>setOpen(null)} onSave={async values=>{await api('auth/two-factor/disable','POST',values,session.csrf);setOpen(null);await q.refetch()}} submit="Disable authenticator"/></Modal>}
  {codes&&<Modal title="Save your recovery codes" onClose={()=>setCodes(null)}><div className="modal-body"><p>These codes are shown only now. Each code can sign in once if your authenticator is unavailable.</p><div className="hr-recovery-codes">{codes.map(c=><code key={c}>{c}</code>)}</div><button className="btn secondary" onClick={()=>{const blob=new Blob(['TCW HR recovery codes\n'+codes.join('\n')],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='tcw-recovery-codes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download recovery codes</button><p className="subtle-note">Keep the downloaded file private. Codes are stored as hashes on the server.</p></div></Modal>}
  </section>;
}
